package schemahealth

// RequiredTables is the minimum table set needed for the current runtime
// modules to serve requests without schema-drift 500s.
var RequiredTables = []string{
	"user",
	"workspaces",
	"workspace_members",
	"workspace_roles",
	"role_permissions",
	"organizations",
	"organization_members",
	"organization_invites",
	"clients",
	"team_members",
	"projects",
	"tasks",
	"deals",
	"deliverables",
	"calendar_events",
	"glossary_terms",
	"rhythm_entries",
	"campaigns",
	"offers",
	"personas",
	"content_items",
	"sites",
	"knowledge_documents",
	"boards",
	"workspace_preferences",
	"workspace_apps",
	"app_catalog",
	"workspace_desktop_spaces",
	"desktop3d_layouts",
	"workspace_storage",
	"miosa_workspace_links",
	"module_installations",
	"entity_links",
	"intelligence_reports",
	"drive_files",
	"workspace_agents",
	"workspace_agent_runs",
	"agent_runs",
	"engines_workflows",
	"engines_runs",
	"builders",
	"resources",
	"assets",
	"communication_routes",
	"microsoft_teams_channels",
	"microsoft_teams_messages",
	"microsoft_subscriptions",
	"google_gmail_watches",
	"instagram_workspace_credentials",
	"instagram_oauth_states",
	"custom_module_versions",
	"custom_module_installations",
	"custom_module_shares",
}

// RequiredColumns covers columns that have repeatedly drifted between local,
// CI, cloud, and generated sqlc code.
var RequiredColumns = map[string][]string{
	"workspace_members": {
		"workspace_id",
		"user_id",
		"role",
		"role_id",
		"custom_permissions",
	},
	"workspace_roles": {
		"workspace_id",
		"name",
		"permissions",
	},
	"clients": {
		"workspace_id",
		"pipeline_stage",
		"agency_type",
		"outreach_status",
		"offer_fit",
		"fit_score",
		"next_step_date",
	},
	"team_members": {
		"workspace_id",
	},
	"deals": {
		"client_id",
		"stage_id",
		"amount",
		"status",
	},
	"deliverables": {
		"workspace_id",
		"title",
		"kind",
		"status",
	},
	"pipelines": {
		"workspace_id",
	},
	"tasks": {
		"workspace_id",
		"estimated_hours",
	},
	"calendar_events": {
		"workspace_id",
		"user_id",
		"google_event_id",
	},
	"workspace_apps": {
		"workspace_id",
		"catalog_app_id",
		"url",
		"launch_mode",
		"show_on_desktop",
		"show_in_dock",
		"position_index",
		"provider",
	},
	"app_catalog": {
		"name",
		"url",
		"launch_mode",
		"logo_url",
		"category",
	},
	"workspace_desktop_spaces": {
		"workspace_id",
		"name",
		"kind",
		"config",
	},
	"desktop3d_layouts": {
		"user_id",
		"name",
		"is_active",
		"modules",
	},
	"workspace_storage": {
		"workspace_id",
		"cloud_sync_activated",
	},
	"miosa_workspace_links": {
		"workspace_id",
		"miosa_workspace_id",
		"external_workspace_id",
		"external_user_id",
	},
	"module_installations": {
		"workspace_id",
	},
	"entity_links": {
		"workspace_id",
	},
	"content_items": {
		"workspace_id",
		"theme",
		"views",
		"reach",
		"likes",
		"comments",
		"saves",
		"shares",
		"reposts",
		"follows",
		"profile_activity",
		"accounts_engaged",
		"avg_watch_time_seconds",
		"retention_rate",
		"analytics_notes",
	},
}

// RequiredFunctions are DB-side helpers relied on by auth/workspace setup.
var RequiredFunctions = []string{
	"seed_default_workspace_roles",
}
