// Code generated by weaver. DO NOT EDIT.
// source: semconv/model

package semconv

import "go.opentelemetry.io/otel/attribute"

// A2a Attributes
const (
	// A2A_AGENT_IDKey is the OTel attribute key for a2a.agent.id.
	// Identifier of the target agent in an A2A call.
	A2A_AGENT_IDKey = attribute.Key("a2a.agent.id")
	// A2A_DEAL_IDKey is the OTel attribute key for a2a.deal.id.
	// Identifier of the deal being created or operated on via A2A.
	A2A_DEAL_IDKey = attribute.Key("a2a.deal.id")
	// A2A_DEAL_TYPEKey is the OTel attribute key for a2a.deal.type.
	// Type of the A2A deal.
	A2A_DEAL_TYPEKey = attribute.Key("a2a.deal.type")
	// A2A_OPERATIONKey is the OTel attribute key for a2a.operation.
	// The A2A operation name being invoked.
	A2A_OPERATIONKey = attribute.Key("a2a.operation")
	// A2A_SOURCE_SERVICEKey is the OTel attribute key for a2a.source.service.
	// Service initiating the A2A call (sender).
	A2A_SOURCE_SERVICEKey = attribute.Key("a2a.source.service")
	// A2A_TARGET_SERVICEKey is the OTel attribute key for a2a.target.service.
	// Service receiving the A2A call (receiver).
	A2A_TARGET_SERVICEKey = attribute.Key("a2a.target.service")
)

// A2aAgentId returns an attribute KeyValue for a2a.agent.id.
func A2aAgentId(val string) attribute.KeyValue {
	return A2A_AGENT_IDKey.String(val)
}

// A2aDealId returns an attribute KeyValue for a2a.deal.id.
func A2aDealId(val string) attribute.KeyValue {
	return A2A_DEAL_IDKey.String(val)
}

// A2aDealType returns an attribute KeyValue for a2a.deal.type.
func A2aDealType(val string) attribute.KeyValue {
	return A2A_DEAL_TYPEKey.String(val)
}

// A2aOperation returns an attribute KeyValue for a2a.operation.
func A2aOperation(val string) attribute.KeyValue {
	return A2A_OPERATIONKey.String(val)
}

// A2aSourceService returns an attribute KeyValue for a2a.source.service.
func A2aSourceService(val string) attribute.KeyValue {
	return A2A_SOURCE_SERVICEKey.String(val)
}

// A2aTargetService returns an attribute KeyValue for a2a.target.service.
func A2aTargetService(val string) attribute.KeyValue {
	return A2A_TARGET_SERVICEKey.String(val)
}

