// Code generated by weaver. DO NOT EDIT.
// source: semconv/model

package semconv

import "go.opentelemetry.io/otel/attribute"

// Agent Attributes
const (
	// AGENT_DECISION_TYPEKey is the OTel attribute key for agent.decision_type.
	// Type of decision made by the agent in the ReAct loop.
	AGENT_DECISION_TYPEKey = attribute.Key("agent.decision_type")
	// AGENT_IDKey is the OTel attribute key for agent.id.
	// Unique identifier of the agent.
	AGENT_IDKey = attribute.Key("agent.id")
	// AGENT_LLM_MODELKey is the OTel attribute key for agent.llm_model.
	// The LLM model used for agent inference.
	AGENT_LLM_MODELKey = attribute.Key("agent.llm_model")
	// AGENT_OUTCOMEKey is the OTel attribute key for agent.outcome.
	// Outcome of the agent decision.
	AGENT_OUTCOMEKey = attribute.Key("agent.outcome")
	// AGENT_TOKEN_COUNTKey is the OTel attribute key for agent.token_count.
	// Total token count for the agent inference.
	AGENT_TOKEN_COUNTKey = attribute.Key("agent.token_count")
)

// AgentDecisionType returns an attribute KeyValue for agent.decision_type.
func AgentDecisionType(val string) attribute.KeyValue {
	return AGENT_DECISION_TYPEKey.String(val)
}

// AgentId returns an attribute KeyValue for agent.id.
func AgentId(val string) attribute.KeyValue {
	return AGENT_IDKey.String(val)
}

// AgentLlmModel returns an attribute KeyValue for agent.llm_model.
func AgentLlmModel(val string) attribute.KeyValue {
	return AGENT_LLM_MODELKey.String(val)
}

// AgentOutcome returns an attribute KeyValue for agent.outcome.
func AgentOutcome(val string) attribute.KeyValue {
	return AGENT_OUTCOMEKey.String(val)
}

// AgentOutcomeValues contains the known values for agent.outcome.
var AgentOutcomeValues = struct {
	Success string
	Failure string
	Escalated string
}{
	Success: "success",
	Failure: "failure",
	Escalated: "escalated",
}

// AgentTokenCount returns an attribute KeyValue for agent.token_count.
func AgentTokenCount(val int64) attribute.KeyValue {
	return AGENT_TOKEN_COUNTKey.Int64(val)
}

