// Code generated by weaver. DO NOT EDIT.
// source: semconv/model

package semconv

import "go.opentelemetry.io/otel/attribute"

// Bos Attributes
const (
	// BOS_AGENT_SERVICEKey is the OTel attribute key for bos.agent.service.
	// Name of the BusinessOS AI service or agent handling the operation.
	BOS_AGENT_SERVICEKey = attribute.Key("bos.agent.service")
	// BOS_COMPLIANCE_FRAMEWORKKey is the OTel attribute key for bos.compliance.framework.
	// Compliance framework being evaluated or enforced.
	BOS_COMPLIANCE_FRAMEWORKKey = attribute.Key("bos.compliance.framework")
	// BOS_COMPLIANCE_PASSEDKey is the OTel attribute key for bos.compliance.passed.
	// Whether the compliance check passed (true) or failed (false).
	BOS_COMPLIANCE_PASSEDKey = attribute.Key("bos.compliance.passed")
	// BOS_COMPLIANCE_RULE_IDKey is the OTel attribute key for bos.compliance.rule_id.
	// Identifier of the specific compliance rule being checked.
	BOS_COMPLIANCE_RULE_IDKey = attribute.Key("bos.compliance.rule_id")
	// BOS_COMPLIANCE_SEVERITYKey is the OTel attribute key for bos.compliance.severity.
	// Severity level of a compliance rule violation.
	BOS_COMPLIANCE_SEVERITYKey = attribute.Key("bos.compliance.severity")
	// BOS_DECISION_IDKey is the OTel attribute key for bos.decision.id.
	// Unique identifier for a recorded decision in BusinessOS.
	BOS_DECISION_IDKey = attribute.Key("bos.decision.id")
	// BOS_DECISION_TYPEKey is the OTel attribute key for bos.decision.type.
	// Classification of the decision recorded.
	BOS_DECISION_TYPEKey = attribute.Key("bos.decision.type")
	// BOS_WORKSPACE_IDKey is the OTel attribute key for bos.workspace.id.
	// Unique identifier for a BusinessOS workspace.
	BOS_WORKSPACE_IDKey = attribute.Key("bos.workspace.id")
	// BOS_WORKSPACE_NAMEKey is the OTel attribute key for bos.workspace.name.
	// Human-readable name of the BusinessOS workspace.
	BOS_WORKSPACE_NAMEKey = attribute.Key("bos.workspace.name")
)

// BosAgentService returns an attribute KeyValue for bos.agent.service.
func BosAgentService(val string) attribute.KeyValue {
	return BOS_AGENT_SERVICEKey.String(val)
}

// BosComplianceFramework returns an attribute KeyValue for bos.compliance.framework.
func BosComplianceFramework(val string) attribute.KeyValue {
	return BOS_COMPLIANCE_FRAMEWORKKey.String(val)
}

// BosComplianceFrameworkValues contains the known values for bos.compliance.framework.
var BosComplianceFrameworkValues = struct {
	Soc2 string
	Hipaa string
	Gdpr string
	Sox string
}{
	Soc2: "SOC2",
	Hipaa: "HIPAA",
	Gdpr: "GDPR",
	Sox: "SOX",
}

// BosCompliancePassed returns an attribute KeyValue for bos.compliance.passed.
func BosCompliancePassed(val bool) attribute.KeyValue {
	return BOS_COMPLIANCE_PASSEDKey.Bool(val)
}

// BosComplianceRuleId returns an attribute KeyValue for bos.compliance.rule_id.
func BosComplianceRuleId(val string) attribute.KeyValue {
	return BOS_COMPLIANCE_RULE_IDKey.String(val)
}

// BosComplianceSeverity returns an attribute KeyValue for bos.compliance.severity.
func BosComplianceSeverity(val string) attribute.KeyValue {
	return BOS_COMPLIANCE_SEVERITYKey.String(val)
}

// BosComplianceSeverityValues contains the known values for bos.compliance.severity.
var BosComplianceSeverityValues = struct {
	Critical string
	High string
	Medium string
	Low string
}{
	Critical: "critical",
	High: "high",
	Medium: "medium",
	Low: "low",
}

// BosDecisionId returns an attribute KeyValue for bos.decision.id.
func BosDecisionId(val string) attribute.KeyValue {
	return BOS_DECISION_IDKey.String(val)
}

// BosDecisionType returns an attribute KeyValue for bos.decision.type.
func BosDecisionType(val string) attribute.KeyValue {
	return BOS_DECISION_TYPEKey.String(val)
}

// BosDecisionTypeValues contains the known values for bos.decision.type.
var BosDecisionTypeValues = struct {
	Architectural string
	Operational string
	Strategic string
	Compliance string
}{
	Architectural: "architectural",
	Operational: "operational",
	Strategic: "strategic",
	Compliance: "compliance",
}

// BosWorkspaceId returns an attribute KeyValue for bos.workspace.id.
func BosWorkspaceId(val string) attribute.KeyValue {
	return BOS_WORKSPACE_IDKey.String(val)
}

// BosWorkspaceName returns an attribute KeyValue for bos.workspace.name.
func BosWorkspaceName(val string) attribute.KeyValue {
	return BOS_WORKSPACE_NAMEKey.String(val)
}

