// Code generated by weaver. DO NOT EDIT.
// source: semconv/model

package semconv

import "go.opentelemetry.io/otel/attribute"

// Canopy Attributes
const (
	// CANOPY_ADAPTER_ACTIONKey is the OTel attribute key for canopy.adapter.action.
	// Action performed by the Canopy adapter.
	CANOPY_ADAPTER_ACTIONKey = attribute.Key("canopy.adapter.action")
	// CANOPY_ADAPTER_NAMEKey is the OTel attribute key for canopy.adapter.name.
	// Name of the Canopy adapter being invoked.
	CANOPY_ADAPTER_NAMEKey = attribute.Key("canopy.adapter.name")
	// CANOPY_BUDGET_MSKey is the OTel attribute key for canopy.budget.ms.
	// Time budget allocated for the Canopy operation in milliseconds.
	CANOPY_BUDGET_MSKey = attribute.Key("canopy.budget.ms")
	// CANOPY_HEARTBEAT_TIERKey is the OTel attribute key for canopy.heartbeat.tier.
	// Priority tier of the heartbeat dispatch.
	CANOPY_HEARTBEAT_TIERKey = attribute.Key("canopy.heartbeat.tier")
)

// CanopyAdapterAction returns an attribute KeyValue for canopy.adapter.action.
func CanopyAdapterAction(val string) attribute.KeyValue {
	return CANOPY_ADAPTER_ACTIONKey.String(val)
}

// CanopyAdapterName returns an attribute KeyValue for canopy.adapter.name.
func CanopyAdapterName(val string) attribute.KeyValue {
	return CANOPY_ADAPTER_NAMEKey.String(val)
}

// CanopyBudgetMs returns an attribute KeyValue for canopy.budget.ms.
func CanopyBudgetMs(val int64) attribute.KeyValue {
	return CANOPY_BUDGET_MSKey.Int64(val)
}

// CanopyHeartbeatTier returns an attribute KeyValue for canopy.heartbeat.tier.
func CanopyHeartbeatTier(val string) attribute.KeyValue {
	return CANOPY_HEARTBEAT_TIERKey.String(val)
}

// CanopyHeartbeatTierValues contains the known values for canopy.heartbeat.tier.
var CanopyHeartbeatTierValues = struct {
	Critical string
	High string
	Normal string
	Low string
}{
	Critical: "critical",
	High: "high",
	Normal: "normal",
	Low: "low",
}

