// Code generated by weaver. DO NOT EDIT.
// source: semconv/model

package semconv

import "go.opentelemetry.io/otel/attribute"

// Chatmangpt Attributes
const (
	// CHATMANGPT_AGENT_IDKey is the OTel attribute key for chatmangpt.agent.id.
	// Unique identifier of the agent processing the operation.
	CHATMANGPT_AGENT_IDKey = attribute.Key("chatmangpt.agent.id")
	// CHATMANGPT_BUDGET_EXCEEDEDKey is the OTel attribute key for chatmangpt.budget.exceeded.
	// Whether the operation exceeded its time budget.
	CHATMANGPT_BUDGET_EXCEEDEDKey = attribute.Key("chatmangpt.budget.exceeded")
	// CHATMANGPT_BUDGET_TIME_MSKey is the OTel attribute key for chatmangpt.budget.time_ms.
	// Time budget allocated for the operation in milliseconds.
	CHATMANGPT_BUDGET_TIME_MSKey = attribute.Key("chatmangpt.budget.time_ms")
	// CHATMANGPT_SERVICE_TIERKey is the OTel attribute key for chatmangpt.service.tier.
	// Priority tier of the operation, used for budget enforcement.
	CHATMANGPT_SERVICE_TIERKey = attribute.Key("chatmangpt.service.tier")
)

// ChatmangptAgentId returns an attribute KeyValue for chatmangpt.agent.id.
func ChatmangptAgentId(val string) attribute.KeyValue {
	return CHATMANGPT_AGENT_IDKey.String(val)
}

// ChatmangptBudgetExceeded returns an attribute KeyValue for chatmangpt.budget.exceeded.
func ChatmangptBudgetExceeded(val bool) attribute.KeyValue {
	return CHATMANGPT_BUDGET_EXCEEDEDKey.Bool(val)
}

// ChatmangptBudgetTimeMs returns an attribute KeyValue for chatmangpt.budget.time_ms.
func ChatmangptBudgetTimeMs(val int64) attribute.KeyValue {
	return CHATMANGPT_BUDGET_TIME_MSKey.Int64(val)
}

// ChatmangptServiceTier returns an attribute KeyValue for chatmangpt.service.tier.
func ChatmangptServiceTier(val string) attribute.KeyValue {
	return CHATMANGPT_SERVICE_TIERKey.String(val)
}

// ChatmangptServiceTierValues contains the known values for chatmangpt.service.tier.
var ChatmangptServiceTierValues = struct {
	Critical string
	High string
	Normal string
	Low string
}{
	Critical: "critical",
	High: "high",
	Normal: "normal",
	Low: "low",
}

