// Code generated by weaver. DO NOT EDIT.
// source: semconv/model

package semconv

import "go.opentelemetry.io/otel/attribute"

// Conformance Attributes
const (
	// CONFORMANCE_FITNESSKey is the OTel attribute key for conformance.fitness.
	// Conformance fitness score [0.0, 1.0] measuring how well the trace fits the model.
	CONFORMANCE_FITNESSKey = attribute.Key("conformance.fitness")
	// CONFORMANCE_PRECISIONKey is the OTel attribute key for conformance.precision.
	// Conformance precision score [0.0, 1.0] measuring model over-fitting.
	CONFORMANCE_PRECISIONKey = attribute.Key("conformance.precision")
)

// ConformanceFitness returns an attribute KeyValue for conformance.fitness.
func ConformanceFitness(val float64) attribute.KeyValue {
	return CONFORMANCE_FITNESSKey.Float64(val)
}

// ConformancePrecision returns an attribute KeyValue for conformance.precision.
func ConformancePrecision(val float64) attribute.KeyValue {
	return CONFORMANCE_PRECISIONKey.Float64(val)
}

