// Code generated by weaver. DO NOT EDIT.
// source: semconv/model

package semconv

import "go.opentelemetry.io/otel/attribute"

// Consensus Attributes
const (
	// CONSENSUS_LATENCY_MSKey is the OTel attribute key for consensus.latency_ms.
	// Latency of the consensus round in milliseconds.
	CONSENSUS_LATENCY_MSKey = attribute.Key("consensus.latency_ms")
	// CONSENSUS_NODE_IDKey is the OTel attribute key for consensus.node_id.
	// Identifier of the consensus node.
	CONSENSUS_NODE_IDKey = attribute.Key("consensus.node_id")
	// CONSENSUS_QUORUM_SIZEKey is the OTel attribute key for consensus.quorum_size.
	// Required quorum size for the consensus round.
	CONSENSUS_QUORUM_SIZEKey = attribute.Key("consensus.quorum_size")
	// CONSENSUS_ROUND_NUMKey is the OTel attribute key for consensus.round_num.
	// The round number within the BFT consensus protocol.
	CONSENSUS_ROUND_NUMKey = attribute.Key("consensus.round_num")
	// CONSENSUS_ROUND_TYPEKey is the OTel attribute key for consensus.round_type.
	// Phase of the BFT consensus round.
	CONSENSUS_ROUND_TYPEKey = attribute.Key("consensus.round_type")
)

// ConsensusLatencyMs returns an attribute KeyValue for consensus.latency_ms.
func ConsensusLatencyMs(val int64) attribute.KeyValue {
	return CONSENSUS_LATENCY_MSKey.Int64(val)
}

// ConsensusNodeId returns an attribute KeyValue for consensus.node_id.
func ConsensusNodeId(val string) attribute.KeyValue {
	return CONSENSUS_NODE_IDKey.String(val)
}

// ConsensusQuorumSize returns an attribute KeyValue for consensus.quorum_size.
func ConsensusQuorumSize(val int64) attribute.KeyValue {
	return CONSENSUS_QUORUM_SIZEKey.Int64(val)
}

// ConsensusRoundNum returns an attribute KeyValue for consensus.round_num.
func ConsensusRoundNum(val int64) attribute.KeyValue {
	return CONSENSUS_ROUND_NUMKey.Int64(val)
}

// ConsensusRoundType returns an attribute KeyValue for consensus.round_type.
func ConsensusRoundType(val string) attribute.KeyValue {
	return CONSENSUS_ROUND_TYPEKey.String(val)
}

// ConsensusRoundTypeValues contains the known values for consensus.round_type.
var ConsensusRoundTypeValues = struct {
	Prepare string
	Promise string
	Accept string
	Learn string
}{
	Prepare: "prepare",
	Promise: "promise",
	Accept: "accept",
	Learn: "learn",
}

