// Code generated by weaver. DO NOT EDIT.
// source: semconv/model

package semconv

import "go.opentelemetry.io/otel/attribute"

// Error Attributes
const (
	// ERROR_TYPEKey is the OTel attribute key for error.type.
	// Describes a class of error the operation ended with.
	ERROR_TYPEKey = attribute.Key("error.type")
)

// ErrorType returns an attribute KeyValue for error.type.
func ErrorType(val string) attribute.KeyValue {
	return ERROR_TYPEKey.String(val)
}

// ErrorTypeValues contains the known values for error.type.
var ErrorTypeValues = struct {
	Timeout string
	Cancelled string
	Internal string
	Unavailable string
}{
	Timeout: "timeout",
	Cancelled: "cancelled",
	Internal: "internal",
	Unavailable: "unavailable",
}

