// Code generated by weaver. DO NOT EDIT.
// source: semconv/model

package semconv

import "go.opentelemetry.io/otel/attribute"

// Healing Attributes
const (
	// HEALING_AGENT_IDKey is the OTel attribute key for healing.agent_id.
	// Identifier of the OSA agent that owns the healing operation.
	HEALING_AGENT_IDKey = attribute.Key("healing.agent_id")
	// HEALING_CONFIDENCEKey is the OTel attribute key for healing.confidence.
	// Confidence score for the failure mode classification, in range [0.0, 1.0].
	HEALING_CONFIDENCEKey = attribute.Key("healing.confidence")
	// HEALING_FAILURE_MODEKey is the OTel attribute key for healing.failure_mode.
	// The classified failure mode detected by the healing diagnosis engine.
	HEALING_FAILURE_MODEKey = attribute.Key("healing.failure_mode")
	// HEALING_MTTR_MSKey is the OTel attribute key for healing.mttr_ms.
	// Mean time to recovery in milliseconds for the healing operation.
	HEALING_MTTR_MSKey = attribute.Key("healing.mttr_ms")
	// HEALING_RECOVERY_ACTIONKey is the OTel attribute key for healing.recovery_action.
	// The recovery action taken by the reflex arc.
	HEALING_RECOVERY_ACTIONKey = attribute.Key("healing.recovery_action")
	// HEALING_REFLEX_ARCKey is the OTel attribute key for healing.reflex_arc.
	// The named reflex arc triggered during healing.
	HEALING_REFLEX_ARCKey = attribute.Key("healing.reflex_arc")
)

// HealingAgentId returns an attribute KeyValue for healing.agent_id.
func HealingAgentId(val string) attribute.KeyValue {
	return HEALING_AGENT_IDKey.String(val)
}

// HealingConfidence returns an attribute KeyValue for healing.confidence.
func HealingConfidence(val float64) attribute.KeyValue {
	return HEALING_CONFIDENCEKey.Float64(val)
}

// HealingFailureMode returns an attribute KeyValue for healing.failure_mode.
func HealingFailureMode(val string) attribute.KeyValue {
	return HEALING_FAILURE_MODEKey.String(val)
}

// HealingFailureModeValues contains the known values for healing.failure_mode.
var HealingFailureModeValues = struct {
	Deadlock string
	Timeout string
	RaceCondition string
	MemoryLeak string
	CascadingFailure string
	Stagnation string
	Livelock string
}{
	Deadlock: "deadlock",
	Timeout: "timeout",
	RaceCondition: "race_condition",
	MemoryLeak: "memory_leak",
	CascadingFailure: "cascading_failure",
	Stagnation: "stagnation",
	Livelock: "livelock",
}

// HealingMttrMs returns an attribute KeyValue for healing.mttr_ms.
func HealingMttrMs(val int64) attribute.KeyValue {
	return HEALING_MTTR_MSKey.Int64(val)
}

// HealingRecoveryAction returns an attribute KeyValue for healing.recovery_action.
func HealingRecoveryAction(val string) attribute.KeyValue {
	return HEALING_RECOVERY_ACTIONKey.String(val)
}

// HealingReflexArc returns an attribute KeyValue for healing.reflex_arc.
func HealingReflexArc(val string) attribute.KeyValue {
	return HEALING_REFLEX_ARCKey.String(val)
}

