// Code generated by weaver. DO NOT EDIT.
// source: semconv/model

package semconv

import "go.opentelemetry.io/otel/attribute"

// Mcp Attributes
const (
	// MCP_PROTOCOLKey is the OTel attribute key for mcp.protocol.
	// Transport protocol used for MCP communication.
	MCP_PROTOCOLKey = attribute.Key("mcp.protocol")
	// MCP_SERVER_NAMEKey is the OTel attribute key for mcp.server.name.
	// Name of the MCP server hosting the tool.
	MCP_SERVER_NAMEKey = attribute.Key("mcp.server.name")
	// MCP_TOOL_NAMEKey is the OTel attribute key for mcp.tool.name.
	// Name of the MCP tool being invoked.
	MCP_TOOL_NAMEKey = attribute.Key("mcp.tool.name")
	// MCP_TOOL_RESULT_COUNTKey is the OTel attribute key for mcp.tool.result_count.
	// Number of results returned by the MCP tool.
	MCP_TOOL_RESULT_COUNTKey = attribute.Key("mcp.tool.result_count")
)

// McpProtocol returns an attribute KeyValue for mcp.protocol.
func McpProtocol(val string) attribute.KeyValue {
	return MCP_PROTOCOLKey.String(val)
}

// McpProtocolValues contains the known values for mcp.protocol.
var McpProtocolValues = struct {
	Stdio string
	Http string
	Sse string
}{
	Stdio: "stdio",
	Http: "http",
	Sse: "sse",
}

// McpServerName returns an attribute KeyValue for mcp.server.name.
func McpServerName(val string) attribute.KeyValue {
	return MCP_SERVER_NAMEKey.String(val)
}

// McpToolName returns an attribute KeyValue for mcp.tool.name.
func McpToolName(val string) attribute.KeyValue {
	return MCP_TOOL_NAMEKey.String(val)
}

// McpToolResultCount returns an attribute KeyValue for mcp.tool.result_count.
func McpToolResultCount(val int64) attribute.KeyValue {
	return MCP_TOOL_RESULT_COUNTKey.Int64(val)
}

