// Code generated by weaver. DO NOT EDIT.
// source: semconv/model/mcp/registry.yaml

package semconv

import "go.opentelemetry.io/otel/attribute"

// Mcp Attributes
const (
	// McpProtocolKey is the OTel attribute key for mcp.protocol.
	// Transport protocol used for MCP communication.
	McpProtocolKey = attribute.Key("mcp.protocol")
	// McpServerNameKey is the OTel attribute key for mcp.server.name.
	// Name of the MCP server hosting the tool.
	McpServerNameKey = attribute.Key("mcp.server.name")
	// McpToolNameKey is the OTel attribute key for mcp.tool.name.
	// Name of the MCP tool being invoked.
	McpToolNameKey = attribute.Key("mcp.tool.name")
	// McpToolResultCountKey is the OTel attribute key for mcp.tool.result_count.
	// Number of results returned by the MCP tool.
	McpToolResultCountKey = attribute.Key("mcp.tool.result_count")
)

// McpProtocol returns an attribute KeyValue for mcp.protocol.
func McpProtocol(val string) attribute.KeyValue {
	return McpProtocolKey.String(val)
}

// McpProtocolValues contains the known enum values for mcp.protocol.
var McpProtocolValues = struct {
	Stdio string
	Http string
	Sse string
}{
	Stdio: "stdio",
	Http: "http",
	Sse: "sse",
}

// McpServerName returns an attribute KeyValue for mcp.server.name.
func McpServerName(val string) attribute.KeyValue {
	return McpServerNameKey.String(val)
}

// McpToolName returns an attribute KeyValue for mcp.tool.name.
func McpToolName(val string) attribute.KeyValue {
	return McpToolNameKey.String(val)
}

// McpToolResultCount returns an attribute KeyValue for mcp.tool.result_count.
func McpToolResultCount(val int64) attribute.KeyValue {
	return McpToolResultCountKey.Int64(val)
}

// Wave 9 Iteration 8: MCP Tool Schema attributes

const (
	// McpToolInputSizeKey is the OTel attribute key for mcp.tool.input_size.
	// Size of the MCP tool input payload in bytes.
	McpToolInputSizeKey = attribute.Key("mcp.tool.input_size")
	// McpToolOutputSizeKey is the OTel attribute key for mcp.tool.output_size.
	// Size of the MCP tool output payload in bytes.
	McpToolOutputSizeKey = attribute.Key("mcp.tool.output_size")
	// McpToolRetryCountKey is the OTel attribute key for mcp.tool.retry_count.
	// Number of retries attempted for this MCP tool invocation.
	McpToolRetryCountKey = attribute.Key("mcp.tool.retry_count")
	// McpToolTimeoutMsKey is the OTel attribute key for mcp.tool.timeout_ms.
	// Timeout in milliseconds for the MCP tool invocation.
	McpToolTimeoutMsKey = attribute.Key("mcp.tool.timeout_ms")
)

// McpToolInputSize returns an attribute KeyValue for mcp.tool.input_size.
func McpToolInputSize(val int) attribute.KeyValue {
	return McpToolInputSizeKey.Int(val)
}

// McpToolOutputSize returns an attribute KeyValue for mcp.tool.output_size.
func McpToolOutputSize(val int) attribute.KeyValue {
	return McpToolOutputSizeKey.Int(val)
}

// McpToolRetryCount returns an attribute KeyValue for mcp.tool.retry_count.
func McpToolRetryCount(val int) attribute.KeyValue {
	return McpToolRetryCountKey.Int(val)
}

// McpToolTimeoutMs returns an attribute KeyValue for mcp.tool.timeout_ms.
func McpToolTimeoutMs(val int) attribute.KeyValue {
	return McpToolTimeoutMsKey.Int(val)
}

