// Code generated by weaver. DO NOT EDIT.
// source: semconv/model

package semconv

import "go.opentelemetry.io/otel/attribute"

// Process Attributes
const (
	// PROCESS_MINING_ACTIVITYKey is the OTel attribute key for process.mining.activity.
	// Name of the process activity (event class) from the XES log.
	PROCESS_MINING_ACTIVITYKey = attribute.Key("process.mining.activity")
	// PROCESS_MINING_ALGORITHMKey is the OTel attribute key for process.mining.algorithm.
	// Process discovery algorithm used.
	PROCESS_MINING_ALGORITHMKey = attribute.Key("process.mining.algorithm")
	// PROCESS_MINING_EVENT_COUNTKey is the OTel attribute key for process.mining.event_count.
	// Number of events in the process trace.
	PROCESS_MINING_EVENT_COUNTKey = attribute.Key("process.mining.event_count")
	// PROCESS_MINING_LOG_PATHKey is the OTel attribute key for process.mining.log_path.
	// File path or identifier of the XES event log being mined.
	PROCESS_MINING_LOG_PATHKey = attribute.Key("process.mining.log_path")
	// PROCESS_MINING_TRACE_IDKey is the OTel attribute key for process.mining.trace_id.
	// Identifier of the process trace from the XES event log.
	PROCESS_MINING_TRACE_IDKey = attribute.Key("process.mining.trace_id")
)

// ProcessMiningActivity returns an attribute KeyValue for process.mining.activity.
func ProcessMiningActivity(val string) attribute.KeyValue {
	return PROCESS_MINING_ACTIVITYKey.String(val)
}

// ProcessMiningAlgorithm returns an attribute KeyValue for process.mining.algorithm.
func ProcessMiningAlgorithm(val string) attribute.KeyValue {
	return PROCESS_MINING_ALGORITHMKey.String(val)
}

// ProcessMiningAlgorithmValues contains the known values for process.mining.algorithm.
var ProcessMiningAlgorithmValues = struct {
	AlphaMiner string
	InductiveMiner string
	HeuristicsMiner string
}{
	AlphaMiner: "alpha_miner",
	InductiveMiner: "inductive_miner",
	HeuristicsMiner: "heuristics_miner",
}

// ProcessMiningEventCount returns an attribute KeyValue for process.mining.event_count.
func ProcessMiningEventCount(val int64) attribute.KeyValue {
	return PROCESS_MINING_EVENT_COUNTKey.Int64(val)
}

// ProcessMiningLogPath returns an attribute KeyValue for process.mining.log_path.
func ProcessMiningLogPath(val string) attribute.KeyValue {
	return PROCESS_MINING_LOG_PATHKey.String(val)
}

// ProcessMiningTraceId returns an attribute KeyValue for process.mining.trace_id.
func ProcessMiningTraceId(val string) attribute.KeyValue {
	return PROCESS_MINING_TRACE_IDKey.String(val)
}

