// Code generated by weaver. DO NOT EDIT.
// source: semconv/model

package semconv

import "go.opentelemetry.io/otel/attribute"

// Signal Attributes
const (
	// SIGNAL_CLASSIFIERKey is the OTel attribute key for signal.classifier.
	// The classifier module or model that analyzed and scored the signal.
	SIGNAL_CLASSIFIERKey = attribute.Key("signal.classifier")
	// SIGNAL_FORMATKey is the OTel attribute key for signal.format.
	// The format component (F) of the signal — the container or serialization format.
	SIGNAL_FORMATKey = attribute.Key("signal.format")
	// SIGNAL_GENREKey is the OTel attribute key for signal.genre.
	// The genre component (G) of the signal — the document or interaction type.
	SIGNAL_GENREKey = attribute.Key("signal.genre")
	// SIGNAL_MODEKey is the OTel attribute key for signal.mode.
	// The mode component (M) of the signal — how information is encoded.
	SIGNAL_MODEKey = attribute.Key("signal.mode")
	// SIGNAL_NOISE_LEVELKey is the OTel attribute key for signal.noise_level.
	// Noise level of the signal in range [0.0, 1.0]. Complement of signal weight for clean signals.
	SIGNAL_NOISE_LEVELKey = attribute.Key("signal.noise_level")
	// SIGNAL_SOURCEKey is the OTel attribute key for signal.source.
	// The source channel through which the signal was received.
	SIGNAL_SOURCEKey = attribute.Key("signal.source")
	// SIGNAL_TYPEKey is the OTel attribute key for signal.type.
	// The type component (T) of the signal — the speech act or communicative intent.
	SIGNAL_TYPEKey = attribute.Key("signal.type")
	// SIGNAL_WEIGHTKey is the OTel attribute key for signal.weight.
	// Signal weight (W) — signal-to-noise ratio in range [0.0, 1.0]. Values >= 0.7 pass the S/N gate.
	SIGNAL_WEIGHTKey = attribute.Key("signal.weight")
)

// SignalClassifier returns an attribute KeyValue for signal.classifier.
func SignalClassifier(val string) attribute.KeyValue {
	return SIGNAL_CLASSIFIERKey.String(val)
}

// SignalFormat returns an attribute KeyValue for signal.format.
func SignalFormat(val string) attribute.KeyValue {
	return SIGNAL_FORMATKey.String(val)
}

// SignalFormatValues contains the known values for signal.format.
var SignalFormatValues = struct {
	Markdown string
	Code string
	Json string
	Yaml string
	Html string
	Text string
}{
	Markdown: "markdown",
	Code: "code",
	Json: "json",
	Yaml: "yaml",
	Html: "html",
	Text: "text",
}

// SignalGenre returns an attribute KeyValue for signal.genre.
func SignalGenre(val string) attribute.KeyValue {
	return SIGNAL_GENREKey.String(val)
}

// SignalGenreValues contains the known values for signal.genre.
var SignalGenreValues = struct {
	Spec string
	Brief string
	Report string
	Plan string
	Adr string
	Email string
	CodeReview string
}{
	Spec: "spec",
	Brief: "brief",
	Report: "report",
	Plan: "plan",
	Adr: "adr",
	Email: "email",
	CodeReview: "code_review",
}

// SignalMode returns an attribute KeyValue for signal.mode.
func SignalMode(val string) attribute.KeyValue {
	return SIGNAL_MODEKey.String(val)
}

// SignalModeValues contains the known values for signal.mode.
var SignalModeValues = struct {
	Linguistic string
	Visual string
	Code string
	Data string
	Mixed string
}{
	Linguistic: "linguistic",
	Visual: "visual",
	Code: "code",
	Data: "data",
	Mixed: "mixed",
}

// SignalNoiseLevel returns an attribute KeyValue for signal.noise_level.
func SignalNoiseLevel(val float64) attribute.KeyValue {
	return SIGNAL_NOISE_LEVELKey.Float64(val)
}

// SignalSource returns an attribute KeyValue for signal.source.
func SignalSource(val string) attribute.KeyValue {
	return SIGNAL_SOURCEKey.String(val)
}

// SignalType returns an attribute KeyValue for signal.type.
func SignalType(val string) attribute.KeyValue {
	return SIGNAL_TYPEKey.String(val)
}

// SignalTypeValues contains the known values for signal.type.
var SignalTypeValues = struct {
	Direct string
	Inform string
	Commit string
	Decide string
	Express string
}{
	Direct: "direct",
	Inform: "inform",
	Commit: "commit",
	Decide: "decide",
	Express: "express",
}

// SignalWeight returns an attribute KeyValue for signal.weight.
func SignalWeight(val float64) attribute.KeyValue {
	return SIGNAL_WEIGHTKey.Float64(val)
}

