// Code generated by weaver. DO NOT EDIT.
// source: semconv/model

package semconv

import "go.opentelemetry.io/otel/attribute"

// Workflow Attributes
const (
	// WORKFLOW_ENGINEKey is the OTel attribute key for workflow.engine.
	// Workflow engine executing the workflow.
	WORKFLOW_ENGINEKey = attribute.Key("workflow.engine")
	// WORKFLOW_IDKey is the OTel attribute key for workflow.id.
	// Unique identifier for the workflow instance.
	WORKFLOW_IDKey = attribute.Key("workflow.id")
	// WORKFLOW_NAMEKey is the OTel attribute key for workflow.name.
	// Human-readable name of the workflow definition.
	WORKFLOW_NAMEKey = attribute.Key("workflow.name")
	// WORKFLOW_PATTERNKey is the OTel attribute key for workflow.pattern.
	// YAWL workflow control-flow pattern applied in this step.
	WORKFLOW_PATTERNKey = attribute.Key("workflow.pattern")
	// WORKFLOW_STATEKey is the OTel attribute key for workflow.state.
	// Execution state of the workflow instance.
	WORKFLOW_STATEKey = attribute.Key("workflow.state")
	// WORKFLOW_STEPKey is the OTel attribute key for workflow.step.
	// The current step or activity name within the workflow.
	WORKFLOW_STEPKey = attribute.Key("workflow.step")
	// WORKFLOW_STEP_COUNTKey is the OTel attribute key for workflow.step_count.
	// Total number of steps completed so far in the workflow.
	WORKFLOW_STEP_COUNTKey = attribute.Key("workflow.step_count")
)

// WorkflowEngine returns an attribute KeyValue for workflow.engine.
func WorkflowEngine(val string) attribute.KeyValue {
	return WORKFLOW_ENGINEKey.String(val)
}

// WorkflowEngineValues contains the known values for workflow.engine.
var WorkflowEngineValues = struct {
	Canopy string
	Yawl string
	BusinessOs string
}{
	Canopy: "canopy",
	Yawl: "yawl",
	BusinessOs: "business_os",
}

// WorkflowId returns an attribute KeyValue for workflow.id.
func WorkflowId(val string) attribute.KeyValue {
	return WORKFLOW_IDKey.String(val)
}

// WorkflowName returns an attribute KeyValue for workflow.name.
func WorkflowName(val string) attribute.KeyValue {
	return WORKFLOW_NAMEKey.String(val)
}

// WorkflowPattern returns an attribute KeyValue for workflow.pattern.
func WorkflowPattern(val string) attribute.KeyValue {
	return WORKFLOW_PATTERNKey.String(val)
}

// WorkflowPatternValues contains the known values for workflow.pattern.
var WorkflowPatternValues = struct {
	Sequence string
	ParallelSplit string
	Synchronization string
	ExclusiveChoice string
	MultiChoice string
	StructuredLoop string
	DeferredChoice string
	Milestone string
}{
	Sequence: "sequence",
	ParallelSplit: "parallel_split",
	Synchronization: "synchronization",
	ExclusiveChoice: "exclusive_choice",
	MultiChoice: "multi_choice",
	StructuredLoop: "structured_loop",
	DeferredChoice: "deferred_choice",
	Milestone: "milestone",
}

// WorkflowState returns an attribute KeyValue for workflow.state.
func WorkflowState(val string) attribute.KeyValue {
	return WORKFLOW_STATEKey.String(val)
}

// WorkflowStateValues contains the known values for workflow.state.
var WorkflowStateValues = struct {
	Pending string
	Active string
	Completed string
	Failed string
	Cancelled string
	Suspended string
}{
	Pending: "pending",
	Active: "active",
	Completed: "completed",
	Failed: "failed",
	Cancelled: "cancelled",
	Suspended: "suspended",
}

// WorkflowStep returns an attribute KeyValue for workflow.step.
func WorkflowStep(val string) attribute.KeyValue {
	return WORKFLOW_STEPKey.String(val)
}

// WorkflowStepCount returns an attribute KeyValue for workflow.step_count.
func WorkflowStepCount(val int64) attribute.KeyValue {
	return WORKFLOW_STEP_COUNTKey.Int64(val)
}

