-- 134_seed_core_app_catalog.sql
-- Real default catalog entries for commonly used web apps.

INSERT INTO app_catalog (
    slug, name, provider, app_type, url, launch_mode, icon, logo_url, color,
    category, notes, url_class, status, is_featured, position_index
) VALUES
    ('chatgpt', 'ChatGPT', 'openai', 'web_app', 'https://chatgpt.com', 'iframe', 'message-square', '/app-logos/chatgpt.svg', '#111827', 'ai', 'OpenAI ChatGPT web app.', 'custom_domain', 'active', TRUE, 10),
    ('claude', 'Claude', 'anthropic', 'web_app', 'https://claude.ai', 'iframe', 'message-square', '/app-logos/claude.svg', '#111827', 'ai', 'Anthropic Claude web app.', 'custom_domain', 'active', TRUE, 20),
    ('perplexity', 'Perplexity', 'perplexity', 'web_app', 'https://www.perplexity.ai', 'iframe', 'search', '/app-logos/perplexity.svg', '#111827', 'ai', 'AI answer engine and research app.', 'custom_domain', 'active', TRUE, 30),
    ('google', 'Google', 'google', 'web_app', 'https://www.google.com', 'iframe', 'search', '/app-logos/google.svg', '#4285F4', 'search', 'Google Search.', 'custom_domain', 'active', TRUE, 40),
    ('openai-platform', 'OpenAI Platform', 'openai', 'web_app', 'https://platform.openai.com', 'iframe', 'terminal', '/app-logos/openai.svg', '#111827', 'ai', 'OpenAI developer platform.', 'custom_domain', 'active', TRUE, 50),
    ('higgsfield', 'Higgsfield', 'higgsfield', 'web_app', 'https://higgsfield.ai', 'iframe', 'sparkles', '/app-logos/higgsfield.ico', '#111827', 'creative', 'AI-native creative suite for image, video, and voice workflows.', 'custom_domain', 'active', TRUE, 60),
    ('slack', 'Slack', 'slack', 'web_app', 'https://app.slack.com', 'iframe', 'messages-square', '/app-logos/slack.ico', '#4A154B', 'communication', 'Team messaging and channels.', 'custom_domain', 'active', TRUE, 70),
    ('discord', 'Discord', 'discord', 'web_app', 'https://discord.com/app', 'iframe', 'messages-square', '/app-logos/discord.svg', '#5865F2', 'communication', 'Community and team voice/chat workspace.', 'custom_domain', 'active', TRUE, 80),
    ('notion', 'Notion', 'notion', 'web_app', 'https://www.notion.so', 'iframe', 'file-text', '/app-logos/notion.svg', '#111827', 'docs', 'Docs, wiki, and databases.', 'custom_domain', 'active', TRUE, 90),
    ('clickup', 'ClickUp', 'clickup', 'web_app', 'https://app.clickup.com', 'iframe', 'check-square', '/app-logos/clickup.svg', '#7B68EE', 'project-management', 'Tasks, docs, goals, and operations.', 'custom_domain', 'active', TRUE, 100),
    ('gohighlevel', 'GoHighLevel', 'gohighlevel', 'web_app', 'https://app.gohighlevel.com', 'iframe', 'workflow', '/app-logos/gohighlevel.ico', '#111827', 'crm', 'CRM, marketing automation, and agency client ops.', 'custom_domain', 'active', TRUE, 110),
    ('hubspot', 'HubSpot', 'hubspot', 'web_app', 'https://app.hubspot.com', 'iframe', 'users', '/app-logos/hubspot.ico', '#FF7A59', 'crm', 'CRM, sales, marketing, and support platform.', 'custom_domain', 'active', TRUE, 120),
    ('gmail', 'Gmail', 'google', 'web_app', 'https://mail.google.com', 'iframe', 'mail', '/app-logos/gmail.ico', '#EA4335', 'communication', 'Google email inbox.', 'custom_domain', 'active', FALSE, 130),
    ('google-calendar', 'Google Calendar', 'google', 'web_app', 'https://calendar.google.com', 'iframe', 'calendar', '/app-logos/google-calendar.svg', '#4285F4', 'calendar', 'Google Calendar.', 'custom_domain', 'active', FALSE, 140),
    ('google-drive', 'Google Drive', 'google', 'web_app', 'https://drive.google.com', 'iframe', 'folder', '/app-logos/google-drive.ico', '#0F9D58', 'files', 'Google file storage and docs.', 'custom_domain', 'active', FALSE, 130),
    ('google-meet', 'Google Meet', 'google', 'web_app', 'https://meet.google.com', 'iframe', 'video', '/app-logos/google-meet.ico', '#00897B', 'meetings', 'Google video meetings.', 'custom_domain', 'active', FALSE, 140),
    ('zoom', 'Zoom', 'zoom', 'web_app', 'https://app.zoom.us/wc', 'iframe', 'video', '/app-logos/zoom.ico', '#0B5CFF', 'meetings', 'Zoom web client.', 'custom_domain', 'active', FALSE, 150),
    ('fathom', 'Fathom', 'fathom', 'web_app', 'https://fathom.video', 'iframe', 'mic', '/app-logos/fathom.ico', '#111827', 'meetings', 'Meeting recorder and summaries.', 'custom_domain', 'active', FALSE, 160),
    ('fireflies', 'Fireflies', 'fireflies', 'web_app', 'https://app.fireflies.ai', 'iframe', 'mic', '/app-logos/fireflies.ico', '#6D5DFB', 'meetings', 'Meeting notes and conversation intelligence.', 'custom_domain', 'active', FALSE, 170),
    ('figma', 'Figma', 'figma', 'web_app', 'https://www.figma.com/files', 'iframe', 'pen-tool', '/app-logos/figma.svg', '#111827', 'design', 'Collaborative design files.', 'custom_domain', 'active', FALSE, 180),
    ('airtable', 'Airtable', 'airtable', 'web_app', 'https://airtable.com', 'iframe', 'table', '/app-logos/airtable.webp', '#FCB400', 'database', 'No-code databases and operations tables.', 'custom_domain', 'active', FALSE, 190),
    ('trello', 'Trello', 'trello', 'web_app', 'https://trello.com', 'iframe', 'kanban', '/app-logos/trello.ico', '#0079BF', 'project-management', 'Kanban boards and task tracking.', 'custom_domain', 'active', FALSE, 200),
    ('asana', 'Asana', 'asana', 'web_app', 'https://app.asana.com', 'iframe', 'list-checks', '/app-logos/asana.ico', '#F06A6A', 'project-management', 'Team projects and task management.', 'custom_domain', 'active', FALSE, 210),
    ('linear', 'Linear', 'linear', 'web_app', 'https://linear.app', 'iframe', 'list-checks', '/app-logos/linear.ico', '#5E6AD2', 'project-management', 'Issues, product work, and engineering planning.', 'custom_domain', 'active', FALSE, 220),
    ('github', 'GitHub', 'github', 'web_app', 'https://github.com', 'iframe', 'github', '/app-logos/github.ico', '#111827', 'development', 'Code repositories and collaboration.', 'custom_domain', 'active', FALSE, 230),
    ('vercel', 'Vercel', 'vercel', 'web_app', 'https://vercel.com/dashboard', 'iframe', 'triangle', '/app-logos/vercel.ico', '#111827', 'deployment', 'Frontend deployments and hosting.', 'custom_domain', 'active', FALSE, 240),
    ('netlify', 'Netlify', 'netlify', 'web_app', 'https://app.netlify.com', 'iframe', 'cloud', '/app-logos/netlify.ico', '#00AD9F', 'deployment', 'Web deployments and hosting.', 'custom_domain', 'active', FALSE, 250),
    ('render', 'Render', 'render', 'web_app', 'https://dashboard.render.com', 'iframe', 'cloud', '/app-logos/render.svg', '#46E3B7', 'deployment', 'App hosting, workers, and databases.', 'custom_domain', 'active', FALSE, 260),
    ('replit', 'Replit', 'replit', 'web_app', 'https://replit.com', 'iframe', 'code-2', '/app-logos/replit.svg', '#F26207', 'development', 'Browser IDE and deployments.', 'custom_domain', 'active', FALSE, 270),
    ('supabase', 'Supabase', 'supabase', 'web_app', 'https://supabase.com/dashboard', 'iframe', 'database', '/app-logos/supabase.svg', '#3ECF8E', 'database', 'Postgres, auth, storage, and backend services.', 'custom_domain', 'active', FALSE, 280),
    ('stripe', 'Stripe', 'stripe', 'web_app', 'https://dashboard.stripe.com', 'iframe', 'credit-card', '/app-logos/stripe.ico', '#635BFF', 'payments', 'Payments, billing, and financial operations.', 'custom_domain', 'active', FALSE, 290),
    ('shopify', 'Shopify', 'shopify', 'web_app', 'https://admin.shopify.com', 'iframe', 'shopping-bag', '/app-logos/shopify.ico', '#95BF47', 'commerce', 'Commerce admin and store operations.', 'custom_domain', 'active', FALSE, 300),
    ('webflow', 'Webflow', 'webflow', 'web_app', 'https://webflow.com/dashboard', 'iframe', 'layout-template', '/app-logos/webflow.ico', '#146EF5', 'sites', 'Visual website builder and CMS.', 'custom_domain', 'active', FALSE, 310),
    ('canva', 'Canva', 'canva', 'web_app', 'https://www.canva.com', 'iframe', 'palette', '/app-logos/canva.ico', '#00C4CC', 'creative', 'Design and brand creative production.', 'custom_domain', 'active', FALSE, 320),
    ('capcut', 'CapCut', 'capcut', 'web_app', 'https://www.capcut.com', 'iframe', 'scissors', '/app-logos/capcut.ico', '#111827', 'creative', 'Video editing and creative production.', 'custom_domain', 'active', FALSE, 330),
    ('midjourney', 'Midjourney', 'midjourney', 'web_app', 'https://www.midjourney.com', 'iframe', 'image', '/app-logos/midjourney.png', '#111827', 'creative', 'AI image generation.', 'custom_domain', 'active', FALSE, 340),
    ('runway', 'Runway', 'runway', 'web_app', 'https://runwayml.com', 'iframe', 'film', '/app-logos/runway.png', '#111827', 'creative', 'AI video generation and editing.', 'custom_domain', 'active', FALSE, 350),
    ('elevenlabs', 'ElevenLabs', 'elevenlabs', 'web_app', 'https://elevenlabs.io/app', 'iframe', 'audio-lines', '/app-logos/elevenlabs.ico', '#111827', 'creative', 'AI voice and audio generation.', 'custom_domain', 'active', FALSE, 360),
    ('descript', 'Descript', 'descript', 'web_app', 'https://web.descript.com', 'iframe', 'file-audio', '/app-logos/descript.png', '#111827', 'creative', 'Audio/video editing and transcription.', 'custom_domain', 'active', FALSE, 370),
    ('zapier', 'Zapier', 'zapier', 'web_app', 'https://zapier.com/app/home', 'iframe', 'workflow', '/app-logos/zapier.ico', '#FF4A00', 'automation', 'Workflow automation between apps.', 'custom_domain', 'active', FALSE, 380),
    ('make', 'Make', 'make', 'web_app', 'https://www.make.com/en/hq/app', 'iframe', 'workflow', '/app-logos/make.ico', '#6D00CC', 'automation', 'Visual workflow automation.', 'custom_domain', 'active', FALSE, 390),
    ('n8n', 'n8n', 'n8n', 'web_app', 'https://app.n8n.cloud', 'iframe', 'workflow', '/app-logos/n8n.ico', '#EA4B71', 'automation', 'Workflow automation and integrations.', 'custom_domain', 'active', FALSE, 400),
    ('calendly', 'Calendly', 'calendly', 'web_app', 'https://calendly.com/app', 'iframe', 'calendar-check', '/app-logos/calendly.ico', '#006BFF', 'scheduling', 'Scheduling links and booking pages.', 'custom_domain', 'active', FALSE, 410),
    ('typeform', 'Typeform', 'typeform', 'web_app', 'https://admin.typeform.com', 'iframe', 'clipboard-list', '/app-logos/typeform.svg', '#111827', 'forms', 'Forms, surveys, and lead capture.', 'custom_domain', 'active', FALSE, 420),
    ('mailchimp', 'Mailchimp', 'mailchimp', 'web_app', 'https://mailchimp.com', 'iframe', 'mail', '/app-logos/mailchimp.ico', '#FFE01B', 'email', 'Email marketing and audience management.', 'custom_domain', 'active', FALSE, 430),
    ('beehiiv', 'beehiiv', 'beehiiv', 'web_app', 'https://app.beehiiv.com', 'iframe', 'newspaper', '/app-logos/beehiiv.png', '#FACC15', 'email', 'Newsletter publishing and growth.', 'custom_domain', 'active', FALSE, 440),
    ('meta-business', 'Meta Business Suite', 'meta', 'web_app', 'https://business.facebook.com', 'iframe', 'megaphone', '/app-logos/meta-business.ico', '#0866FF', 'ads', 'Meta ads and business management.', 'custom_domain', 'active', FALSE, 450),
    ('tiktok-ads', 'TikTok Ads Manager', 'tiktok', 'web_app', 'https://ads.tiktok.com', 'iframe', 'megaphone', '/app-logos/tiktok-ads.svg', '#111827', 'ads', 'TikTok advertising dashboard.', 'custom_domain', 'active', FALSE, 460)
ON CONFLICT (slug) DO UPDATE SET
    name = EXCLUDED.name,
    provider = EXCLUDED.provider,
    app_type = EXCLUDED.app_type,
    url = EXCLUDED.url,
    launch_mode = EXCLUDED.launch_mode,
    icon = EXCLUDED.icon,
    logo_url = EXCLUDED.logo_url,
    color = EXCLUDED.color,
    category = EXCLUDED.category,
    notes = EXCLUDED.notes,
    url_class = EXCLUDED.url_class,
    status = EXCLUDED.status,
    is_featured = EXCLUDED.is_featured,
    position_index = EXCLUDED.position_index,
    updated_at = NOW();
