-- 139_app_catalog_embedded_launch.sql
-- Curated web apps launch inside BusinessOS by default.
-- Explicit browser or external launch remains available per workspace app.

UPDATE app_catalog
SET launch_mode = 'iframe',
    updated_at = NOW()
WHERE slug IN (
    'chatgpt',
    'claude',
    'perplexity',
    'google',
    'openai-platform',
    'higgsfield',
    'slack',
    'discord',
    'notion',
    'clickup',
    'gohighlevel',
    'hubspot',
    'gmail',
    'google-calendar',
    'google-drive',
    'google-meet',
    'zoom',
    'fathom',
    'fireflies',
    'figma',
    'airtable',
    'trello',
    'asana',
    'linear',
    'github',
    'vercel',
    'netlify',
    'render',
    'replit',
    'supabase',
    'stripe',
    'shopify',
    'webflow',
    'canva',
    'capcut',
    'midjourney',
    'runway',
    'elevenlabs',
    'descript',
    'zapier',
    'make',
    'n8n',
    'calendly',
    'typeform',
    'mailchimp',
    'beehiiv',
    'meta-business',
    'tiktok-ads'
);
