// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: clients.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createClient = `-- name: CreateClient :one
INSERT INTO clients (user_id, name, type, email, phone, website, industry, company_size, address, city, state, zip_code, country, status, source, assigned_to, tags, custom_fields, notes)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19)
RETURNING id, user_id, name, type, email, phone, website, industry, company_size, address, city, state, zip_code, country, status, source, assigned_to, lifetime_value, tags, custom_fields, notes, created_at, updated_at, last_contacted_at
`

type CreateClientParams struct {
	UserID       string           `json:"user_id"`
	Name         string           `json:"name"`
	Type         NullClienttype   `json:"type"`
	Email        *string          `json:"email"`
	Phone        *string          `json:"phone"`
	Website      *string          `json:"website"`
	Industry     *string          `json:"industry"`
	CompanySize  *string          `json:"company_size"`
	Address      *string          `json:"address"`
	City         *string          `json:"city"`
	State        *string          `json:"state"`
	ZipCode      *string          `json:"zip_code"`
	Country      *string          `json:"country"`
	Status       NullClientstatus `json:"status"`
	Source       *string          `json:"source"`
	AssignedTo   *string          `json:"assigned_to"`
	Tags         []byte           `json:"tags"`
	CustomFields []byte           `json:"custom_fields"`
	Notes        *string          `json:"notes"`
}

func (q *Queries) CreateClient(ctx context.Context, arg CreateClientParams) (Client, error) {
	row := q.db.QueryRow(ctx, createClient,
		arg.UserID,
		arg.Name,
		arg.Type,
		arg.Email,
		arg.Phone,
		arg.Website,
		arg.Industry,
		arg.CompanySize,
		arg.Address,
		arg.City,
		arg.State,
		arg.ZipCode,
		arg.Country,
		arg.Status,
		arg.Source,
		arg.AssignedTo,
		arg.Tags,
		arg.CustomFields,
		arg.Notes,
	)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Type,
		&i.Email,
		&i.Phone,
		&i.Website,
		&i.Industry,
		&i.CompanySize,
		&i.Address,
		&i.City,
		&i.State,
		&i.ZipCode,
		&i.Country,
		&i.Status,
		&i.Source,
		&i.AssignedTo,
		&i.LifetimeValue,
		&i.Tags,
		&i.CustomFields,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastContactedAt,
	)
	return i, err
}

const createClientContact = `-- name: CreateClientContact :one
INSERT INTO client_contacts (client_id, name, email, phone, role, is_primary, notes)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, client_id, name, email, phone, role, is_primary, notes, created_at, updated_at
`

type CreateClientContactParams struct {
	ClientID  pgtype.UUID `json:"client_id"`
	Name      string      `json:"name"`
	Email     *string     `json:"email"`
	Phone     *string     `json:"phone"`
	Role      *string     `json:"role"`
	IsPrimary *bool       `json:"is_primary"`
	Notes     *string     `json:"notes"`
}

func (q *Queries) CreateClientContact(ctx context.Context, arg CreateClientContactParams) (ClientContact, error) {
	row := q.db.QueryRow(ctx, createClientContact,
		arg.ClientID,
		arg.Name,
		arg.Email,
		arg.Phone,
		arg.Role,
		arg.IsPrimary,
		arg.Notes,
	)
	var i ClientContact
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.Role,
		&i.IsPrimary,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createClientDeal = `-- name: CreateClientDeal :one
INSERT INTO deals (
    client_id, user_id, pipeline_id, stage_id,
    name, amount, probability, expected_close_date,
    description, status
)
SELECT
    $1,                                           -- client_id
    c.user_id,                                    -- user_id (from client's owner)
    p.id,                                         -- pipeline_id (default pipeline)
    ps.id,                                        -- stage_id (matched by stage name)
    $2,                                           -- name
    $3,                                           -- amount (was value)
    $5,                                           -- probability
    $6,                                           -- expected_close_date
    $7,                                           -- description (was notes)
    'open'                                        -- status
FROM clients c
JOIN pipelines p ON p.user_id = c.user_id AND p.is_default = TRUE
JOIN pipeline_stages ps ON ps.pipeline_id = p.id AND ps.name = $4  -- stage name lookup
WHERE c.id = $1
RETURNING id, user_id, pipeline_id, stage_id, name, description, amount, currency, probability, expected_close_date, actual_close_date, owner_id, company_id, primary_contact_id, status, lost_reason, priority, lead_source, deal_score, custom_fields, client_id, stage_entered_at, created_at, updated_at
`

type CreateClientDealParams struct {
	ClientID          pgtype.UUID    `json:"client_id"`
	Name              string         `json:"name"`
	Amount            pgtype.Numeric `json:"amount"`
	Name_2            string         `json:"name_2"`
	Probability       *int32         `json:"probability"`
	ExpectedCloseDate pgtype.Date    `json:"expected_close_date"`
	Description       *string        `json:"description"`
}

func (q *Queries) CreateClientDeal(ctx context.Context, arg CreateClientDealParams) (Deal, error) {
	row := q.db.QueryRow(ctx, createClientDeal,
		arg.ClientID,
		arg.Name,
		arg.Amount,
		arg.Name_2,
		arg.Probability,
		arg.ExpectedCloseDate,
		arg.Description,
	)
	var i Deal
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PipelineID,
		&i.StageID,
		&i.Name,
		&i.Description,
		&i.Amount,
		&i.Currency,
		&i.Probability,
		&i.ExpectedCloseDate,
		&i.ActualCloseDate,
		&i.OwnerID,
		&i.CompanyID,
		&i.PrimaryContactID,
		&i.Status,
		&i.LostReason,
		&i.Priority,
		&i.LeadSource,
		&i.DealScore,
		&i.CustomFields,
		&i.ClientID,
		&i.StageEnteredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createClientInteraction = `-- name: CreateClientInteraction :one
INSERT INTO client_interactions (client_id, contact_id, type, subject, description, outcome, occurred_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, client_id, contact_id, type, subject, description, outcome, occurred_at, created_at
`

type CreateClientInteractionParams struct {
	ClientID    pgtype.UUID        `json:"client_id"`
	ContactID   pgtype.UUID        `json:"contact_id"`
	Type        Interactiontype    `json:"type"`
	Subject     string             `json:"subject"`
	Description *string            `json:"description"`
	Outcome     *string            `json:"outcome"`
	OccurredAt  pgtype.Timestamptz `json:"occurred_at"`
}

func (q *Queries) CreateClientInteraction(ctx context.Context, arg CreateClientInteractionParams) (ClientInteraction, error) {
	row := q.db.QueryRow(ctx, createClientInteraction,
		arg.ClientID,
		arg.ContactID,
		arg.Type,
		arg.Subject,
		arg.Description,
		arg.Outcome,
		arg.OccurredAt,
	)
	var i ClientInteraction
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.ContactID,
		&i.Type,
		&i.Subject,
		&i.Description,
		&i.Outcome,
		&i.OccurredAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteClient = `-- name: DeleteClient :exec
DELETE FROM clients
WHERE id = $1 AND user_id = $2
`

type DeleteClientParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID string      `json:"user_id"`
}

func (q *Queries) DeleteClient(ctx context.Context, arg DeleteClientParams) error {
	_, err := q.db.Exec(ctx, deleteClient, arg.ID, arg.UserID)
	return err
}

const deleteClientContact = `-- name: DeleteClientContact :exec
DELETE FROM client_contacts
WHERE id = $1 AND client_id = $2
`

type DeleteClientContactParams struct {
	ID       pgtype.UUID `json:"id"`
	ClientID pgtype.UUID `json:"client_id"`
}

func (q *Queries) DeleteClientContact(ctx context.Context, arg DeleteClientContactParams) error {
	_, err := q.db.Exec(ctx, deleteClientContact, arg.ID, arg.ClientID)
	return err
}

const getClient = `-- name: GetClient :one
SELECT id, user_id, name, type, email, phone, website, industry, company_size, address, city, state, zip_code, country, status, source, assigned_to, lifetime_value, tags, custom_fields, notes, created_at, updated_at, last_contacted_at FROM clients
WHERE id = $1 AND user_id = $2
`

type GetClientParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID string      `json:"user_id"`
}

func (q *Queries) GetClient(ctx context.Context, arg GetClientParams) (Client, error) {
	row := q.db.QueryRow(ctx, getClient, arg.ID, arg.UserID)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Type,
		&i.Email,
		&i.Phone,
		&i.Website,
		&i.Industry,
		&i.CompanySize,
		&i.Address,
		&i.City,
		&i.State,
		&i.ZipCode,
		&i.Country,
		&i.Status,
		&i.Source,
		&i.AssignedTo,
		&i.LifetimeValue,
		&i.Tags,
		&i.CustomFields,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastContactedAt,
	)
	return i, err
}

const listClientContacts = `-- name: ListClientContacts :many
SELECT id, client_id, name, email, phone, role, is_primary, notes, created_at, updated_at FROM client_contacts
WHERE client_id = $1
ORDER BY is_primary DESC, name ASC
`

func (q *Queries) ListClientContacts(ctx context.Context, clientID pgtype.UUID) ([]ClientContact, error) {
	rows, err := q.db.Query(ctx, listClientContacts, clientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClientContact{}
	for rows.Next() {
		var i ClientContact
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.Name,
			&i.Email,
			&i.Phone,
			&i.Role,
			&i.IsPrimary,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClientDeals = `-- name: ListClientDeals :many
SELECT d.id, d.user_id, d.pipeline_id, d.stage_id, d.name, d.description, d.amount, d.currency, d.probability, d.expected_close_date, d.actual_close_date, d.owner_id, d.company_id, d.primary_contact_id, d.status, d.lost_reason, d.priority, d.lead_source, d.deal_score, d.custom_fields, d.client_id, d.stage_entered_at, d.created_at, d.updated_at, ps.name as stage_name
FROM deals d
JOIN pipeline_stages ps ON d.stage_id = ps.id
WHERE d.client_id = $1
ORDER BY d.created_at DESC
`

type ListClientDealsRow struct {
	ID                pgtype.UUID        `json:"id"`
	UserID            string             `json:"user_id"`
	PipelineID        pgtype.UUID        `json:"pipeline_id"`
	StageID           pgtype.UUID        `json:"stage_id"`
	Name              string             `json:"name"`
	Description       *string            `json:"description"`
	Amount            pgtype.Numeric     `json:"amount"`
	Currency          *string            `json:"currency"`
	Probability       *int32             `json:"probability"`
	ExpectedCloseDate pgtype.Date        `json:"expected_close_date"`
	ActualCloseDate   pgtype.Date        `json:"actual_close_date"`
	OwnerID           *string            `json:"owner_id"`
	CompanyID         pgtype.UUID        `json:"company_id"`
	PrimaryContactID  pgtype.UUID        `json:"primary_contact_id"`
	Status            *string            `json:"status"`
	LostReason        *string            `json:"lost_reason"`
	Priority          *string            `json:"priority"`
	LeadSource        *string            `json:"lead_source"`
	DealScore         *int32             `json:"deal_score"`
	CustomFields      []byte             `json:"custom_fields"`
	ClientID          pgtype.UUID        `json:"client_id"`
	StageEnteredAt    pgtype.Timestamptz `json:"stage_entered_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	StageName         string             `json:"stage_name"`
}

func (q *Queries) ListClientDeals(ctx context.Context, clientID pgtype.UUID) ([]ListClientDealsRow, error) {
	rows, err := q.db.Query(ctx, listClientDeals, clientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListClientDealsRow{}
	for rows.Next() {
		var i ListClientDealsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.PipelineID,
			&i.StageID,
			&i.Name,
			&i.Description,
			&i.Amount,
			&i.Currency,
			&i.Probability,
			&i.ExpectedCloseDate,
			&i.ActualCloseDate,
			&i.OwnerID,
			&i.CompanyID,
			&i.PrimaryContactID,
			&i.Status,
			&i.LostReason,
			&i.Priority,
			&i.LeadSource,
			&i.DealScore,
			&i.CustomFields,
			&i.ClientID,
			&i.StageEnteredAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StageName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClientInteractions = `-- name: ListClientInteractions :many
SELECT id, client_id, contact_id, type, subject, description, outcome, occurred_at, created_at FROM client_interactions
WHERE client_id = $1
ORDER BY occurred_at DESC
`

func (q *Queries) ListClientInteractions(ctx context.Context, clientID pgtype.UUID) ([]ClientInteraction, error) {
	rows, err := q.db.Query(ctx, listClientInteractions, clientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClientInteraction{}
	for rows.Next() {
		var i ClientInteraction
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.ContactID,
			&i.Type,
			&i.Subject,
			&i.Description,
			&i.Outcome,
			&i.OccurredAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClients = `-- name: ListClients :many
SELECT id, user_id, name, type, email, phone, website, industry, company_size, address, city, state, zip_code, country, status, source, assigned_to, lifetime_value, tags, custom_fields, notes, created_at, updated_at, last_contacted_at FROM clients
WHERE user_id = $1
  AND ($2::clientstatus IS NULL OR status = $2)
  AND ($3::clienttype IS NULL OR type = $3)
  AND ($4::text IS NULL OR name ILIKE '%' || $4 || '%')
ORDER BY updated_at DESC
`

type ListClientsParams struct {
	UserID     string           `json:"user_id"`
	Status     NullClientstatus `json:"status"`
	ClientType NullClienttype   `json:"client_type"`
	Search     *string          `json:"search"`
}

func (q *Queries) ListClients(ctx context.Context, arg ListClientsParams) ([]Client, error) {
	rows, err := q.db.Query(ctx, listClients,
		arg.UserID,
		arg.Status,
		arg.ClientType,
		arg.Search,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Client{}
	for rows.Next() {
		var i Client
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Type,
			&i.Email,
			&i.Phone,
			&i.Website,
			&i.Industry,
			&i.CompanySize,
			&i.Address,
			&i.City,
			&i.State,
			&i.ZipCode,
			&i.Country,
			&i.Status,
			&i.Source,
			&i.AssignedTo,
			&i.LifetimeValue,
			&i.Tags,
			&i.CustomFields,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastContactedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeals = `-- name: ListDeals :many
SELECT d.id, d.user_id, d.pipeline_id, d.stage_id, d.name, d.description, d.amount, d.currency, d.probability, d.expected_close_date, d.actual_close_date, d.owner_id, d.company_id, d.primary_contact_id, d.status, d.lost_reason, d.priority, d.lead_source, d.deal_score, d.custom_fields, d.client_id, d.stage_entered_at, d.created_at, d.updated_at, c.name as client_name, ps.name as stage_name
FROM deals d
JOIN clients c ON c.id = d.client_id
JOIN pipeline_stages ps ON d.stage_id = ps.id
WHERE c.user_id = $1
  AND ($2::varchar IS NULL OR d.status = $2)
ORDER BY d.updated_at DESC
`

type ListDealsParams struct {
	UserID string  `json:"user_id"`
	Status *string `json:"status"`
}

type ListDealsRow struct {
	ID                pgtype.UUID        `json:"id"`
	UserID            string             `json:"user_id"`
	PipelineID        pgtype.UUID        `json:"pipeline_id"`
	StageID           pgtype.UUID        `json:"stage_id"`
	Name              string             `json:"name"`
	Description       *string            `json:"description"`
	Amount            pgtype.Numeric     `json:"amount"`
	Currency          *string            `json:"currency"`
	Probability       *int32             `json:"probability"`
	ExpectedCloseDate pgtype.Date        `json:"expected_close_date"`
	ActualCloseDate   pgtype.Date        `json:"actual_close_date"`
	OwnerID           *string            `json:"owner_id"`
	CompanyID         pgtype.UUID        `json:"company_id"`
	PrimaryContactID  pgtype.UUID        `json:"primary_contact_id"`
	Status            *string            `json:"status"`
	LostReason        *string            `json:"lost_reason"`
	Priority          *string            `json:"priority"`
	LeadSource        *string            `json:"lead_source"`
	DealScore         *int32             `json:"deal_score"`
	CustomFields      []byte             `json:"custom_fields"`
	ClientID          pgtype.UUID        `json:"client_id"`
	StageEnteredAt    pgtype.Timestamptz `json:"stage_entered_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	ClientName        string             `json:"client_name"`
	StageName         string             `json:"stage_name"`
}

func (q *Queries) ListDeals(ctx context.Context, arg ListDealsParams) ([]ListDealsRow, error) {
	rows, err := q.db.Query(ctx, listDeals, arg.UserID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDealsRow{}
	for rows.Next() {
		var i ListDealsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.PipelineID,
			&i.StageID,
			&i.Name,
			&i.Description,
			&i.Amount,
			&i.Currency,
			&i.Probability,
			&i.ExpectedCloseDate,
			&i.ActualCloseDate,
			&i.OwnerID,
			&i.CompanyID,
			&i.PrimaryContactID,
			&i.Status,
			&i.LostReason,
			&i.Priority,
			&i.LeadSource,
			&i.DealScore,
			&i.CustomFields,
			&i.ClientID,
			&i.StageEnteredAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ClientName,
			&i.StageName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateClient = `-- name: UpdateClient :one
UPDATE clients
SET name = $2, type = $3, email = $4, phone = $5, website = $6, industry = $7, company_size = $8,
    address = $9, city = $10, state = $11, zip_code = $12, country = $13, status = $14, source = $15,
    assigned_to = $16, tags = $17, custom_fields = $18, notes = $19, updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, name, type, email, phone, website, industry, company_size, address, city, state, zip_code, country, status, source, assigned_to, lifetime_value, tags, custom_fields, notes, created_at, updated_at, last_contacted_at
`

type UpdateClientParams struct {
	ID           pgtype.UUID      `json:"id"`
	Name         string           `json:"name"`
	Type         NullClienttype   `json:"type"`
	Email        *string          `json:"email"`
	Phone        *string          `json:"phone"`
	Website      *string          `json:"website"`
	Industry     *string          `json:"industry"`
	CompanySize  *string          `json:"company_size"`
	Address      *string          `json:"address"`
	City         *string          `json:"city"`
	State        *string          `json:"state"`
	ZipCode      *string          `json:"zip_code"`
	Country      *string          `json:"country"`
	Status       NullClientstatus `json:"status"`
	Source       *string          `json:"source"`
	AssignedTo   *string          `json:"assigned_to"`
	Tags         []byte           `json:"tags"`
	CustomFields []byte           `json:"custom_fields"`
	Notes        *string          `json:"notes"`
}

func (q *Queries) UpdateClient(ctx context.Context, arg UpdateClientParams) (Client, error) {
	row := q.db.QueryRow(ctx, updateClient,
		arg.ID,
		arg.Name,
		arg.Type,
		arg.Email,
		arg.Phone,
		arg.Website,
		arg.Industry,
		arg.CompanySize,
		arg.Address,
		arg.City,
		arg.State,
		arg.ZipCode,
		arg.Country,
		arg.Status,
		arg.Source,
		arg.AssignedTo,
		arg.Tags,
		arg.CustomFields,
		arg.Notes,
	)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Type,
		&i.Email,
		&i.Phone,
		&i.Website,
		&i.Industry,
		&i.CompanySize,
		&i.Address,
		&i.City,
		&i.State,
		&i.ZipCode,
		&i.Country,
		&i.Status,
		&i.Source,
		&i.AssignedTo,
		&i.LifetimeValue,
		&i.Tags,
		&i.CustomFields,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastContactedAt,
	)
	return i, err
}

const updateClientContact = `-- name: UpdateClientContact :one
UPDATE client_contacts
SET name = $2, email = $3, phone = $4, role = $5, is_primary = $6, notes = $7, updated_at = NOW()
WHERE id = $1
RETURNING id, client_id, name, email, phone, role, is_primary, notes, created_at, updated_at
`

type UpdateClientContactParams struct {
	ID        pgtype.UUID `json:"id"`
	Name      string      `json:"name"`
	Email     *string     `json:"email"`
	Phone     *string     `json:"phone"`
	Role      *string     `json:"role"`
	IsPrimary *bool       `json:"is_primary"`
	Notes     *string     `json:"notes"`
}

func (q *Queries) UpdateClientContact(ctx context.Context, arg UpdateClientContactParams) (ClientContact, error) {
	row := q.db.QueryRow(ctx, updateClientContact,
		arg.ID,
		arg.Name,
		arg.Email,
		arg.Phone,
		arg.Role,
		arg.IsPrimary,
		arg.Notes,
	)
	var i ClientContact
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.Role,
		&i.IsPrimary,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateClientDeal = `-- name: UpdateClientDeal :one
UPDATE deals
SET name = $2, amount = $3, probability = $5,
    expected_close_date = $6, description = $7,
    status = $4, updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, pipeline_id, stage_id, name, description, amount, currency, probability, expected_close_date, actual_close_date, owner_id, company_id, primary_contact_id, status, lost_reason, priority, lead_source, deal_score, custom_fields, client_id, stage_entered_at, created_at, updated_at
`

type UpdateClientDealParams struct {
	ID                pgtype.UUID    `json:"id"`
	Name              string         `json:"name"`
	Amount            pgtype.Numeric `json:"amount"`
	Status            *string        `json:"status"`
	Probability       *int32         `json:"probability"`
	ExpectedCloseDate pgtype.Date    `json:"expected_close_date"`
	Description       *string        `json:"description"`
}

func (q *Queries) UpdateClientDeal(ctx context.Context, arg UpdateClientDealParams) (Deal, error) {
	row := q.db.QueryRow(ctx, updateClientDeal,
		arg.ID,
		arg.Name,
		arg.Amount,
		arg.Status,
		arg.Probability,
		arg.ExpectedCloseDate,
		arg.Description,
	)
	var i Deal
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PipelineID,
		&i.StageID,
		&i.Name,
		&i.Description,
		&i.Amount,
		&i.Currency,
		&i.Probability,
		&i.ExpectedCloseDate,
		&i.ActualCloseDate,
		&i.OwnerID,
		&i.CompanyID,
		&i.PrimaryContactID,
		&i.Status,
		&i.LostReason,
		&i.Priority,
		&i.LeadSource,
		&i.DealScore,
		&i.CustomFields,
		&i.ClientID,
		&i.StageEnteredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateClientStatus = `-- name: UpdateClientStatus :one
UPDATE clients
SET status = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, name, type, email, phone, website, industry, company_size, address, city, state, zip_code, country, status, source, assigned_to, lifetime_value, tags, custom_fields, notes, created_at, updated_at, last_contacted_at
`

type UpdateClientStatusParams struct {
	ID     pgtype.UUID      `json:"id"`
	Status NullClientstatus `json:"status"`
}

func (q *Queries) UpdateClientStatus(ctx context.Context, arg UpdateClientStatusParams) (Client, error) {
	row := q.db.QueryRow(ctx, updateClientStatus, arg.ID, arg.Status)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Type,
		&i.Email,
		&i.Phone,
		&i.Website,
		&i.Industry,
		&i.CompanySize,
		&i.Address,
		&i.City,
		&i.State,
		&i.ZipCode,
		&i.Country,
		&i.Status,
		&i.Source,
		&i.AssignedTo,
		&i.LifetimeValue,
		&i.Tags,
		&i.CustomFields,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastContactedAt,
	)
	return i, err
}

const updateDealStage = `-- name: UpdateDealStage :one
UPDATE deals
SET stage_id = (
        SELECT ps.id FROM pipeline_stages ps
        WHERE ps.pipeline_id = deals.pipeline_id AND ps.name = $2
        LIMIT 1
    ),
    status = CASE
        WHEN $2 = 'Won' THEN 'won'
        WHEN $2 = 'Lost' THEN 'lost'
        ELSE status
    END,
    actual_close_date = CASE
        WHEN $2 IN ('Won', 'Lost') THEN NOW()
        ELSE NULL
    END,
    updated_at = NOW()
WHERE deals.id = $1
RETURNING id, user_id, pipeline_id, stage_id, name, description, amount, currency, probability, expected_close_date, actual_close_date, owner_id, company_id, primary_contact_id, status, lost_reason, priority, lead_source, deal_score, custom_fields, client_id, stage_entered_at, created_at, updated_at
`

type UpdateDealStageParams struct {
	ID   pgtype.UUID `json:"id"`
	Name string      `json:"name"`
}

func (q *Queries) UpdateDealStage(ctx context.Context, arg UpdateDealStageParams) (Deal, error) {
	row := q.db.QueryRow(ctx, updateDealStage, arg.ID, arg.Name)
	var i Deal
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PipelineID,
		&i.StageID,
		&i.Name,
		&i.Description,
		&i.Amount,
		&i.Currency,
		&i.Probability,
		&i.ExpectedCloseDate,
		&i.ActualCloseDate,
		&i.OwnerID,
		&i.CompanyID,
		&i.PrimaryContactID,
		&i.Status,
		&i.LostReason,
		&i.Priority,
		&i.LeadSource,
		&i.DealScore,
		&i.CustomFields,
		&i.ClientID,
		&i.StageEnteredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
