// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: focus_configurations.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createFocusConfiguration = `-- name: CreateFocusConfiguration :one
INSERT INTO focus_configurations (
    user_id, template_id, custom_name, temperature, max_tokens,
    output_style, response_format, max_response_length, require_sources,
    auto_search, search_depth, kb_context_limit, include_history_count,
    thinking_enabled, thinking_style, custom_system_prompt, preferred_model,
    auto_load_kb_categories, keyboard_shortcut, is_favorite
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20
)
RETURNING id, user_id, template_id, custom_name, temperature, max_tokens, output_style, response_format, max_response_length, require_sources, auto_search, search_depth, kb_context_limit, include_history_count, thinking_enabled, thinking_style, custom_system_prompt, preferred_model, auto_load_kb_categories, keyboard_shortcut, is_favorite, use_count, last_used_at, created_at, updated_at
`

type CreateFocusConfigurationParams struct {
	UserID               string         `json:"user_id"`
	TemplateID           pgtype.UUID    `json:"template_id"`
	CustomName           *string        `json:"custom_name"`
	Temperature          pgtype.Numeric `json:"temperature"`
	MaxTokens            *int32         `json:"max_tokens"`
	OutputStyle          *string        `json:"output_style"`
	ResponseFormat       *string        `json:"response_format"`
	MaxResponseLength    *int32         `json:"max_response_length"`
	RequireSources       *bool          `json:"require_sources"`
	AutoSearch           *bool          `json:"auto_search"`
	SearchDepth          *string        `json:"search_depth"`
	KbContextLimit       *int32         `json:"kb_context_limit"`
	IncludeHistoryCount  *int32         `json:"include_history_count"`
	ThinkingEnabled      *bool          `json:"thinking_enabled"`
	ThinkingStyle        *string        `json:"thinking_style"`
	CustomSystemPrompt   *string        `json:"custom_system_prompt"`
	PreferredModel       *string        `json:"preferred_model"`
	AutoLoadKbCategories []string       `json:"auto_load_kb_categories"`
	KeyboardShortcut     *string        `json:"keyboard_shortcut"`
	IsFavorite           *bool          `json:"is_favorite"`
}

func (q *Queries) CreateFocusConfiguration(ctx context.Context, arg CreateFocusConfigurationParams) (FocusConfiguration, error) {
	row := q.db.QueryRow(ctx, createFocusConfiguration,
		arg.UserID,
		arg.TemplateID,
		arg.CustomName,
		arg.Temperature,
		arg.MaxTokens,
		arg.OutputStyle,
		arg.ResponseFormat,
		arg.MaxResponseLength,
		arg.RequireSources,
		arg.AutoSearch,
		arg.SearchDepth,
		arg.KbContextLimit,
		arg.IncludeHistoryCount,
		arg.ThinkingEnabled,
		arg.ThinkingStyle,
		arg.CustomSystemPrompt,
		arg.PreferredModel,
		arg.AutoLoadKbCategories,
		arg.KeyboardShortcut,
		arg.IsFavorite,
	)
	var i FocusConfiguration
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TemplateID,
		&i.CustomName,
		&i.Temperature,
		&i.MaxTokens,
		&i.OutputStyle,
		&i.ResponseFormat,
		&i.MaxResponseLength,
		&i.RequireSources,
		&i.AutoSearch,
		&i.SearchDepth,
		&i.KbContextLimit,
		&i.IncludeHistoryCount,
		&i.ThinkingEnabled,
		&i.ThinkingStyle,
		&i.CustomSystemPrompt,
		&i.PreferredModel,
		&i.AutoLoadKbCategories,
		&i.KeyboardShortcut,
		&i.IsFavorite,
		&i.UseCount,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createFocusContextPreset = `-- name: CreateFocusContextPreset :one
INSERT INTO focus_context_presets (
    user_id, name, description, kb_artifact_ids, kb_categories, project_ids, default_search_queries, search_domains
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, user_id, name, description, kb_artifact_ids, kb_categories, project_ids, default_search_queries, search_domains, created_at, updated_at
`

type CreateFocusContextPresetParams struct {
	UserID               string        `json:"user_id"`
	Name                 string        `json:"name"`
	Description          *string       `json:"description"`
	KbArtifactIds        []pgtype.UUID `json:"kb_artifact_ids"`
	KbCategories         []string      `json:"kb_categories"`
	ProjectIds           []pgtype.UUID `json:"project_ids"`
	DefaultSearchQueries []string      `json:"default_search_queries"`
	SearchDomains        []string      `json:"search_domains"`
}

func (q *Queries) CreateFocusContextPreset(ctx context.Context, arg CreateFocusContextPresetParams) (FocusContextPreset, error) {
	row := q.db.QueryRow(ctx, createFocusContextPreset,
		arg.UserID,
		arg.Name,
		arg.Description,
		arg.KbArtifactIds,
		arg.KbCategories,
		arg.ProjectIds,
		arg.DefaultSearchQueries,
		arg.SearchDomains,
	)
	var i FocusContextPreset
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.KbArtifactIds,
		&i.KbCategories,
		&i.ProjectIds,
		&i.DefaultSearchQueries,
		&i.SearchDomains,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteFocusConfiguration = `-- name: DeleteFocusConfiguration :exec
DELETE FROM focus_configurations
WHERE id = $1 AND user_id = $2
`

type DeleteFocusConfigurationParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID string      `json:"user_id"`
}

func (q *Queries) DeleteFocusConfiguration(ctx context.Context, arg DeleteFocusConfigurationParams) error {
	_, err := q.db.Exec(ctx, deleteFocusConfiguration, arg.ID, arg.UserID)
	return err
}

const deleteFocusContextPreset = `-- name: DeleteFocusContextPreset :exec
DELETE FROM focus_context_presets
WHERE id = $1 AND user_id = $2
`

type DeleteFocusContextPresetParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID string      `json:"user_id"`
}

func (q *Queries) DeleteFocusContextPreset(ctx context.Context, arg DeleteFocusContextPresetParams) error {
	_, err := q.db.Exec(ctx, deleteFocusContextPreset, arg.ID, arg.UserID)
	return err
}

const getEffectiveFocusSettings = `-- name: GetEffectiveFocusSettings :one
SELECT
    fmt.name,
    fmt.display_name,
    COALESCE(fc.custom_name, fmt.display_name) as effective_name,
    COALESCE(fc.preferred_model, fmt.default_model) as effective_model,
    COALESCE(fc.temperature, fmt.temperature) as effective_temperature,
    COALESCE(fc.max_tokens, fmt.max_tokens) as effective_max_tokens,
    COALESCE(fc.output_style, fmt.output_style) as effective_output_style,
    COALESCE(fc.response_format, fmt.response_format) as effective_response_format,
    COALESCE(fc.max_response_length, fmt.max_response_length) as effective_max_response_length,
    COALESCE(fc.require_sources, fmt.require_sources) as effective_require_sources,
    COALESCE(fc.auto_search, fmt.auto_search) as effective_auto_search,
    COALESCE(fc.search_depth, fmt.search_depth) as effective_search_depth,
    COALESCE(fc.kb_context_limit, fmt.kb_context_limit) as effective_kb_context_limit,
    COALESCE(fc.include_history_count, fmt.include_history_count) as effective_include_history_count,
    COALESCE(fc.thinking_enabled, fmt.thinking_enabled) as effective_thinking_enabled,
    COALESCE(fc.thinking_style, fmt.thinking_style) as effective_thinking_style,
    COALESCE(fc.custom_system_prompt, '') as custom_system_prompt,
    fmt.system_prompt_prefix,
    fmt.system_prompt_suffix,
    fc.auto_load_kb_categories
FROM focus_mode_templates fmt
LEFT JOIN focus_configurations fc ON fc.template_id = fmt.id AND fc.user_id = $1
WHERE fmt.name = $2 AND fmt.is_active = true
`

type GetEffectiveFocusSettingsParams struct {
	UserID string `json:"user_id"`
	Name   string `json:"name"`
}

type GetEffectiveFocusSettingsRow struct {
	Name                         string         `json:"name"`
	DisplayName                  string         `json:"display_name"`
	EffectiveName                string         `json:"effective_name"`
	EffectiveModel               *string        `json:"effective_model"`
	EffectiveTemperature         pgtype.Numeric `json:"effective_temperature"`
	EffectiveMaxTokens           *int32         `json:"effective_max_tokens"`
	EffectiveOutputStyle         *string        `json:"effective_output_style"`
	EffectiveResponseFormat      *string        `json:"effective_response_format"`
	EffectiveMaxResponseLength   *int32         `json:"effective_max_response_length"`
	EffectiveRequireSources      *bool          `json:"effective_require_sources"`
	EffectiveAutoSearch          *bool          `json:"effective_auto_search"`
	EffectiveSearchDepth         *string        `json:"effective_search_depth"`
	EffectiveKbContextLimit      *int32         `json:"effective_kb_context_limit"`
	EffectiveIncludeHistoryCount *int32         `json:"effective_include_history_count"`
	EffectiveThinkingEnabled     *bool          `json:"effective_thinking_enabled"`
	EffectiveThinkingStyle       *string        `json:"effective_thinking_style"`
	CustomSystemPrompt           string         `json:"custom_system_prompt"`
	SystemPromptPrefix           *string        `json:"system_prompt_prefix"`
	SystemPromptSuffix           *string        `json:"system_prompt_suffix"`
	AutoLoadKbCategories         []string       `json:"auto_load_kb_categories"`
}

// Returns merged settings (template defaults + user overrides)
func (q *Queries) GetEffectiveFocusSettings(ctx context.Context, arg GetEffectiveFocusSettingsParams) (GetEffectiveFocusSettingsRow, error) {
	row := q.db.QueryRow(ctx, getEffectiveFocusSettings, arg.UserID, arg.Name)
	var i GetEffectiveFocusSettingsRow
	err := row.Scan(
		&i.Name,
		&i.DisplayName,
		&i.EffectiveName,
		&i.EffectiveModel,
		&i.EffectiveTemperature,
		&i.EffectiveMaxTokens,
		&i.EffectiveOutputStyle,
		&i.EffectiveResponseFormat,
		&i.EffectiveMaxResponseLength,
		&i.EffectiveRequireSources,
		&i.EffectiveAutoSearch,
		&i.EffectiveSearchDepth,
		&i.EffectiveKbContextLimit,
		&i.EffectiveIncludeHistoryCount,
		&i.EffectiveThinkingEnabled,
		&i.EffectiveThinkingStyle,
		&i.CustomSystemPrompt,
		&i.SystemPromptPrefix,
		&i.SystemPromptSuffix,
		&i.AutoLoadKbCategories,
	)
	return i, err
}

const getFocusContextPresets = `-- name: GetFocusContextPresets :many
SELECT id, user_id, name, description, kb_artifact_ids, kb_categories, project_ids, default_search_queries, search_domains, created_at, updated_at FROM focus_context_presets
WHERE user_id = $1
ORDER BY name ASC
`

func (q *Queries) GetFocusContextPresets(ctx context.Context, userID string) ([]FocusContextPreset, error) {
	rows, err := q.db.Query(ctx, getFocusContextPresets, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FocusContextPreset{}
	for rows.Next() {
		var i FocusContextPreset
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Description,
			&i.KbArtifactIds,
			&i.KbCategories,
			&i.ProjectIds,
			&i.DefaultSearchQueries,
			&i.SearchDomains,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFocusModeTemplateByID = `-- name: GetFocusModeTemplateByID :one
SELECT id, name, display_name, description, icon, default_model, temperature, max_tokens, output_style, response_format, max_response_length, require_sources, auto_search, search_depth, kb_context_limit, include_history_count, thinking_enabled, thinking_style, system_prompt_prefix, system_prompt_suffix, sort_order, is_active, created_at, updated_at FROM focus_mode_templates
WHERE id = $1
`

func (q *Queries) GetFocusModeTemplateByID(ctx context.Context, id pgtype.UUID) (FocusModeTemplate, error) {
	row := q.db.QueryRow(ctx, getFocusModeTemplateByID, id)
	var i FocusModeTemplate
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DisplayName,
		&i.Description,
		&i.Icon,
		&i.DefaultModel,
		&i.Temperature,
		&i.MaxTokens,
		&i.OutputStyle,
		&i.ResponseFormat,
		&i.MaxResponseLength,
		&i.RequireSources,
		&i.AutoSearch,
		&i.SearchDepth,
		&i.KbContextLimit,
		&i.IncludeHistoryCount,
		&i.ThinkingEnabled,
		&i.ThinkingStyle,
		&i.SystemPromptPrefix,
		&i.SystemPromptSuffix,
		&i.SortOrder,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFocusModeTemplateByName = `-- name: GetFocusModeTemplateByName :one
SELECT id, name, display_name, description, icon, default_model, temperature, max_tokens, output_style, response_format, max_response_length, require_sources, auto_search, search_depth, kb_context_limit, include_history_count, thinking_enabled, thinking_style, system_prompt_prefix, system_prompt_suffix, sort_order, is_active, created_at, updated_at FROM focus_mode_templates
WHERE name = $1 AND is_active = true
`

func (q *Queries) GetFocusModeTemplateByName(ctx context.Context, name string) (FocusModeTemplate, error) {
	row := q.db.QueryRow(ctx, getFocusModeTemplateByName, name)
	var i FocusModeTemplate
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DisplayName,
		&i.Description,
		&i.Icon,
		&i.DefaultModel,
		&i.Temperature,
		&i.MaxTokens,
		&i.OutputStyle,
		&i.ResponseFormat,
		&i.MaxResponseLength,
		&i.RequireSources,
		&i.AutoSearch,
		&i.SearchDepth,
		&i.KbContextLimit,
		&i.IncludeHistoryCount,
		&i.ThinkingEnabled,
		&i.ThinkingStyle,
		&i.SystemPromptPrefix,
		&i.SystemPromptSuffix,
		&i.SortOrder,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFocusModeTemplates = `-- name: GetFocusModeTemplates :many
SELECT id, name, display_name, description, icon, default_model, temperature, max_tokens, output_style, response_format, max_response_length, require_sources, auto_search, search_depth, kb_context_limit, include_history_count, thinking_enabled, thinking_style, system_prompt_prefix, system_prompt_suffix, sort_order, is_active, created_at, updated_at FROM focus_mode_templates
WHERE is_active = true
ORDER BY sort_order ASC
`

func (q *Queries) GetFocusModeTemplates(ctx context.Context) ([]FocusModeTemplate, error) {
	rows, err := q.db.Query(ctx, getFocusModeTemplates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FocusModeTemplate{}
	for rows.Next() {
		var i FocusModeTemplate
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.DisplayName,
			&i.Description,
			&i.Icon,
			&i.DefaultModel,
			&i.Temperature,
			&i.MaxTokens,
			&i.OutputStyle,
			&i.ResponseFormat,
			&i.MaxResponseLength,
			&i.RequireSources,
			&i.AutoSearch,
			&i.SearchDepth,
			&i.KbContextLimit,
			&i.IncludeHistoryCount,
			&i.ThinkingEnabled,
			&i.ThinkingStyle,
			&i.SystemPromptPrefix,
			&i.SystemPromptSuffix,
			&i.SortOrder,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPresetsForFocusConfig = `-- name: GetPresetsForFocusConfig :many
SELECT fcp.id, fcp.user_id, fcp.name, fcp.description, fcp.kb_artifact_ids, fcp.kb_categories, fcp.project_ids, fcp.default_search_queries, fcp.search_domains, fcp.created_at, fcp.updated_at FROM focus_context_presets fcp
JOIN focus_configuration_presets link ON fcp.id = link.preset_id
WHERE link.focus_config_id = $1
ORDER BY link.sort_order ASC
`

func (q *Queries) GetPresetsForFocusConfig(ctx context.Context, focusConfigID pgtype.UUID) ([]FocusContextPreset, error) {
	rows, err := q.db.Query(ctx, getPresetsForFocusConfig, focusConfigID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FocusContextPreset{}
	for rows.Next() {
		var i FocusContextPreset
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Description,
			&i.KbArtifactIds,
			&i.KbCategories,
			&i.ProjectIds,
			&i.DefaultSearchQueries,
			&i.SearchDomains,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserFocusConfiguration = `-- name: GetUserFocusConfiguration :one
SELECT fc.id, fc.user_id, fc.template_id, fc.custom_name, fc.temperature, fc.max_tokens, fc.output_style, fc.response_format, fc.max_response_length, fc.require_sources, fc.auto_search, fc.search_depth, fc.kb_context_limit, fc.include_history_count, fc.thinking_enabled, fc.thinking_style, fc.custom_system_prompt, fc.preferred_model, fc.auto_load_kb_categories, fc.keyboard_shortcut, fc.is_favorite, fc.use_count, fc.last_used_at, fc.created_at, fc.updated_at, fmt.name as template_name, fmt.display_name as template_display_name
FROM focus_configurations fc
JOIN focus_mode_templates fmt ON fc.template_id = fmt.id
WHERE fc.user_id = $1 AND fmt.name = $2
`

type GetUserFocusConfigurationParams struct {
	UserID string `json:"user_id"`
	Name   string `json:"name"`
}

type GetUserFocusConfigurationRow struct {
	ID                   pgtype.UUID        `json:"id"`
	UserID               string             `json:"user_id"`
	TemplateID           pgtype.UUID        `json:"template_id"`
	CustomName           *string            `json:"custom_name"`
	Temperature          pgtype.Numeric     `json:"temperature"`
	MaxTokens            *int32             `json:"max_tokens"`
	OutputStyle          *string            `json:"output_style"`
	ResponseFormat       *string            `json:"response_format"`
	MaxResponseLength    *int32             `json:"max_response_length"`
	RequireSources       *bool              `json:"require_sources"`
	AutoSearch           *bool              `json:"auto_search"`
	SearchDepth          *string            `json:"search_depth"`
	KbContextLimit       *int32             `json:"kb_context_limit"`
	IncludeHistoryCount  *int32             `json:"include_history_count"`
	ThinkingEnabled      *bool              `json:"thinking_enabled"`
	ThinkingStyle        *string            `json:"thinking_style"`
	CustomSystemPrompt   *string            `json:"custom_system_prompt"`
	PreferredModel       *string            `json:"preferred_model"`
	AutoLoadKbCategories []string           `json:"auto_load_kb_categories"`
	KeyboardShortcut     *string            `json:"keyboard_shortcut"`
	IsFavorite           *bool              `json:"is_favorite"`
	UseCount             *int32             `json:"use_count"`
	LastUsedAt           pgtype.Timestamptz `json:"last_used_at"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
	TemplateName         string             `json:"template_name"`
	TemplateDisplayName  string             `json:"template_display_name"`
}

func (q *Queries) GetUserFocusConfiguration(ctx context.Context, arg GetUserFocusConfigurationParams) (GetUserFocusConfigurationRow, error) {
	row := q.db.QueryRow(ctx, getUserFocusConfiguration, arg.UserID, arg.Name)
	var i GetUserFocusConfigurationRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TemplateID,
		&i.CustomName,
		&i.Temperature,
		&i.MaxTokens,
		&i.OutputStyle,
		&i.ResponseFormat,
		&i.MaxResponseLength,
		&i.RequireSources,
		&i.AutoSearch,
		&i.SearchDepth,
		&i.KbContextLimit,
		&i.IncludeHistoryCount,
		&i.ThinkingEnabled,
		&i.ThinkingStyle,
		&i.CustomSystemPrompt,
		&i.PreferredModel,
		&i.AutoLoadKbCategories,
		&i.KeyboardShortcut,
		&i.IsFavorite,
		&i.UseCount,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TemplateName,
		&i.TemplateDisplayName,
	)
	return i, err
}

const getUserFocusConfigurationByID = `-- name: GetUserFocusConfigurationByID :one
SELECT fc.id, fc.user_id, fc.template_id, fc.custom_name, fc.temperature, fc.max_tokens, fc.output_style, fc.response_format, fc.max_response_length, fc.require_sources, fc.auto_search, fc.search_depth, fc.kb_context_limit, fc.include_history_count, fc.thinking_enabled, fc.thinking_style, fc.custom_system_prompt, fc.preferred_model, fc.auto_load_kb_categories, fc.keyboard_shortcut, fc.is_favorite, fc.use_count, fc.last_used_at, fc.created_at, fc.updated_at, fmt.name as template_name, fmt.display_name as template_display_name
FROM focus_configurations fc
JOIN focus_mode_templates fmt ON fc.template_id = fmt.id
WHERE fc.id = $1 AND fc.user_id = $2
`

type GetUserFocusConfigurationByIDParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID string      `json:"user_id"`
}

type GetUserFocusConfigurationByIDRow struct {
	ID                   pgtype.UUID        `json:"id"`
	UserID               string             `json:"user_id"`
	TemplateID           pgtype.UUID        `json:"template_id"`
	CustomName           *string            `json:"custom_name"`
	Temperature          pgtype.Numeric     `json:"temperature"`
	MaxTokens            *int32             `json:"max_tokens"`
	OutputStyle          *string            `json:"output_style"`
	ResponseFormat       *string            `json:"response_format"`
	MaxResponseLength    *int32             `json:"max_response_length"`
	RequireSources       *bool              `json:"require_sources"`
	AutoSearch           *bool              `json:"auto_search"`
	SearchDepth          *string            `json:"search_depth"`
	KbContextLimit       *int32             `json:"kb_context_limit"`
	IncludeHistoryCount  *int32             `json:"include_history_count"`
	ThinkingEnabled      *bool              `json:"thinking_enabled"`
	ThinkingStyle        *string            `json:"thinking_style"`
	CustomSystemPrompt   *string            `json:"custom_system_prompt"`
	PreferredModel       *string            `json:"preferred_model"`
	AutoLoadKbCategories []string           `json:"auto_load_kb_categories"`
	KeyboardShortcut     *string            `json:"keyboard_shortcut"`
	IsFavorite           *bool              `json:"is_favorite"`
	UseCount             *int32             `json:"use_count"`
	LastUsedAt           pgtype.Timestamptz `json:"last_used_at"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
	TemplateName         string             `json:"template_name"`
	TemplateDisplayName  string             `json:"template_display_name"`
}

func (q *Queries) GetUserFocusConfigurationByID(ctx context.Context, arg GetUserFocusConfigurationByIDParams) (GetUserFocusConfigurationByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserFocusConfigurationByID, arg.ID, arg.UserID)
	var i GetUserFocusConfigurationByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TemplateID,
		&i.CustomName,
		&i.Temperature,
		&i.MaxTokens,
		&i.OutputStyle,
		&i.ResponseFormat,
		&i.MaxResponseLength,
		&i.RequireSources,
		&i.AutoSearch,
		&i.SearchDepth,
		&i.KbContextLimit,
		&i.IncludeHistoryCount,
		&i.ThinkingEnabled,
		&i.ThinkingStyle,
		&i.CustomSystemPrompt,
		&i.PreferredModel,
		&i.AutoLoadKbCategories,
		&i.KeyboardShortcut,
		&i.IsFavorite,
		&i.UseCount,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TemplateName,
		&i.TemplateDisplayName,
	)
	return i, err
}

const getUserFocusConfigurations = `-- name: GetUserFocusConfigurations :many
SELECT fc.id, fc.user_id, fc.template_id, fc.custom_name, fc.temperature, fc.max_tokens, fc.output_style, fc.response_format, fc.max_response_length, fc.require_sources, fc.auto_search, fc.search_depth, fc.kb_context_limit, fc.include_history_count, fc.thinking_enabled, fc.thinking_style, fc.custom_system_prompt, fc.preferred_model, fc.auto_load_kb_categories, fc.keyboard_shortcut, fc.is_favorite, fc.use_count, fc.last_used_at, fc.created_at, fc.updated_at, fmt.name as template_name, fmt.display_name as template_display_name, fmt.icon as template_icon
FROM focus_configurations fc
JOIN focus_mode_templates fmt ON fc.template_id = fmt.id
WHERE fc.user_id = $1
ORDER BY fc.is_favorite DESC, fc.use_count DESC
`

type GetUserFocusConfigurationsRow struct {
	ID                   pgtype.UUID        `json:"id"`
	UserID               string             `json:"user_id"`
	TemplateID           pgtype.UUID        `json:"template_id"`
	CustomName           *string            `json:"custom_name"`
	Temperature          pgtype.Numeric     `json:"temperature"`
	MaxTokens            *int32             `json:"max_tokens"`
	OutputStyle          *string            `json:"output_style"`
	ResponseFormat       *string            `json:"response_format"`
	MaxResponseLength    *int32             `json:"max_response_length"`
	RequireSources       *bool              `json:"require_sources"`
	AutoSearch           *bool              `json:"auto_search"`
	SearchDepth          *string            `json:"search_depth"`
	KbContextLimit       *int32             `json:"kb_context_limit"`
	IncludeHistoryCount  *int32             `json:"include_history_count"`
	ThinkingEnabled      *bool              `json:"thinking_enabled"`
	ThinkingStyle        *string            `json:"thinking_style"`
	CustomSystemPrompt   *string            `json:"custom_system_prompt"`
	PreferredModel       *string            `json:"preferred_model"`
	AutoLoadKbCategories []string           `json:"auto_load_kb_categories"`
	KeyboardShortcut     *string            `json:"keyboard_shortcut"`
	IsFavorite           *bool              `json:"is_favorite"`
	UseCount             *int32             `json:"use_count"`
	LastUsedAt           pgtype.Timestamptz `json:"last_used_at"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
	TemplateName         string             `json:"template_name"`
	TemplateDisplayName  string             `json:"template_display_name"`
	TemplateIcon         *string            `json:"template_icon"`
}

func (q *Queries) GetUserFocusConfigurations(ctx context.Context, userID string) ([]GetUserFocusConfigurationsRow, error) {
	rows, err := q.db.Query(ctx, getUserFocusConfigurations, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUserFocusConfigurationsRow{}
	for rows.Next() {
		var i GetUserFocusConfigurationsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TemplateID,
			&i.CustomName,
			&i.Temperature,
			&i.MaxTokens,
			&i.OutputStyle,
			&i.ResponseFormat,
			&i.MaxResponseLength,
			&i.RequireSources,
			&i.AutoSearch,
			&i.SearchDepth,
			&i.KbContextLimit,
			&i.IncludeHistoryCount,
			&i.ThinkingEnabled,
			&i.ThinkingStyle,
			&i.CustomSystemPrompt,
			&i.PreferredModel,
			&i.AutoLoadKbCategories,
			&i.KeyboardShortcut,
			&i.IsFavorite,
			&i.UseCount,
			&i.LastUsedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TemplateName,
			&i.TemplateDisplayName,
			&i.TemplateIcon,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const incrementFocusConfigurationUseCount = `-- name: IncrementFocusConfigurationUseCount :exec
UPDATE focus_configurations SET
    use_count = use_count + 1,
    last_used_at = NOW()
WHERE user_id = $1 AND template_id = (
    SELECT id FROM focus_mode_templates WHERE name = $2
)
`

type IncrementFocusConfigurationUseCountParams struct {
	UserID string `json:"user_id"`
	Name   string `json:"name"`
}

func (q *Queries) IncrementFocusConfigurationUseCount(ctx context.Context, arg IncrementFocusConfigurationUseCountParams) error {
	_, err := q.db.Exec(ctx, incrementFocusConfigurationUseCount, arg.UserID, arg.Name)
	return err
}

const linkPresetToFocusConfig = `-- name: LinkPresetToFocusConfig :exec
INSERT INTO focus_configuration_presets (focus_config_id, preset_id, sort_order)
VALUES ($1, $2, $3)
ON CONFLICT (focus_config_id, preset_id) DO UPDATE SET sort_order = $3
`

type LinkPresetToFocusConfigParams struct {
	FocusConfigID pgtype.UUID `json:"focus_config_id"`
	PresetID      pgtype.UUID `json:"preset_id"`
	SortOrder     *int32      `json:"sort_order"`
}

func (q *Queries) LinkPresetToFocusConfig(ctx context.Context, arg LinkPresetToFocusConfigParams) error {
	_, err := q.db.Exec(ctx, linkPresetToFocusConfig, arg.FocusConfigID, arg.PresetID, arg.SortOrder)
	return err
}

const toggleFocusConfigurationFavorite = `-- name: ToggleFocusConfigurationFavorite :one
UPDATE focus_configurations SET
    is_favorite = NOT is_favorite,
    updated_at = NOW()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, template_id, custom_name, temperature, max_tokens, output_style, response_format, max_response_length, require_sources, auto_search, search_depth, kb_context_limit, include_history_count, thinking_enabled, thinking_style, custom_system_prompt, preferred_model, auto_load_kb_categories, keyboard_shortcut, is_favorite, use_count, last_used_at, created_at, updated_at
`

type ToggleFocusConfigurationFavoriteParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID string      `json:"user_id"`
}

func (q *Queries) ToggleFocusConfigurationFavorite(ctx context.Context, arg ToggleFocusConfigurationFavoriteParams) (FocusConfiguration, error) {
	row := q.db.QueryRow(ctx, toggleFocusConfigurationFavorite, arg.ID, arg.UserID)
	var i FocusConfiguration
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TemplateID,
		&i.CustomName,
		&i.Temperature,
		&i.MaxTokens,
		&i.OutputStyle,
		&i.ResponseFormat,
		&i.MaxResponseLength,
		&i.RequireSources,
		&i.AutoSearch,
		&i.SearchDepth,
		&i.KbContextLimit,
		&i.IncludeHistoryCount,
		&i.ThinkingEnabled,
		&i.ThinkingStyle,
		&i.CustomSystemPrompt,
		&i.PreferredModel,
		&i.AutoLoadKbCategories,
		&i.KeyboardShortcut,
		&i.IsFavorite,
		&i.UseCount,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const unlinkPresetFromFocusConfig = `-- name: UnlinkPresetFromFocusConfig :exec
DELETE FROM focus_configuration_presets
WHERE focus_config_id = $1 AND preset_id = $2
`

type UnlinkPresetFromFocusConfigParams struct {
	FocusConfigID pgtype.UUID `json:"focus_config_id"`
	PresetID      pgtype.UUID `json:"preset_id"`
}

func (q *Queries) UnlinkPresetFromFocusConfig(ctx context.Context, arg UnlinkPresetFromFocusConfigParams) error {
	_, err := q.db.Exec(ctx, unlinkPresetFromFocusConfig, arg.FocusConfigID, arg.PresetID)
	return err
}

const updateFocusConfiguration = `-- name: UpdateFocusConfiguration :one
UPDATE focus_configurations SET
    custom_name = COALESCE($3, custom_name),
    temperature = COALESCE($4, temperature),
    max_tokens = COALESCE($5, max_tokens),
    output_style = COALESCE($6, output_style),
    response_format = COALESCE($7, response_format),
    max_response_length = COALESCE($8, max_response_length),
    require_sources = COALESCE($9, require_sources),
    auto_search = COALESCE($10, auto_search),
    search_depth = COALESCE($11, search_depth),
    kb_context_limit = COALESCE($12, kb_context_limit),
    include_history_count = COALESCE($13, include_history_count),
    thinking_enabled = COALESCE($14, thinking_enabled),
    thinking_style = COALESCE($15, thinking_style),
    custom_system_prompt = COALESCE($16, custom_system_prompt),
    preferred_model = COALESCE($17, preferred_model),
    auto_load_kb_categories = COALESCE($18, auto_load_kb_categories),
    keyboard_shortcut = COALESCE($19, keyboard_shortcut),
    is_favorite = COALESCE($20, is_favorite),
    updated_at = NOW()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, template_id, custom_name, temperature, max_tokens, output_style, response_format, max_response_length, require_sources, auto_search, search_depth, kb_context_limit, include_history_count, thinking_enabled, thinking_style, custom_system_prompt, preferred_model, auto_load_kb_categories, keyboard_shortcut, is_favorite, use_count, last_used_at, created_at, updated_at
`

type UpdateFocusConfigurationParams struct {
	ID                   pgtype.UUID    `json:"id"`
	UserID               string         `json:"user_id"`
	CustomName           *string        `json:"custom_name"`
	Temperature          pgtype.Numeric `json:"temperature"`
	MaxTokens            *int32         `json:"max_tokens"`
	OutputStyle          *string        `json:"output_style"`
	ResponseFormat       *string        `json:"response_format"`
	MaxResponseLength    *int32         `json:"max_response_length"`
	RequireSources       *bool          `json:"require_sources"`
	AutoSearch           *bool          `json:"auto_search"`
	SearchDepth          *string        `json:"search_depth"`
	KbContextLimit       *int32         `json:"kb_context_limit"`
	IncludeHistoryCount  *int32         `json:"include_history_count"`
	ThinkingEnabled      *bool          `json:"thinking_enabled"`
	ThinkingStyle        *string        `json:"thinking_style"`
	CustomSystemPrompt   *string        `json:"custom_system_prompt"`
	PreferredModel       *string        `json:"preferred_model"`
	AutoLoadKbCategories []string       `json:"auto_load_kb_categories"`
	KeyboardShortcut     *string        `json:"keyboard_shortcut"`
	IsFavorite           *bool          `json:"is_favorite"`
}

func (q *Queries) UpdateFocusConfiguration(ctx context.Context, arg UpdateFocusConfigurationParams) (FocusConfiguration, error) {
	row := q.db.QueryRow(ctx, updateFocusConfiguration,
		arg.ID,
		arg.UserID,
		arg.CustomName,
		arg.Temperature,
		arg.MaxTokens,
		arg.OutputStyle,
		arg.ResponseFormat,
		arg.MaxResponseLength,
		arg.RequireSources,
		arg.AutoSearch,
		arg.SearchDepth,
		arg.KbContextLimit,
		arg.IncludeHistoryCount,
		arg.ThinkingEnabled,
		arg.ThinkingStyle,
		arg.CustomSystemPrompt,
		arg.PreferredModel,
		arg.AutoLoadKbCategories,
		arg.KeyboardShortcut,
		arg.IsFavorite,
	)
	var i FocusConfiguration
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TemplateID,
		&i.CustomName,
		&i.Temperature,
		&i.MaxTokens,
		&i.OutputStyle,
		&i.ResponseFormat,
		&i.MaxResponseLength,
		&i.RequireSources,
		&i.AutoSearch,
		&i.SearchDepth,
		&i.KbContextLimit,
		&i.IncludeHistoryCount,
		&i.ThinkingEnabled,
		&i.ThinkingStyle,
		&i.CustomSystemPrompt,
		&i.PreferredModel,
		&i.AutoLoadKbCategories,
		&i.KeyboardShortcut,
		&i.IsFavorite,
		&i.UseCount,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateFocusContextPreset = `-- name: UpdateFocusContextPreset :one
UPDATE focus_context_presets SET
    name = COALESCE($3, name),
    description = COALESCE($4, description),
    kb_artifact_ids = COALESCE($5, kb_artifact_ids),
    kb_categories = COALESCE($6, kb_categories),
    project_ids = COALESCE($7, project_ids),
    default_search_queries = COALESCE($8, default_search_queries),
    search_domains = COALESCE($9, search_domains),
    updated_at = NOW()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, name, description, kb_artifact_ids, kb_categories, project_ids, default_search_queries, search_domains, created_at, updated_at
`

type UpdateFocusContextPresetParams struct {
	ID                   pgtype.UUID   `json:"id"`
	UserID               string        `json:"user_id"`
	Name                 string        `json:"name"`
	Description          *string       `json:"description"`
	KbArtifactIds        []pgtype.UUID `json:"kb_artifact_ids"`
	KbCategories         []string      `json:"kb_categories"`
	ProjectIds           []pgtype.UUID `json:"project_ids"`
	DefaultSearchQueries []string      `json:"default_search_queries"`
	SearchDomains        []string      `json:"search_domains"`
}

func (q *Queries) UpdateFocusContextPreset(ctx context.Context, arg UpdateFocusContextPresetParams) (FocusContextPreset, error) {
	row := q.db.QueryRow(ctx, updateFocusContextPreset,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Description,
		arg.KbArtifactIds,
		arg.KbCategories,
		arg.ProjectIds,
		arg.DefaultSearchQueries,
		arg.SearchDomains,
	)
	var i FocusContextPreset
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.KbArtifactIds,
		&i.KbCategories,
		&i.ProjectIds,
		&i.DefaultSearchQueries,
		&i.SearchDomains,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
