// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: optimal_signals.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOptimalDecisionLog = `-- name: CreateOptimalDecisionLog :one

INSERT INTO optimal_decision_log (workspace_id, actor, action, target_type, target_id, what_changed, why, alternatives_considered, context)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, workspace_id, actor, action, target_type, target_id, what_changed, why, alternatives_considered, context, created_at
`

type CreateOptimalDecisionLogParams struct {
	WorkspaceID            pgtype.UUID `json:"workspace_id"`
	Actor                  string      `json:"actor"`
	Action                 string      `json:"action"`
	TargetType             string      `json:"target_type"`
	TargetID               pgtype.UUID `json:"target_id"`
	WhatChanged            string      `json:"what_changed"`
	Why                    *string     `json:"why"`
	AlternativesConsidered []byte      `json:"alternatives_considered"`
	Context                []byte      `json:"context"`
}

// ===== DECISION LOG =====
func (q *Queries) CreateOptimalDecisionLog(ctx context.Context, arg CreateOptimalDecisionLogParams) (OptimalDecisionLog, error) {
	row := q.db.QueryRow(ctx, createOptimalDecisionLog,
		arg.WorkspaceID,
		arg.Actor,
		arg.Action,
		arg.TargetType,
		arg.TargetID,
		arg.WhatChanged,
		arg.Why,
		arg.AlternativesConsidered,
		arg.Context,
	)
	var i OptimalDecisionLog
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Actor,
		&i.Action,
		&i.TargetType,
		&i.TargetID,
		&i.WhatChanged,
		&i.Why,
		&i.AlternativesConsidered,
		&i.Context,
		&i.CreatedAt,
	)
	return i, err
}

const createOptimalEdge = `-- name: CreateOptimalEdge :one

INSERT INTO optimal_edges (workspace_id, source_id, source_type, target_id, target_type, relation, weight, reason)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (workspace_id, source_id, target_id, relation) DO UPDATE
SET weight = EXCLUDED.weight, valid_from = NOW()
RETURNING id, workspace_id, source_id, source_type, target_id, target_type, relation, weight, valid_from, valid_until, reason, metadata, created_at
`

type CreateOptimalEdgeParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	SourceID    pgtype.UUID `json:"source_id"`
	SourceType  string      `json:"source_type"`
	TargetID    pgtype.UUID `json:"target_id"`
	TargetType  string      `json:"target_type"`
	Relation    string      `json:"relation"`
	Weight      float32     `json:"weight"`
	Reason      *string     `json:"reason"`
}

// ===== EDGES (KNOWLEDGE GRAPH) =====
func (q *Queries) CreateOptimalEdge(ctx context.Context, arg CreateOptimalEdgeParams) (OptimalEdge, error) {
	row := q.db.QueryRow(ctx, createOptimalEdge,
		arg.WorkspaceID,
		arg.SourceID,
		arg.SourceType,
		arg.TargetID,
		arg.TargetType,
		arg.Relation,
		arg.Weight,
		arg.Reason,
	)
	var i OptimalEdge
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.SourceID,
		&i.SourceType,
		&i.TargetID,
		&i.TargetType,
		&i.Relation,
		&i.Weight,
		&i.ValidFrom,
		&i.ValidUntil,
		&i.Reason,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const createOptimalObservation = `-- name: CreateOptimalObservation :one

INSERT INTO optimal_observations (workspace_id, created_by, category, content, confidence, source)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, workspace_id, created_by, category, content, confidence, source, created_at
`

type CreateOptimalObservationParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	CreatedBy   string      `json:"created_by"`
	Category    string      `json:"category"`
	Content     string      `json:"content"`
	Confidence  float32     `json:"confidence"`
	Source      string      `json:"source"`
}

// ===== OBSERVATIONS (LEARNING LOOP) =====
func (q *Queries) CreateOptimalObservation(ctx context.Context, arg CreateOptimalObservationParams) (OptimalObservation, error) {
	row := q.db.QueryRow(ctx, createOptimalObservation,
		arg.WorkspaceID,
		arg.CreatedBy,
		arg.Category,
		arg.Content,
		arg.Confidence,
		arg.Source,
	)
	var i OptimalObservation
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.CreatedBy,
		&i.Category,
		&i.Content,
		&i.Confidence,
		&i.Source,
		&i.CreatedAt,
	)
	return i, err
}

const createOptimalSignal = `-- name: CreateOptimalSignal :one

INSERT INTO optimal_signals (
    workspace_id, node_id, created_by, title, slug, uri, path,
    content, mode, genre, signal_type, format, structure,
    sn_ratio, l0_abstract, l1_overview, primary_node, cross_ref_nodes,
    entities, valid_from, metadata
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13,
    $14, $15, $16, $17, $18, $19, $20, $21
) RETURNING id, workspace_id, node_id, created_by, title, slug, uri, path, content, mode, genre, signal_type, format, structure, sn_ratio, l0_abstract, l1_overview, primary_node, cross_ref_nodes, entities, valid_from, valid_until, supersedes, metadata, created_at, updated_at, indexed_at, search_vector
`

type CreateOptimalSignalParams struct {
	WorkspaceID   pgtype.UUID        `json:"workspace_id"`
	NodeID        pgtype.UUID        `json:"node_id"`
	CreatedBy     string             `json:"created_by"`
	Title         string             `json:"title"`
	Slug          string             `json:"slug"`
	Uri           string             `json:"uri"`
	Path          string             `json:"path"`
	Content       string             `json:"content"`
	Mode          string             `json:"mode"`
	Genre         string             `json:"genre"`
	SignalType    string             `json:"signal_type"`
	Format        string             `json:"format"`
	Structure     string             `json:"structure"`
	SnRatio       float32            `json:"sn_ratio"`
	L0Abstract    string             `json:"l0_abstract"`
	L1Overview    string             `json:"l1_overview"`
	PrimaryNode   string             `json:"primary_node"`
	CrossRefNodes []byte             `json:"cross_ref_nodes"`
	Entities      []byte             `json:"entities"`
	ValidFrom     pgtype.Timestamptz `json:"valid_from"`
	Metadata      []byte             `json:"metadata"`
}

// ===== SIGNALS CRUD =====
func (q *Queries) CreateOptimalSignal(ctx context.Context, arg CreateOptimalSignalParams) (OptimalSignal, error) {
	row := q.db.QueryRow(ctx, createOptimalSignal,
		arg.WorkspaceID,
		arg.NodeID,
		arg.CreatedBy,
		arg.Title,
		arg.Slug,
		arg.Uri,
		arg.Path,
		arg.Content,
		arg.Mode,
		arg.Genre,
		arg.SignalType,
		arg.Format,
		arg.Structure,
		arg.SnRatio,
		arg.L0Abstract,
		arg.L1Overview,
		arg.PrimaryNode,
		arg.CrossRefNodes,
		arg.Entities,
		arg.ValidFrom,
		arg.Metadata,
	)
	var i OptimalSignal
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.NodeID,
		&i.CreatedBy,
		&i.Title,
		&i.Slug,
		&i.Uri,
		&i.Path,
		&i.Content,
		&i.Mode,
		&i.Genre,
		&i.SignalType,
		&i.Format,
		&i.Structure,
		&i.SnRatio,
		&i.L0Abstract,
		&i.L1Overview,
		&i.PrimaryNode,
		&i.CrossRefNodes,
		&i.Entities,
		&i.ValidFrom,
		&i.ValidUntil,
		&i.Supersedes,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IndexedAt,
		&i.SearchVector,
	)
	return i, err
}

const deleteOptimalEdge = `-- name: DeleteOptimalEdge :exec
DELETE FROM optimal_edges
WHERE id = $1 AND workspace_id = $2
`

type DeleteOptimalEdgeParams struct {
	ID          pgtype.UUID `json:"id"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
}

func (q *Queries) DeleteOptimalEdge(ctx context.Context, arg DeleteOptimalEdgeParams) error {
	_, err := q.db.Exec(ctx, deleteOptimalEdge, arg.ID, arg.WorkspaceID)
	return err
}

const deleteOptimalEntity = `-- name: DeleteOptimalEntity :exec
DELETE FROM optimal_entities
WHERE id = $1 AND workspace_id = $2
`

type DeleteOptimalEntityParams struct {
	ID          pgtype.UUID `json:"id"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
}

func (q *Queries) DeleteOptimalEntity(ctx context.Context, arg DeleteOptimalEntityParams) error {
	_, err := q.db.Exec(ctx, deleteOptimalEntity, arg.ID, arg.WorkspaceID)
	return err
}

const deleteOptimalSignal = `-- name: DeleteOptimalSignal :exec
DELETE FROM optimal_signals
WHERE id = $1 AND workspace_id = $2
`

type DeleteOptimalSignalParams struct {
	ID          pgtype.UUID `json:"id"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
}

func (q *Queries) DeleteOptimalSignal(ctx context.Context, arg DeleteOptimalSignalParams) error {
	_, err := q.db.Exec(ctx, deleteOptimalSignal, arg.ID, arg.WorkspaceID)
	return err
}

const getOptimalDashboardStats = `-- name: GetOptimalDashboardStats :one

SELECT
    (SELECT COUNT(*) FROM optimal_signals WHERE workspace_id = v.wid AND valid_until IS NULL) AS signal_count,
    (SELECT COUNT(*) FROM optimal_entities WHERE workspace_id = v.wid) AS entity_count,
    (SELECT COUNT(*) FROM optimal_edges WHERE workspace_id = v.wid AND valid_until IS NULL) AS edge_count,
    (SELECT COUNT(*) FROM optimal_observations WHERE workspace_id = v.wid) AS observation_count,
    (SELECT COUNT(*) FROM optimal_sessions WHERE workspace_id = v.wid) AS session_count
FROM (VALUES ($1::uuid)) AS v(wid)
`

type GetOptimalDashboardStatsRow struct {
	SignalCount      int64 `json:"signal_count"`
	EntityCount      int64 `json:"entity_count"`
	EdgeCount        int64 `json:"edge_count"`
	ObservationCount int64 `json:"observation_count"`
	SessionCount     int64 `json:"session_count"`
}

// ===== DASHBOARD AGGREGATES =====
func (q *Queries) GetOptimalDashboardStats(ctx context.Context, dollar_1 pgtype.UUID) (GetOptimalDashboardStatsRow, error) {
	row := q.db.QueryRow(ctx, getOptimalDashboardStats, dollar_1)
	var i GetOptimalDashboardStatsRow
	err := row.Scan(
		&i.SignalCount,
		&i.EntityCount,
		&i.EdgeCount,
		&i.ObservationCount,
		&i.SessionCount,
	)
	return i, err
}

const getOptimalEdgesByEntity = `-- name: GetOptimalEdgesByEntity :many
SELECT id, workspace_id, source_id, source_type, target_id, target_type, relation, weight, valid_from, valid_until, reason, metadata, created_at FROM optimal_edges
WHERE workspace_id = $1
  AND (source_id = $2 OR target_id = $2)
  AND valid_until IS NULL
`

type GetOptimalEdgesByEntityParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	SourceID    pgtype.UUID `json:"source_id"`
}

func (q *Queries) GetOptimalEdgesByEntity(ctx context.Context, arg GetOptimalEdgesByEntityParams) ([]OptimalEdge, error) {
	rows, err := q.db.Query(ctx, getOptimalEdgesByEntity, arg.WorkspaceID, arg.SourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OptimalEdge{}
	for rows.Next() {
		var i OptimalEdge
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.SourceID,
			&i.SourceType,
			&i.TargetID,
			&i.TargetType,
			&i.Relation,
			&i.Weight,
			&i.ValidFrom,
			&i.ValidUntil,
			&i.Reason,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOptimalEntity = `-- name: GetOptimalEntity :one
SELECT id, workspace_id, name, canonical_name, type, properties, mention_count, first_seen, last_seen FROM optimal_entities
WHERE id = $1 AND workspace_id = $2
`

type GetOptimalEntityParams struct {
	ID          pgtype.UUID `json:"id"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
}

func (q *Queries) GetOptimalEntity(ctx context.Context, arg GetOptimalEntityParams) (OptimalEntity, error) {
	row := q.db.QueryRow(ctx, getOptimalEntity, arg.ID, arg.WorkspaceID)
	var i OptimalEntity
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.CanonicalName,
		&i.Type,
		&i.Properties,
		&i.MentionCount,
		&i.FirstSeen,
		&i.LastSeen,
	)
	return i, err
}

const getOptimalEscalations = `-- name: GetOptimalEscalations :many
SELECT category, COUNT(*) AS observation_count
FROM optimal_observations
WHERE workspace_id = $1
GROUP BY category
HAVING COUNT(*) >= 3
ORDER BY observation_count DESC
`

type GetOptimalEscalationsRow struct {
	Category         string `json:"category"`
	ObservationCount int64  `json:"observation_count"`
}

// Returns categories with 3 or more observations; signals patterns requiring escalation
func (q *Queries) GetOptimalEscalations(ctx context.Context, workspaceID pgtype.UUID) ([]GetOptimalEscalationsRow, error) {
	rows, err := q.db.Query(ctx, getOptimalEscalations, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetOptimalEscalationsRow{}
	for rows.Next() {
		var i GetOptimalEscalationsRow
		if err := rows.Scan(&i.Category, &i.ObservationCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOptimalGraphHubs = `-- name: GetOptimalGraphHubs :many
SELECT e.id, e.name, e.type, e.mention_count,
       COUNT(DISTINCT ed.id) AS connection_count
FROM optimal_entities e
LEFT JOIN optimal_edges ed ON (ed.source_id = e.id OR ed.target_id = e.id)
    AND ed.workspace_id = e.workspace_id
    AND ed.valid_until IS NULL
WHERE e.workspace_id = $1
GROUP BY e.id, e.name, e.type, e.mention_count
ORDER BY connection_count DESC
LIMIT $2
`

type GetOptimalGraphHubsParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	Limit       int32       `json:"limit"`
}

type GetOptimalGraphHubsRow struct {
	ID              pgtype.UUID `json:"id"`
	Name            string      `json:"name"`
	Type            string      `json:"type"`
	MentionCount    int32       `json:"mention_count"`
	ConnectionCount int64       `json:"connection_count"`
}

// Returns the most connected entities by total edge count
func (q *Queries) GetOptimalGraphHubs(ctx context.Context, arg GetOptimalGraphHubsParams) ([]GetOptimalGraphHubsRow, error) {
	rows, err := q.db.Query(ctx, getOptimalGraphHubs, arg.WorkspaceID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetOptimalGraphHubsRow{}
	for rows.Next() {
		var i GetOptimalGraphHubsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.MentionCount,
			&i.ConnectionCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOptimalRecentSignals = `-- name: GetOptimalRecentSignals :many
SELECT id, title, genre, mode, signal_type, sn_ratio, l0_abstract, primary_node, created_at
FROM optimal_signals
WHERE workspace_id = $1 AND valid_until IS NULL
ORDER BY created_at DESC
LIMIT $2
`

type GetOptimalRecentSignalsParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	Limit       int32       `json:"limit"`
}

type GetOptimalRecentSignalsRow struct {
	ID          pgtype.UUID        `json:"id"`
	Title       string             `json:"title"`
	Genre       string             `json:"genre"`
	Mode        string             `json:"mode"`
	SignalType  string             `json:"signal_type"`
	SnRatio     float32            `json:"sn_ratio"`
	L0Abstract  string             `json:"l0_abstract"`
	PrimaryNode string             `json:"primary_node"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetOptimalRecentSignals(ctx context.Context, arg GetOptimalRecentSignalsParams) ([]GetOptimalRecentSignalsRow, error) {
	rows, err := q.db.Query(ctx, getOptimalRecentSignals, arg.WorkspaceID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetOptimalRecentSignalsRow{}
	for rows.Next() {
		var i GetOptimalRecentSignalsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Genre,
			&i.Mode,
			&i.SignalType,
			&i.SnRatio,
			&i.L0Abstract,
			&i.PrimaryNode,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOptimalSignal = `-- name: GetOptimalSignal :one
SELECT id, workspace_id, node_id, created_by, title, slug, uri, path, content, mode, genre, signal_type, format, structure, sn_ratio, l0_abstract, l1_overview, primary_node, cross_ref_nodes, entities, valid_from, valid_until, supersedes, metadata, created_at, updated_at, indexed_at, search_vector FROM optimal_signals
WHERE id = $1 AND workspace_id = $2
`

type GetOptimalSignalParams struct {
	ID          pgtype.UUID `json:"id"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
}

func (q *Queries) GetOptimalSignal(ctx context.Context, arg GetOptimalSignalParams) (OptimalSignal, error) {
	row := q.db.QueryRow(ctx, getOptimalSignal, arg.ID, arg.WorkspaceID)
	var i OptimalSignal
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.NodeID,
		&i.CreatedBy,
		&i.Title,
		&i.Slug,
		&i.Uri,
		&i.Path,
		&i.Content,
		&i.Mode,
		&i.Genre,
		&i.SignalType,
		&i.Format,
		&i.Structure,
		&i.SnRatio,
		&i.L0Abstract,
		&i.L1Overview,
		&i.PrimaryNode,
		&i.CrossRefNodes,
		&i.Entities,
		&i.ValidFrom,
		&i.ValidUntil,
		&i.Supersedes,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IndexedAt,
		&i.SearchVector,
	)
	return i, err
}

const getOptimalSignalsByGenre = `-- name: GetOptimalSignalsByGenre :many
SELECT genre, COUNT(*) AS count
FROM optimal_signals
WHERE workspace_id = $1 AND valid_until IS NULL
GROUP BY genre
ORDER BY count DESC
`

type GetOptimalSignalsByGenreRow struct {
	Genre string `json:"genre"`
	Count int64  `json:"count"`
}

func (q *Queries) GetOptimalSignalsByGenre(ctx context.Context, workspaceID pgtype.UUID) ([]GetOptimalSignalsByGenreRow, error) {
	rows, err := q.db.Query(ctx, getOptimalSignalsByGenre, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetOptimalSignalsByGenreRow{}
	for rows.Next() {
		var i GetOptimalSignalsByGenreRow
		if err := rows.Scan(&i.Genre, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOptimalTopology = `-- name: GetOptimalTopology :one

SELECT id, workspace_id, config, genre_skeletons, genre_half_lives, created_at, updated_at FROM optimal_topology
WHERE workspace_id = $1
`

// ===== TOPOLOGY =====
func (q *Queries) GetOptimalTopology(ctx context.Context, workspaceID pgtype.UUID) (OptimalTopology, error) {
	row := q.db.QueryRow(ctx, getOptimalTopology, workspaceID)
	var i OptimalTopology
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Config,
		&i.GenreSkeletons,
		&i.GenreHalfLives,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listOptimalDecisionLog = `-- name: ListOptimalDecisionLog :many
SELECT id, workspace_id, actor, action, target_type, target_id, what_changed, why, alternatives_considered, context, created_at FROM optimal_decision_log
WHERE workspace_id = $1
  AND ($3::text IS NULL OR target_type = $3)
ORDER BY created_at DESC
LIMIT $2
`

type ListOptimalDecisionLogParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	Limit       int32       `json:"limit"`
	TargetType  *string     `json:"target_type"`
}

func (q *Queries) ListOptimalDecisionLog(ctx context.Context, arg ListOptimalDecisionLogParams) ([]OptimalDecisionLog, error) {
	rows, err := q.db.Query(ctx, listOptimalDecisionLog, arg.WorkspaceID, arg.Limit, arg.TargetType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OptimalDecisionLog{}
	for rows.Next() {
		var i OptimalDecisionLog
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Actor,
			&i.Action,
			&i.TargetType,
			&i.TargetID,
			&i.WhatChanged,
			&i.Why,
			&i.AlternativesConsidered,
			&i.Context,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOptimalEdges = `-- name: ListOptimalEdges :many
SELECT id, workspace_id, source_id, source_type, target_id, target_type, relation, weight, valid_from, valid_until, reason, metadata, created_at FROM optimal_edges
WHERE workspace_id = $1
  AND valid_until IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListOptimalEdges(ctx context.Context, workspaceID pgtype.UUID) ([]OptimalEdge, error) {
	rows, err := q.db.Query(ctx, listOptimalEdges, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OptimalEdge{}
	for rows.Next() {
		var i OptimalEdge
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.SourceID,
			&i.SourceType,
			&i.TargetID,
			&i.TargetType,
			&i.Relation,
			&i.Weight,
			&i.ValidFrom,
			&i.ValidUntil,
			&i.Reason,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOptimalEntities = `-- name: ListOptimalEntities :many
SELECT id, workspace_id, name, canonical_name, type, properties, mention_count, first_seen, last_seen FROM optimal_entities
WHERE workspace_id = $1
  AND ($3::text IS NULL OR type = $3)
ORDER BY mention_count DESC
LIMIT $2
`

type ListOptimalEntitiesParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	Limit       int32       `json:"limit"`
	Type        *string     `json:"type"`
}

func (q *Queries) ListOptimalEntities(ctx context.Context, arg ListOptimalEntitiesParams) ([]OptimalEntity, error) {
	rows, err := q.db.Query(ctx, listOptimalEntities, arg.WorkspaceID, arg.Limit, arg.Type)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OptimalEntity{}
	for rows.Next() {
		var i OptimalEntity
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.CanonicalName,
			&i.Type,
			&i.Properties,
			&i.MentionCount,
			&i.FirstSeen,
			&i.LastSeen,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOptimalObservations = `-- name: ListOptimalObservations :many
SELECT id, workspace_id, created_by, category, content, confidence, source, created_at FROM optimal_observations
WHERE workspace_id = $1
  AND ($2::text IS NULL OR category = $2)
ORDER BY created_at DESC
`

type ListOptimalObservationsParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	Category    *string     `json:"category"`
}

func (q *Queries) ListOptimalObservations(ctx context.Context, arg ListOptimalObservationsParams) ([]OptimalObservation, error) {
	rows, err := q.db.Query(ctx, listOptimalObservations, arg.WorkspaceID, arg.Category)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OptimalObservation{}
	for rows.Next() {
		var i OptimalObservation
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.CreatedBy,
			&i.Category,
			&i.Content,
			&i.Confidence,
			&i.Source,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOptimalSignals = `-- name: ListOptimalSignals :many
SELECT id, workspace_id, node_id, created_by, title, slug, uri, path, content, mode, genre, signal_type, format, structure, sn_ratio, l0_abstract, l1_overview, primary_node, cross_ref_nodes, entities, valid_from, valid_until, supersedes, metadata, created_at, updated_at, indexed_at, search_vector FROM optimal_signals
WHERE workspace_id = $1
  AND ($2::uuid IS NULL OR node_id = $2)
  AND ($3::text IS NULL OR genre = $3)
  AND ($4::text IS NULL OR mode = $4)
  AND valid_until IS NULL
ORDER BY created_at DESC
LIMIT $5::int
`

type ListOptimalSignalsParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	NodeID      pgtype.UUID `json:"node_id"`
	Genre       *string     `json:"genre"`
	Mode        *string     `json:"mode"`
	LimitVal    int32       `json:"limit_val"`
}

func (q *Queries) ListOptimalSignals(ctx context.Context, arg ListOptimalSignalsParams) ([]OptimalSignal, error) {
	rows, err := q.db.Query(ctx, listOptimalSignals,
		arg.WorkspaceID,
		arg.NodeID,
		arg.Genre,
		arg.Mode,
		arg.LimitVal,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OptimalSignal{}
	for rows.Next() {
		var i OptimalSignal
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.NodeID,
			&i.CreatedBy,
			&i.Title,
			&i.Slug,
			&i.Uri,
			&i.Path,
			&i.Content,
			&i.Mode,
			&i.Genre,
			&i.SignalType,
			&i.Format,
			&i.Structure,
			&i.SnRatio,
			&i.L0Abstract,
			&i.L1Overview,
			&i.PrimaryNode,
			&i.CrossRefNodes,
			&i.Entities,
			&i.ValidFrom,
			&i.ValidUntil,
			&i.Supersedes,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IndexedAt,
			&i.SearchVector,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOptimalSignalsByNode = `-- name: ListOptimalSignalsByNode :many
SELECT id, workspace_id, node_id, created_by, title, slug, uri, path, content, mode, genre, signal_type, format, structure, sn_ratio, l0_abstract, l1_overview, primary_node, cross_ref_nodes, entities, valid_from, valid_until, supersedes, metadata, created_at, updated_at, indexed_at, search_vector FROM optimal_signals
WHERE workspace_id = $1 AND node_id = $2
  AND valid_until IS NULL
ORDER BY created_at DESC
`

type ListOptimalSignalsByNodeParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	NodeID      pgtype.UUID `json:"node_id"`
}

func (q *Queries) ListOptimalSignalsByNode(ctx context.Context, arg ListOptimalSignalsByNodeParams) ([]OptimalSignal, error) {
	rows, err := q.db.Query(ctx, listOptimalSignalsByNode, arg.WorkspaceID, arg.NodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OptimalSignal{}
	for rows.Next() {
		var i OptimalSignal
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.NodeID,
			&i.CreatedBy,
			&i.Title,
			&i.Slug,
			&i.Uri,
			&i.Path,
			&i.Content,
			&i.Mode,
			&i.Genre,
			&i.SignalType,
			&i.Format,
			&i.Structure,
			&i.SnRatio,
			&i.L0Abstract,
			&i.L1Overview,
			&i.PrimaryNode,
			&i.CrossRefNodes,
			&i.Entities,
			&i.ValidFrom,
			&i.ValidUntil,
			&i.Supersedes,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IndexedAt,
			&i.SearchVector,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchOptimalSignals = `-- name: SearchOptimalSignals :many

SELECT id, workspace_id, node_id, title, slug, path,
       l0_abstract, l1_overview, genre, mode, signal_type, sn_ratio,
       primary_node, entities, created_at,
       ts_rank_cd(search_vector, websearch_to_tsquery('english', $2)) AS rank
FROM optimal_signals
WHERE workspace_id = $1
  AND search_vector @@ websearch_to_tsquery('english', $2)
  AND valid_until IS NULL
ORDER BY rank DESC
LIMIT $3
`

type SearchOptimalSignalsParams struct {
	WorkspaceID        pgtype.UUID `json:"workspace_id"`
	WebsearchToTsquery string      `json:"websearch_to_tsquery"`
	Limit              int32       `json:"limit"`
}

type SearchOptimalSignalsRow struct {
	ID          pgtype.UUID        `json:"id"`
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
	NodeID      pgtype.UUID        `json:"node_id"`
	Title       string             `json:"title"`
	Slug        string             `json:"slug"`
	Path        string             `json:"path"`
	L0Abstract  string             `json:"l0_abstract"`
	L1Overview  string             `json:"l1_overview"`
	Genre       string             `json:"genre"`
	Mode        string             `json:"mode"`
	SignalType  string             `json:"signal_type"`
	SnRatio     float32            `json:"sn_ratio"`
	PrimaryNode string             `json:"primary_node"`
	Entities    []byte             `json:"entities"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	Rank        float32            `json:"rank"`
}

// ===== FULL-TEXT SEARCH =====
func (q *Queries) SearchOptimalSignals(ctx context.Context, arg SearchOptimalSignalsParams) ([]SearchOptimalSignalsRow, error) {
	rows, err := q.db.Query(ctx, searchOptimalSignals, arg.WorkspaceID, arg.WebsearchToTsquery, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchOptimalSignalsRow{}
	for rows.Next() {
		var i SearchOptimalSignalsRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.NodeID,
			&i.Title,
			&i.Slug,
			&i.Path,
			&i.L0Abstract,
			&i.L1Overview,
			&i.Genre,
			&i.Mode,
			&i.SignalType,
			&i.SnRatio,
			&i.PrimaryNode,
			&i.Entities,
			&i.CreatedAt,
			&i.Rank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchOptimalSignalsByNode = `-- name: SearchOptimalSignalsByNode :many
SELECT id, workspace_id, node_id, title, slug, path,
       l0_abstract, l1_overview, genre, mode, signal_type, sn_ratio,
       primary_node, entities, created_at,
       ts_rank_cd(search_vector, websearch_to_tsquery('english', $3)) AS rank
FROM optimal_signals
WHERE workspace_id = $1
  AND node_id = $2
  AND search_vector @@ websearch_to_tsquery('english', $3)
  AND valid_until IS NULL
ORDER BY rank DESC
LIMIT $4
`

type SearchOptimalSignalsByNodeParams struct {
	WorkspaceID        pgtype.UUID `json:"workspace_id"`
	NodeID             pgtype.UUID `json:"node_id"`
	WebsearchToTsquery string      `json:"websearch_to_tsquery"`
	Limit              int32       `json:"limit"`
}

type SearchOptimalSignalsByNodeRow struct {
	ID          pgtype.UUID        `json:"id"`
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
	NodeID      pgtype.UUID        `json:"node_id"`
	Title       string             `json:"title"`
	Slug        string             `json:"slug"`
	Path        string             `json:"path"`
	L0Abstract  string             `json:"l0_abstract"`
	L1Overview  string             `json:"l1_overview"`
	Genre       string             `json:"genre"`
	Mode        string             `json:"mode"`
	SignalType  string             `json:"signal_type"`
	SnRatio     float32            `json:"sn_ratio"`
	PrimaryNode string             `json:"primary_node"`
	Entities    []byte             `json:"entities"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	Rank        float32            `json:"rank"`
}

func (q *Queries) SearchOptimalSignalsByNode(ctx context.Context, arg SearchOptimalSignalsByNodeParams) ([]SearchOptimalSignalsByNodeRow, error) {
	rows, err := q.db.Query(ctx, searchOptimalSignalsByNode,
		arg.WorkspaceID,
		arg.NodeID,
		arg.WebsearchToTsquery,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchOptimalSignalsByNodeRow{}
	for rows.Next() {
		var i SearchOptimalSignalsByNodeRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.NodeID,
			&i.Title,
			&i.Slug,
			&i.Path,
			&i.L0Abstract,
			&i.L1Overview,
			&i.Genre,
			&i.Mode,
			&i.SignalType,
			&i.SnRatio,
			&i.PrimaryNode,
			&i.Entities,
			&i.CreatedAt,
			&i.Rank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const supersedeOptimalSignal = `-- name: SupersedeOptimalSignal :exec
UPDATE optimal_signals
SET valid_until = NOW(), updated_at = NOW()
WHERE id = $1 AND workspace_id = $2
`

type SupersedeOptimalSignalParams struct {
	ID          pgtype.UUID `json:"id"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
}

// Marks a signal as superseded; a newer version should be created separately
func (q *Queries) SupersedeOptimalSignal(ctx context.Context, arg SupersedeOptimalSignalParams) error {
	_, err := q.db.Exec(ctx, supersedeOptimalSignal, arg.ID, arg.WorkspaceID)
	return err
}

const updateOptimalSignal = `-- name: UpdateOptimalSignal :one
UPDATE optimal_signals
SET title = $3, content = $4, l0_abstract = $5, l1_overview = $6,
    mode = $7, genre = $8, signal_type = $9, sn_ratio = $10,
    entities = $11, metadata = $12, updated_at = NOW()
WHERE id = $1 AND workspace_id = $2
RETURNING id, workspace_id, node_id, created_by, title, slug, uri, path, content, mode, genre, signal_type, format, structure, sn_ratio, l0_abstract, l1_overview, primary_node, cross_ref_nodes, entities, valid_from, valid_until, supersedes, metadata, created_at, updated_at, indexed_at, search_vector
`

type UpdateOptimalSignalParams struct {
	ID          pgtype.UUID `json:"id"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	Title       string      `json:"title"`
	Content     string      `json:"content"`
	L0Abstract  string      `json:"l0_abstract"`
	L1Overview  string      `json:"l1_overview"`
	Mode        string      `json:"mode"`
	Genre       string      `json:"genre"`
	SignalType  string      `json:"signal_type"`
	SnRatio     float32     `json:"sn_ratio"`
	Entities    []byte      `json:"entities"`
	Metadata    []byte      `json:"metadata"`
}

func (q *Queries) UpdateOptimalSignal(ctx context.Context, arg UpdateOptimalSignalParams) (OptimalSignal, error) {
	row := q.db.QueryRow(ctx, updateOptimalSignal,
		arg.ID,
		arg.WorkspaceID,
		arg.Title,
		arg.Content,
		arg.L0Abstract,
		arg.L1Overview,
		arg.Mode,
		arg.Genre,
		arg.SignalType,
		arg.SnRatio,
		arg.Entities,
		arg.Metadata,
	)
	var i OptimalSignal
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.NodeID,
		&i.CreatedBy,
		&i.Title,
		&i.Slug,
		&i.Uri,
		&i.Path,
		&i.Content,
		&i.Mode,
		&i.Genre,
		&i.SignalType,
		&i.Format,
		&i.Structure,
		&i.SnRatio,
		&i.L0Abstract,
		&i.L1Overview,
		&i.PrimaryNode,
		&i.CrossRefNodes,
		&i.Entities,
		&i.ValidFrom,
		&i.ValidUntil,
		&i.Supersedes,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IndexedAt,
		&i.SearchVector,
	)
	return i, err
}

const upsertOptimalEntity = `-- name: UpsertOptimalEntity :one

INSERT INTO optimal_entities (workspace_id, name, canonical_name, type, mention_count)
VALUES ($1, $2, LOWER($2), $3, 1)
ON CONFLICT (workspace_id, canonical_name)
DO UPDATE SET mention_count = optimal_entities.mention_count + 1,
              last_seen = NOW()
RETURNING id, workspace_id, name, canonical_name, type, properties, mention_count, first_seen, last_seen
`

type UpsertOptimalEntityParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	Name        string      `json:"name"`
	Type        string      `json:"type"`
}

// ===== ENTITIES =====
func (q *Queries) UpsertOptimalEntity(ctx context.Context, arg UpsertOptimalEntityParams) (OptimalEntity, error) {
	row := q.db.QueryRow(ctx, upsertOptimalEntity, arg.WorkspaceID, arg.Name, arg.Type)
	var i OptimalEntity
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.CanonicalName,
		&i.Type,
		&i.Properties,
		&i.MentionCount,
		&i.FirstSeen,
		&i.LastSeen,
	)
	return i, err
}

const upsertOptimalTopology = `-- name: UpsertOptimalTopology :one
INSERT INTO optimal_topology (workspace_id, config, genre_skeletons, genre_half_lives)
VALUES ($1, $2, $3, $4)
ON CONFLICT (workspace_id)
DO UPDATE SET config = $2, genre_skeletons = $3, genre_half_lives = $4, updated_at = NOW()
RETURNING id, workspace_id, config, genre_skeletons, genre_half_lives, created_at, updated_at
`

type UpsertOptimalTopologyParams struct {
	WorkspaceID    pgtype.UUID `json:"workspace_id"`
	Config         []byte      `json:"config"`
	GenreSkeletons []byte      `json:"genre_skeletons"`
	GenreHalfLives []byte      `json:"genre_half_lives"`
}

func (q *Queries) UpsertOptimalTopology(ctx context.Context, arg UpsertOptimalTopologyParams) (OptimalTopology, error) {
	row := q.db.QueryRow(ctx, upsertOptimalTopology,
		arg.WorkspaceID,
		arg.Config,
		arg.GenreSkeletons,
		arg.GenreHalfLives,
	)
	var i OptimalTopology
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Config,
		&i.GenreSkeletons,
		&i.GenreHalfLives,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
