// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: voice_sessions.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUserFact = `-- name: CreateUserFact :one
INSERT INTO user_facts (
    user_id,
    fact_type,
    fact_key,
    fact_value,
    confidence_score
) VALUES (
    $1, $2, $3, $4, $5
) ON CONFLICT (user_id, fact_key)
DO UPDATE SET
    fact_value = EXCLUDED.fact_value,
    confidence_score = EXCLUDED.confidence_score,
    last_confirmed_at = NOW(),
    updated_at = NOW()
RETURNING id, user_id, fact_key, fact_value, fact_type, source_memory_id, confidence_score, is_active, last_confirmed_at, created_at, updated_at
`

type CreateUserFactParams struct {
	UserID          string         `json:"user_id"`
	FactType        string         `json:"fact_type"`
	FactKey         string         `json:"fact_key"`
	FactValue       string         `json:"fact_value"`
	ConfidenceScore pgtype.Numeric `json:"confidence_score"`
}

// User Facts Queries (for context retrieval)
func (q *Queries) CreateUserFact(ctx context.Context, arg CreateUserFactParams) (UserFact, error) {
	row := q.db.QueryRow(ctx, createUserFact,
		arg.UserID,
		arg.FactType,
		arg.FactKey,
		arg.FactValue,
		arg.ConfidenceScore,
	)
	var i UserFact
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FactKey,
		&i.FactValue,
		&i.FactType,
		&i.SourceMemoryID,
		&i.ConfidenceScore,
		&i.IsActive,
		&i.LastConfirmedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createVoiceSession = `-- name: CreateVoiceSession :one
INSERT INTO voice_sessions (
    session_id,
    user_id,
    workspace_id,
    agent_role,
    state
) VALUES (
    $1, $2, $3, $4, 'active'
) RETURNING id, session_id, user_id, workspace_id, agent_role, state, last_activity_at, total_messages, total_duration_seconds, created_at, updated_at, ended_at
`

type CreateVoiceSessionParams struct {
	SessionID   string      `json:"session_id"`
	UserID      string      `json:"user_id"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	AgentRole   *string     `json:"agent_role"`
}

func (q *Queries) CreateVoiceSession(ctx context.Context, arg CreateVoiceSessionParams) (VoiceSession, error) {
	row := q.db.QueryRow(ctx, createVoiceSession,
		arg.SessionID,
		arg.UserID,
		arg.WorkspaceID,
		arg.AgentRole,
	)
	var i VoiceSession
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.UserID,
		&i.WorkspaceID,
		&i.AgentRole,
		&i.State,
		&i.LastActivityAt,
		&i.TotalMessages,
		&i.TotalDurationSeconds,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EndedAt,
	)
	return i, err
}

const createVoiceSessionEvent = `-- name: CreateVoiceSessionEvent :one
INSERT INTO voice_session_events (
    session_id,
    event_type,
    event_data,
    duration_ms,
    error_message
) VALUES (
    (SELECT vs.id FROM voice_sessions vs WHERE vs.session_id = $1),
    $2, $3, $4, $5
) RETURNING id, session_id, event_type, event_data, duration_ms, error_message, created_at
`

type CreateVoiceSessionEventParams struct {
	SessionID    string  `json:"session_id"`
	EventType    string  `json:"event_type"`
	EventData    []byte  `json:"event_data"`
	DurationMs   *int32  `json:"duration_ms"`
	ErrorMessage *string `json:"error_message"`
}

// Voice Session Events Queries
func (q *Queries) CreateVoiceSessionEvent(ctx context.Context, arg CreateVoiceSessionEventParams) (VoiceSessionEvent, error) {
	row := q.db.QueryRow(ctx, createVoiceSessionEvent,
		arg.SessionID,
		arg.EventType,
		arg.EventData,
		arg.DurationMs,
		arg.ErrorMessage,
	)
	var i VoiceSessionEvent
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.EventType,
		&i.EventData,
		&i.DurationMs,
		&i.ErrorMessage,
		&i.CreatedAt,
	)
	return i, err
}

const deleteUserFact = `-- name: DeleteUserFact :exec
DELETE FROM user_facts
WHERE id = $1
`

func (q *Queries) DeleteUserFact(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteUserFact, id)
	return err
}

const deleteUserFactByKey = `-- name: DeleteUserFactByKey :exec
DELETE FROM user_facts
WHERE user_id = $1 AND fact_key = $2
`

type DeleteUserFactByKeyParams struct {
	UserID  string `json:"user_id"`
	FactKey string `json:"fact_key"`
}

func (q *Queries) DeleteUserFactByKey(ctx context.Context, arg DeleteUserFactByKeyParams) error {
	_, err := q.db.Exec(ctx, deleteUserFactByKey, arg.UserID, arg.FactKey)
	return err
}

const deleteVoiceSession = `-- name: DeleteVoiceSession :exec
DELETE FROM voice_sessions
WHERE session_id = $1
`

func (q *Queries) DeleteVoiceSession(ctx context.Context, sessionID string) error {
	_, err := q.db.Exec(ctx, deleteVoiceSession, sessionID)
	return err
}

const deleteVoiceSessionByID = `-- name: DeleteVoiceSessionByID :exec
DELETE FROM voice_sessions
WHERE id = $1
`

func (q *Queries) DeleteVoiceSessionByID(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteVoiceSessionByID, id)
	return err
}

const getUserFactByKey = `-- name: GetUserFactByKey :one
SELECT id, user_id, fact_key, fact_value, fact_type, source_memory_id, confidence_score, is_active, last_confirmed_at, created_at, updated_at FROM user_facts
WHERE user_id = $1
    AND fact_key = $2
    AND is_active = TRUE
`

type GetUserFactByKeyParams struct {
	UserID  string `json:"user_id"`
	FactKey string `json:"fact_key"`
}

func (q *Queries) GetUserFactByKey(ctx context.Context, arg GetUserFactByKeyParams) (UserFact, error) {
	row := q.db.QueryRow(ctx, getUserFactByKey, arg.UserID, arg.FactKey)
	var i UserFact
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FactKey,
		&i.FactValue,
		&i.FactType,
		&i.SourceMemoryID,
		&i.ConfidenceScore,
		&i.IsActive,
		&i.LastConfirmedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserFactsByType = `-- name: GetUserFactsByType :many
SELECT id, user_id, fact_key, fact_value, fact_type, source_memory_id, confidence_score, is_active, last_confirmed_at, created_at, updated_at FROM user_facts
WHERE user_id = $1
    AND fact_type = $2
    AND is_active = TRUE
ORDER BY confidence_score DESC
`

type GetUserFactsByTypeParams struct {
	UserID   string `json:"user_id"`
	FactType string `json:"fact_type"`
}

func (q *Queries) GetUserFactsByType(ctx context.Context, arg GetUserFactsByTypeParams) ([]UserFact, error) {
	rows, err := q.db.Query(ctx, getUserFactsByType, arg.UserID, arg.FactType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserFact{}
	for rows.Next() {
		var i UserFact
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.FactKey,
			&i.FactValue,
			&i.FactType,
			&i.SourceMemoryID,
			&i.ConfidenceScore,
			&i.IsActive,
			&i.LastConfirmedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserFactsByUser = `-- name: GetUserFactsByUser :many
SELECT id, user_id, fact_key, fact_value, fact_type, source_memory_id, confidence_score, is_active, last_confirmed_at, created_at, updated_at FROM user_facts
WHERE user_id = $1 AND is_active = TRUE
ORDER BY confidence_score DESC, created_at DESC
`

func (q *Queries) GetUserFactsByUser(ctx context.Context, userID string) ([]UserFact, error) {
	rows, err := q.db.Query(ctx, getUserFactsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserFact{}
	for rows.Next() {
		var i UserFact
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.FactKey,
			&i.FactValue,
			&i.FactType,
			&i.SourceMemoryID,
			&i.ConfidenceScore,
			&i.IsActive,
			&i.LastConfirmedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getVoiceSessionByID = `-- name: GetVoiceSessionByID :one
SELECT id, session_id, user_id, workspace_id, agent_role, state, last_activity_at, total_messages, total_duration_seconds, created_at, updated_at, ended_at FROM voice_sessions
WHERE id = $1
`

func (q *Queries) GetVoiceSessionByID(ctx context.Context, id pgtype.UUID) (VoiceSession, error) {
	row := q.db.QueryRow(ctx, getVoiceSessionByID, id)
	var i VoiceSession
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.UserID,
		&i.WorkspaceID,
		&i.AgentRole,
		&i.State,
		&i.LastActivityAt,
		&i.TotalMessages,
		&i.TotalDurationSeconds,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EndedAt,
	)
	return i, err
}

const getVoiceSessionBySessionID = `-- name: GetVoiceSessionBySessionID :one
SELECT id, session_id, user_id, workspace_id, agent_role, state, last_activity_at, total_messages, total_duration_seconds, created_at, updated_at, ended_at FROM voice_sessions
WHERE session_id = $1
`

func (q *Queries) GetVoiceSessionBySessionID(ctx context.Context, sessionID string) (VoiceSession, error) {
	row := q.db.QueryRow(ctx, getVoiceSessionBySessionID, sessionID)
	var i VoiceSession
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.UserID,
		&i.WorkspaceID,
		&i.AgentRole,
		&i.State,
		&i.LastActivityAt,
		&i.TotalMessages,
		&i.TotalDurationSeconds,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EndedAt,
	)
	return i, err
}

const getVoiceSessionBySessionIDAndUser = `-- name: GetVoiceSessionBySessionIDAndUser :one
SELECT id, session_id, user_id, workspace_id, agent_role, state, last_activity_at, total_messages, total_duration_seconds, created_at, updated_at, ended_at FROM voice_sessions
WHERE session_id = $1 AND user_id = $2
`

type GetVoiceSessionBySessionIDAndUserParams struct {
	SessionID string `json:"session_id"`
	UserID    string `json:"user_id"`
}

func (q *Queries) GetVoiceSessionBySessionIDAndUser(ctx context.Context, arg GetVoiceSessionBySessionIDAndUserParams) (VoiceSession, error) {
	row := q.db.QueryRow(ctx, getVoiceSessionBySessionIDAndUser, arg.SessionID, arg.UserID)
	var i VoiceSession
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.UserID,
		&i.WorkspaceID,
		&i.AgentRole,
		&i.State,
		&i.LastActivityAt,
		&i.TotalMessages,
		&i.TotalDurationSeconds,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EndedAt,
	)
	return i, err
}

const getVoiceSessionEventStats = `-- name: GetVoiceSessionEventStats :one
SELECT
    COUNT(*) as total_events,
    COUNT(*) FILTER (WHERE event_type = 'error') as error_count,
    AVG(duration_ms) FILTER (WHERE duration_ms IS NOT NULL) as avg_duration_ms,
    MAX(created_at) as last_event_at
FROM voice_session_events vse
JOIN voice_sessions vs ON vse.session_id = vs.id
WHERE vs.session_id = $1
`

type GetVoiceSessionEventStatsRow struct {
	TotalEvents   int64       `json:"total_events"`
	ErrorCount    int64       `json:"error_count"`
	AvgDurationMs float64     `json:"avg_duration_ms"`
	LastEventAt   interface{} `json:"last_event_at"`
}

func (q *Queries) GetVoiceSessionEventStats(ctx context.Context, sessionID string) (GetVoiceSessionEventStatsRow, error) {
	row := q.db.QueryRow(ctx, getVoiceSessionEventStats, sessionID)
	var i GetVoiceSessionEventStatsRow
	err := row.Scan(
		&i.TotalEvents,
		&i.ErrorCount,
		&i.AvgDurationMs,
		&i.LastEventAt,
	)
	return i, err
}

const listActiveVoiceSessionsForUser = `-- name: ListActiveVoiceSessionsForUser :many
SELECT id, session_id, user_id, workspace_id, agent_role, state, last_activity_at, total_messages, total_duration_seconds, created_at, updated_at, ended_at FROM voice_sessions
WHERE user_id = $1 AND state = 'active'
ORDER BY created_at DESC
LIMIT $2
`

type ListActiveVoiceSessionsForUserParams struct {
	UserID string `json:"user_id"`
	Limit  int32  `json:"limit"`
}

func (q *Queries) ListActiveVoiceSessionsForUser(ctx context.Context, arg ListActiveVoiceSessionsForUserParams) ([]VoiceSession, error) {
	rows, err := q.db.Query(ctx, listActiveVoiceSessionsForUser, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VoiceSession{}
	for rows.Next() {
		var i VoiceSession
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.UserID,
			&i.WorkspaceID,
			&i.AgentRole,
			&i.State,
			&i.LastActivityAt,
			&i.TotalMessages,
			&i.TotalDurationSeconds,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EndedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVoiceSessionEvents = `-- name: ListVoiceSessionEvents :many
SELECT vse.id, vse.session_id, vse.event_type, vse.event_data, vse.duration_ms, vse.error_message, vse.created_at
FROM voice_session_events vse
JOIN voice_sessions vs ON vse.session_id = vs.id
WHERE vs.session_id = $3
ORDER BY vse.created_at DESC
LIMIT $1 OFFSET $2
`

type ListVoiceSessionEventsParams struct {
	Limit           int32  `json:"limit"`
	Offset          int32  `json:"offset"`
	TargetSessionID string `json:"target_session_id"`
}

func (q *Queries) ListVoiceSessionEvents(ctx context.Context, arg ListVoiceSessionEventsParams) ([]VoiceSessionEvent, error) {
	rows, err := q.db.Query(ctx, listVoiceSessionEvents, arg.Limit, arg.Offset, arg.TargetSessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VoiceSessionEvent{}
	for rows.Next() {
		var i VoiceSessionEvent
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.EventType,
			&i.EventData,
			&i.DurationMs,
			&i.ErrorMessage,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVoiceSessionsForWorkspace = `-- name: ListVoiceSessionsForWorkspace :many
SELECT id, session_id, user_id, workspace_id, agent_role, state, last_activity_at, total_messages, total_duration_seconds, created_at, updated_at, ended_at FROM voice_sessions
WHERE workspace_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListVoiceSessionsForWorkspaceParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	Limit       int32       `json:"limit"`
	Offset      int32       `json:"offset"`
}

func (q *Queries) ListVoiceSessionsForWorkspace(ctx context.Context, arg ListVoiceSessionsForWorkspaceParams) ([]VoiceSession, error) {
	rows, err := q.db.Query(ctx, listVoiceSessionsForWorkspace, arg.WorkspaceID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VoiceSession{}
	for rows.Next() {
		var i VoiceSession
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.UserID,
			&i.WorkspaceID,
			&i.AgentRole,
			&i.State,
			&i.LastActivityAt,
			&i.TotalMessages,
			&i.TotalDurationSeconds,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EndedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateVoiceSessionActivity = `-- name: UpdateVoiceSessionActivity :exec
UPDATE voice_sessions
SET last_activity_at = NOW(),
    total_messages = total_messages + 1
WHERE session_id = $1
`

func (q *Queries) UpdateVoiceSessionActivity(ctx context.Context, sessionID string) error {
	_, err := q.db.Exec(ctx, updateVoiceSessionActivity, sessionID)
	return err
}

const updateVoiceSessionDuration = `-- name: UpdateVoiceSessionDuration :exec
UPDATE voice_sessions
SET total_duration_seconds = $2,
    last_activity_at = NOW()
WHERE session_id = $1
`

type UpdateVoiceSessionDurationParams struct {
	SessionID            string `json:"session_id"`
	TotalDurationSeconds *int32 `json:"total_duration_seconds"`
}

func (q *Queries) UpdateVoiceSessionDuration(ctx context.Context, arg UpdateVoiceSessionDurationParams) error {
	_, err := q.db.Exec(ctx, updateVoiceSessionDuration, arg.SessionID, arg.TotalDurationSeconds)
	return err
}

const updateVoiceSessionState = `-- name: UpdateVoiceSessionState :exec
UPDATE voice_sessions
SET state = $2,
    ended_at = CASE
        WHEN $2 = 'ended' THEN NOW()
        ELSE ended_at
    END,
    last_activity_at = NOW()
WHERE session_id = $1
`

type UpdateVoiceSessionStateParams struct {
	SessionID string  `json:"session_id"`
	State     *string `json:"state"`
}

func (q *Queries) UpdateVoiceSessionState(ctx context.Context, arg UpdateVoiceSessionStateParams) error {
	_, err := q.db.Exec(ctx, updateVoiceSessionState, arg.SessionID, arg.State)
	return err
}
