// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: web_search_cache.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cleanupExpiredCache = `-- name: CleanupExpiredCache :execrows
DELETE FROM web_search_results WHERE expires_at < NOW()
`

func (q *Queries) CleanupExpiredCache(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, cleanupExpiredCache)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteCacheForConversation = `-- name: DeleteCacheForConversation :exec
DELETE FROM web_search_results WHERE conversation_id = $1
`

func (q *Queries) DeleteCacheForConversation(ctx context.Context, conversationID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteCacheForConversation, conversationID)
	return err
}

const deleteCacheForUser = `-- name: DeleteCacheForUser :exec
DELETE FROM web_search_results WHERE user_id = $1
`

func (q *Queries) DeleteCacheForUser(ctx context.Context, userID *string) error {
	_, err := q.db.Exec(ctx, deleteCacheForUser, userID)
	return err
}

const getCacheStats = `-- name: GetCacheStats :one
SELECT
    COUNT(*) as total_entries,
    COUNT(*) FILTER (WHERE expires_at > NOW()) as active_entries,
    COALESCE(SUM(hit_count), 0) as total_hits,
    COALESCE(AVG(search_time_ms), 0) as avg_search_time_ms
FROM web_search_results
`

type GetCacheStatsRow struct {
	TotalEntries    int64       `json:"total_entries"`
	ActiveEntries   int64       `json:"active_entries"`
	TotalHits       interface{} `json:"total_hits"`
	AvgSearchTimeMs interface{} `json:"avg_search_time_ms"`
}

func (q *Queries) GetCacheStats(ctx context.Context) (GetCacheStatsRow, error) {
	row := q.db.QueryRow(ctx, getCacheStats)
	var i GetCacheStatsRow
	err := row.Scan(
		&i.TotalEntries,
		&i.ActiveEntries,
		&i.TotalHits,
		&i.AvgSearchTimeMs,
	)
	return i, err
}

const getCachedSearchResult = `-- name: GetCachedSearchResult :one
SELECT id, query_hash, original_query, optimized_query, user_id, conversation_id, results, result_count, provider, search_time_ms, expires_at, hit_count, last_hit_at, created_at FROM web_search_results
WHERE query_hash = $1 AND expires_at > NOW()
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetCachedSearchResult(ctx context.Context, queryHash string) (WebSearchResult, error) {
	row := q.db.QueryRow(ctx, getCachedSearchResult, queryHash)
	var i WebSearchResult
	err := row.Scan(
		&i.ID,
		&i.QueryHash,
		&i.OriginalQuery,
		&i.OptimizedQuery,
		&i.UserID,
		&i.ConversationID,
		&i.Results,
		&i.ResultCount,
		&i.Provider,
		&i.SearchTimeMs,
		&i.ExpiresAt,
		&i.HitCount,
		&i.LastHitAt,
		&i.CreatedAt,
	)
	return i, err
}

const getCachedSearchResultForConversation = `-- name: GetCachedSearchResultForConversation :one
SELECT id, query_hash, original_query, optimized_query, user_id, conversation_id, results, result_count, provider, search_time_ms, expires_at, hit_count, last_hit_at, created_at FROM web_search_results
WHERE query_hash = $1 AND conversation_id = $2 AND expires_at > NOW()
ORDER BY created_at DESC
LIMIT 1
`

type GetCachedSearchResultForConversationParams struct {
	QueryHash      string      `json:"query_hash"`
	ConversationID pgtype.UUID `json:"conversation_id"`
}

func (q *Queries) GetCachedSearchResultForConversation(ctx context.Context, arg GetCachedSearchResultForConversationParams) (WebSearchResult, error) {
	row := q.db.QueryRow(ctx, getCachedSearchResultForConversation, arg.QueryHash, arg.ConversationID)
	var i WebSearchResult
	err := row.Scan(
		&i.ID,
		&i.QueryHash,
		&i.OriginalQuery,
		&i.OptimizedQuery,
		&i.UserID,
		&i.ConversationID,
		&i.Results,
		&i.ResultCount,
		&i.Provider,
		&i.SearchTimeMs,
		&i.ExpiresAt,
		&i.HitCount,
		&i.LastHitAt,
		&i.CreatedAt,
	)
	return i, err
}

const getSearchHistoryCount = `-- name: GetSearchHistoryCount :one
SELECT COUNT(*) FROM web_search_results WHERE user_id = $1
`

func (q *Queries) GetSearchHistoryCount(ctx context.Context, userID *string) (int64, error) {
	row := q.db.QueryRow(ctx, getSearchHistoryCount, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getSearchResultById = `-- name: GetSearchResultById :one
SELECT id, query_hash, original_query, optimized_query, user_id, conversation_id, results, result_count, provider, search_time_ms, expires_at, hit_count, last_hit_at, created_at FROM web_search_results WHERE id = $1 AND user_id = $2
`

type GetSearchResultByIdParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID *string     `json:"user_id"`
}

func (q *Queries) GetSearchResultById(ctx context.Context, arg GetSearchResultByIdParams) (WebSearchResult, error) {
	row := q.db.QueryRow(ctx, getSearchResultById, arg.ID, arg.UserID)
	var i WebSearchResult
	err := row.Scan(
		&i.ID,
		&i.QueryHash,
		&i.OriginalQuery,
		&i.OptimizedQuery,
		&i.UserID,
		&i.ConversationID,
		&i.Results,
		&i.ResultCount,
		&i.Provider,
		&i.SearchTimeMs,
		&i.ExpiresAt,
		&i.HitCount,
		&i.LastHitAt,
		&i.CreatedAt,
	)
	return i, err
}

const incrementCacheHit = `-- name: IncrementCacheHit :exec
UPDATE web_search_results
SET hit_count = hit_count + 1, last_hit_at = NOW()
WHERE id = $1
`

func (q *Queries) IncrementCacheHit(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, incrementCacheHit, id)
	return err
}

const listSearchHistory = `-- name: ListSearchHistory :many
SELECT id, original_query, optimized_query, result_count, provider, search_time_ms, created_at
FROM web_search_results
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListSearchHistoryParams struct {
	UserID *string `json:"user_id"`
	Limit  int32   `json:"limit"`
	Offset int32   `json:"offset"`
}

type ListSearchHistoryRow struct {
	ID             pgtype.UUID        `json:"id"`
	OriginalQuery  string             `json:"original_query"`
	OptimizedQuery *string            `json:"optimized_query"`
	ResultCount    *int32             `json:"result_count"`
	Provider       *string            `json:"provider"`
	SearchTimeMs   *float64           `json:"search_time_ms"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListSearchHistory(ctx context.Context, arg ListSearchHistoryParams) ([]ListSearchHistoryRow, error) {
	rows, err := q.db.Query(ctx, listSearchHistory, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSearchHistoryRow{}
	for rows.Next() {
		var i ListSearchHistoryRow
		if err := rows.Scan(
			&i.ID,
			&i.OriginalQuery,
			&i.OptimizedQuery,
			&i.ResultCount,
			&i.Provider,
			&i.SearchTimeMs,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveSearchResult = `-- name: SaveSearchResult :one
INSERT INTO web_search_results (
    query_hash,
    original_query,
    optimized_query,
    user_id,
    conversation_id,
    results,
    result_count,
    provider,
    search_time_ms,
    expires_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
) RETURNING id, query_hash, original_query, optimized_query, user_id, conversation_id, results, result_count, provider, search_time_ms, expires_at, hit_count, last_hit_at, created_at
`

type SaveSearchResultParams struct {
	QueryHash      string             `json:"query_hash"`
	OriginalQuery  string             `json:"original_query"`
	OptimizedQuery *string            `json:"optimized_query"`
	UserID         *string            `json:"user_id"`
	ConversationID pgtype.UUID        `json:"conversation_id"`
	Results        []byte             `json:"results"`
	ResultCount    *int32             `json:"result_count"`
	Provider       *string            `json:"provider"`
	SearchTimeMs   *float64           `json:"search_time_ms"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) SaveSearchResult(ctx context.Context, arg SaveSearchResultParams) (WebSearchResult, error) {
	row := q.db.QueryRow(ctx, saveSearchResult,
		arg.QueryHash,
		arg.OriginalQuery,
		arg.OptimizedQuery,
		arg.UserID,
		arg.ConversationID,
		arg.Results,
		arg.ResultCount,
		arg.Provider,
		arg.SearchTimeMs,
		arg.ExpiresAt,
	)
	var i WebSearchResult
	err := row.Scan(
		&i.ID,
		&i.QueryHash,
		&i.OriginalQuery,
		&i.OptimizedQuery,
		&i.UserID,
		&i.ConversationID,
		&i.Results,
		&i.ResultCount,
		&i.Provider,
		&i.SearchTimeMs,
		&i.ExpiresAt,
		&i.HitCount,
		&i.LastHitAt,
		&i.CreatedAt,
	)
	return i, err
}
