#!/usr/bin/env bash
# Start/stop the BusinessOS local dev stack (backend + frontend + Electron).
# No Docker. Assumes Postgres/Redis already running locally (or backend's .env
# points at remote, like Supabase).
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
RUN_DIR="$ROOT/.run"
mkdir -p "$RUN_DIR"

# ============================================================================
# Single source of truth: $ROOT/.env.dev (auto-created if missing).
# Edit that file to change ports; this script syncs the downstream .env files
# (frontend/.env.development.local, desktop/backend-go/.env) before each start.
# ============================================================================
ENV_FILE="$ROOT/.env.dev"
if [ ! -f "$ENV_FILE" ]; then
    cat > "$ENV_FILE" <<'EOF'
# BusinessOS local dev — single source of truth for ports.
# Edit here, then run `make dev-local-restart`.
# The script auto-syncs frontend/.env.development.local and desktop/backend-go/.env.
BACKEND_PORT=8801
FRONTEND_PORT=5273
EOF
fi
set -a; . "$ENV_FILE"; set +a
BACKEND_PORT="${BACKEND_PORT:-8801}"
FRONTEND_PORT="${FRONTEND_PORT:-5273}"

BACKEND_BIN="$RUN_DIR/backend"
BACKEND_LOG="$RUN_DIR/backend.log"
FRONTEND_LOG="$RUN_DIR/frontend.log"
ELECTRON_LOG="$RUN_DIR/electron.log"

color() { printf '\033[%sm%s\033[0m' "$1" "$2"; }
info()  { echo "$(color '36' '==>') $*"; }
warn()  { echo "$(color '33' '!!') $*"; }
ok()    { echo "$(color '32' '✔') $*"; }
err()   { echo "$(color '31' '✗') $*" >&2; }

pid_alive() { [ -f "$1" ] && kill -0 "$(cat "$1")" 2>/dev/null; }

# Sync ports from $ENV_FILE → frontend/.env.development.local + desktop/backend-go/.env.
sync_env_files() {
    info "Syncing ports from .env.dev (BACKEND=$BACKEND_PORT, FRONTEND=$FRONTEND_PORT)"
    cat > "$ROOT/frontend/.env.development.local" <<EOF
# Auto-generated by scripts/dev-local.sh from .env.dev. Edit .env.dev instead.
BACKEND_PORT=$BACKEND_PORT
FRONTEND_PORT=$FRONTEND_PORT
VITE_LOCAL_BACKEND_URL=http://localhost:$BACKEND_PORT
EOF
    local be_env="$ROOT/desktop/backend-go/.env"
    if [ -f "$be_env" ]; then
        # SERVER_PORT
        if grep -q "^SERVER_PORT=" "$be_env"; then
            sed -i.bak "s|^SERVER_PORT=.*|SERVER_PORT=$BACKEND_PORT|" "$be_env"
        else
            printf "\nSERVER_PORT=%s\n" "$BACKEND_PORT" >> "$be_env"
        fi
        # ALLOWED_ORIGINS — ensure http://localhost:$FRONTEND_PORT is in the list
        if grep -q "^ALLOWED_ORIGINS=" "$be_env"; then
            local cur
            cur=$(grep "^ALLOWED_ORIGINS=" "$be_env" | head -1 | cut -d= -f2-)
            if ! echo "$cur" | grep -q "localhost:$FRONTEND_PORT"; then
                sed -i.bak "s|^ALLOWED_ORIGINS=.*|ALLOWED_ORIGINS=$cur,http://localhost:$FRONTEND_PORT|" "$be_env"
            fi
        fi
        # GOOGLE_REDIRECT_URI port
        if grep -q "^GOOGLE_REDIRECT_URI=http://localhost:" "$be_env"; then
            sed -i.bak "s|^GOOGLE_REDIRECT_URI=http://localhost:[0-9]*|GOOGLE_REDIRECT_URI=http://localhost:$BACKEND_PORT|" "$be_env"
        fi
        rm -f "$be_env.bak"
    fi
}

# Ensure desktop deps + Electron binary are present (handles fresh checkouts).
ensure_desktop_deps() {
    if [ ! -d "$ROOT/desktop/node_modules" ]; then
        info "desktop/node_modules missing — installing (skipping native scripts)"
        ( cd "$ROOT/desktop" && npm install --ignore-scripts --no-audit --no-fund )
        info "Rebuilding native modules for Electron's ABI"
        ( cd "$ROOT/desktop" && npx --no-install @electron/rebuild -f -w better-sqlite3 ) || \
            warn "Native rebuild failed — better-sqlite3 may not work at runtime"
    fi
    if [ ! -d "$ROOT/desktop/node_modules/electron/dist/Electron.app" ]; then
        info "Electron binary missing — running install.js (downloads ~150MB)"
        ( cd "$ROOT/desktop" && node node_modules/electron/install.js )
        ok "Electron binary installed"
    fi
}

ensure_frontend_deps() {
    if [ ! -d "$ROOT/frontend/node_modules" ]; then
        info "frontend/node_modules missing — running pnpm install"
        ( cd "$ROOT/frontend" && pnpm install )
    fi
}

build_backend_if_stale() {
    local src="$ROOT/desktop/backend-go"
    if [ ! -x "$BACKEND_BIN" ] || [ -n "$(find "$src" -name '*.go' -newer "$BACKEND_BIN" -print -quit 2>/dev/null)" ]; then
        info "Building backend (Go) → $BACKEND_BIN"
        ( cd "$src" && go build -o "$BACKEND_BIN" ./cmd/server )
        ok "Backend built"
    else
        info "Backend binary up-to-date"
    fi
}

# Spawn a command fully detached from this script's job control.
# Args: <pidfile> <logfile> <workdir> <env vars (KEY=val space-separated)> -- <cmd> <args...>
spawn_detached() {
    local pidfile="$1" logfile="$2" workdir="$3"; shift 3
    local envs=()
    while [ "${1:-}" != "--" ] && [ "$#" -gt 0 ]; do envs+=("$1"); shift; done
    [ "${1:-}" = "--" ] && shift
    (
        cd "$workdir" || exit 1
        # NOTE: do NOT close stdin (no </dev/null) — electron-forge treats stdin
        # EOF as a quit signal and bails right after "Launched Electron app".
        if [ "${#envs[@]}" -gt 0 ]; then
            exec env "${envs[@]}" "$@" >"$logfile" 2>&1
        else
            exec "$@" >"$logfile" 2>&1
        fi
    ) &
    local pid=$!
    echo "$pid" > "$pidfile"
    disown "$pid" 2>/dev/null || true
}

start_backend() {
    if pid_alive "$RUN_DIR/backend.pid"; then
        warn "Backend already running (pid $(cat "$RUN_DIR/backend.pid"))"
        return
    fi
    info "Starting backend on :$BACKEND_PORT"
    # Must run from desktop/backend-go so godotenv finds .env
    spawn_detached "$RUN_DIR/backend.pid" "$BACKEND_LOG" "$ROOT/desktop/backend-go" -- "$BACKEND_BIN"
    for _ in $(seq 1 60); do
        if curl -sf -m 1 "http://localhost:$BACKEND_PORT/healthz" >/dev/null 2>&1; then
            ok "Backend healthy on :$BACKEND_PORT"
            return
        fi
        sleep 0.5
    done
    err "Backend did not become healthy in 30s — see $BACKEND_LOG"
    return 1
}

# OptimalEngine (Elixir) — starts the live engine the BO server proxies to.
# Skipped silently when:
#   - mix isn't on PATH (no Elixir installed; Go fallback handles requests)
#   - OPTIMAL_ENGINE_URL isn't set in backend .env (operator opted out)
# When started, the engine listens on :4200 (or whatever port is in the
# OPTIMAL_ENGINE_URL); BO server picks it up automatically because its
# proxy reads OPTIMAL_ENGINE_URL on each request.
ENGINE_LOG="$RUN_DIR/optimal-engine.log"
ENGINE_PID="$RUN_DIR/optimal-engine.pid"
ENGINE_PORT=4200

start_engine() {
    local be_env="$ROOT/desktop/backend-go/.env"
    if ! grep -q "^OPTIMAL_ENGINE_URL=" "$be_env" 2>/dev/null; then
        warn "OptimalEngine: OPTIMAL_ENGINE_URL not set in $be_env — skipping (Go fallback active)"
        return 0
    fi
    if ! command -v mix >/dev/null 2>&1; then
        warn "OptimalEngine: mix not on PATH — install Elixir to enable the live engine"
        return 0
    fi
    if pid_alive "$ENGINE_PID"; then
        warn "OptimalEngine already running (pid $(cat "$ENGINE_PID"))"
        return 0
    fi
    if lsof -ti tcp:$ENGINE_PORT >/dev/null 2>&1; then
        warn "OptimalEngine: :$ENGINE_PORT already taken (pre-existing process); skipping"
        return 0
    fi
    info "Starting Elixir OptimalEngine on :$ENGINE_PORT"
    local engine_dir="$ROOT/optimal-engine"
    if [ ! -d "$engine_dir/deps" ]; then
        info "  (first run — fetching mix deps; this can take a minute)"
        (cd "$engine_dir" && mix deps.get >>"$ENGINE_LOG" 2>&1) || warn "mix deps.get failed; continuing"
    fi
    local sw="$engine_dir/sample-workspace"
    (
        cd "$engine_dir" || exit 1
        exec env \
            OPTIMAL_ENGINE_ROOT="$sw" \
            OPTIMAL_ENGINE_DB="$sw/.system/index.db" \
            OPTIMAL_API_ENABLED=true \
            mix run --no-halt
    ) >>"$ENGINE_LOG" 2>&1 &
    local pid=$!
    echo "$pid" > "$ENGINE_PID"
    disown "$pid" 2>/dev/null || true
    for _ in $(seq 1 60); do
        if curl -sf -m 1 "http://localhost:$ENGINE_PORT/api/health" >/dev/null 2>&1; then
            ok "OptimalEngine ready on :$ENGINE_PORT"
            return 0
        fi
        sleep 1
    done
    warn "OptimalEngine did not become ready in 60s — see $ENGINE_LOG (BO will fall back to Go port)"
    return 0
}

start_frontend() {
    if pid_alive "$RUN_DIR/frontend.pid"; then
        warn "Frontend already running (pid $(cat "$RUN_DIR/frontend.pid"))"
        return
    fi
    info "Starting frontend on :$FRONTEND_PORT"
    spawn_detached "$RUN_DIR/frontend.pid" "$FRONTEND_LOG" "$ROOT/frontend" -- pnpm dev
    for _ in $(seq 1 60); do
        if curl -sf -m 1 -o /dev/null "http://localhost:$FRONTEND_PORT/"; then
            ok "Frontend serving on :$FRONTEND_PORT"
            return
        fi
        sleep 0.5
    done
    err "Frontend did not respond in 30s — see $FRONTEND_LOG"
    return 1
}

start_electron() {
    if pid_alive "$RUN_DIR/electron.pid"; then
        warn "Electron already running (pid $(cat "$RUN_DIR/electron.pid"))"
        return
    fi
    info "Starting Electron (BUSINESSOS_DEV_URL=http://localhost:$FRONTEND_PORT)"
    # electron-forge treats stdin EOF as 'quit'. The parent shell's stdin
    # closes the moment this script returns — so we feed it `tail -f /dev/null`
    # which blocks forever and never sends EOF.
    (
        cd "$ROOT/desktop" || exit 1
        exec env "BUSINESSOS_DEV_URL=http://localhost:$FRONTEND_PORT" \
            bash -c 'tail -f /dev/null | exec npm start' \
            > "$ELECTRON_LOG" 2>&1
    ) &
    local pid=$!
    echo "$pid" > "$RUN_DIR/electron.pid"
    disown "$pid" 2>/dev/null || true
    # Forge takes ~10s to bundle + launch; poll the log for the success marker
    for _ in $(seq 1 40); do
        if grep -q "Launched Electron app" "$ELECTRON_LOG" 2>/dev/null; then
            ok "Electron launched"
            return
        fi
        if ! pid_alive "$RUN_DIR/electron.pid"; then
            err "Electron exited prematurely — see $ELECTRON_LOG"
            return 1
        fi
        sleep 0.5
    done
    warn "Electron didn't report 'Launched' in 20s; still running, check $ELECTRON_LOG"
}

cmd_start() {
    sync_env_files
    ensure_frontend_deps
    ensure_desktop_deps
    build_backend_if_stale
    start_engine
    start_backend
    start_frontend
    start_electron
    echo
    cmd_status
    echo
    echo "Logs:    make dev-local-logs    (or: tail -f $RUN_DIR/*.log)"
    echo "Stop:    make dev-local-stop"
}

stop_one() {
    local name="$1" pid_file="$RUN_DIR/$1.pid"
    if [ -f "$pid_file" ]; then
        local pid; pid=$(cat "$pid_file")
        if kill -0 "$pid" 2>/dev/null; then
            # Kill the whole process group so we catch tail | npm | electron-forge | electron
            local pgid
            pgid=$(ps -o pgid= -p "$pid" 2>/dev/null | tr -d ' ')
            if [ -n "$pgid" ]; then
                kill -TERM -- "-$pgid" 2>/dev/null || true
            fi
            pkill -P "$pid" 2>/dev/null || true
            kill "$pid" 2>/dev/null || true
            ok "stopped $name (pid $pid)"
        fi
        rm -f "$pid_file"
    fi
}

cmd_stop() {
    info "Stopping local dev stack"
    stop_one electron
    stop_one frontend
    stop_one backend
    stop_one optimal-engine
    # Sweep any stragglers on our ports
    if command -v lsof >/dev/null; then
        lsof -ti tcp:"$BACKEND_PORT" 2>/dev/null | xargs -r kill 2>/dev/null || true
        lsof -ti tcp:"$FRONTEND_PORT" 2>/dev/null | xargs -r kill 2>/dev/null || true
        lsof -ti tcp:"$ENGINE_PORT" 2>/dev/null | xargs -r kill 2>/dev/null || true
    fi
    pkill -f "electron-forge" 2>/dev/null || true
    pkill -f "BusinessOS.app" 2>/dev/null || true
    ok "Stack stopped"
}

cmd_status() {
    printf '%-10s %-7s %-12s %s\n' "Service" "Port" "Status" "PID"
    printf '%-10s %-7s %-12s %s\n' "-------" "----" "------" "---"
    for row in "optimal-engine:$ENGINE_PORT" "backend:$BACKEND_PORT" "frontend:$FRONTEND_PORT" "electron:-"; do
        name="${row%%:*}"
        port="${row##*:}"
        if pid_alive "$RUN_DIR/$name.pid"; then
            status="$(color '32' 'running')"
            pid=$(cat "$RUN_DIR/$name.pid")
        else
            status="$(color '31' 'down')"
            pid="-"
        fi
        printf '%-10s %-7s %-22s %s\n' "$name" "$port" "$status" "$pid"
    done
}

cmd_logs() {
    exec tail -F "$BACKEND_LOG" "$FRONTEND_LOG" "$ELECTRON_LOG" 2>/dev/null
}

case "${1:-start}" in
    start)   cmd_start ;;
    stop)    cmd_stop ;;
    restart) cmd_stop; sleep 1; cmd_start ;;
    status)  cmd_status ;;
    logs)    cmd_logs ;;
    *) echo "Usage: $0 {start|stop|restart|status|logs}"; exit 1 ;;
esac
