#!/usr/bin/env bash
# Start/stop the BusinessOS local dev stack (backend + frontend + Electron).
# Local PostgreSQL is started and verified when the configured database URL
# points at this machine. Remote database URLs are left untouched.
set -euo pipefail

ROOT="${BUSINESSOS_ROOT:-$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)}"
RUN_DIR="${BUSINESSOS_RUN_DIR:-$ROOT/.run}"
mkdir -p "$RUN_DIR"

# ============================================================================
# Single source of truth: $ROOT/.env.dev (auto-created if missing).
# Edit that file to change ports; this script syncs the downstream .env files
# (frontend/.env.development.local, desktop/backend-go/.env) before each start.
# ============================================================================
ENV_FILE="$ROOT/.env.dev"
if [ ! -f "$ENV_FILE" ]; then
    cat > "$ENV_FILE" <<'EOF'
# BusinessOS local dev - single source of truth for ports.
# Edit here, then run `make dev-local-restart`.
# The script auto-syncs frontend/.env.development.local and desktop/backend-go/.env.
BACKEND_PORT=8801
FRONTEND_PORT=5273
POSTGRES_PORT=25432
REDIS_PORT=26379
ENGINE_PORT=4200
EOF
fi
set -a
# shellcheck disable=SC1090
. "$ENV_FILE"
set +a
BACKEND_PORT="${BACKEND_PORT:-8801}"
FRONTEND_PORT="${FRONTEND_PORT:-5273}"
POSTGRES_PORT="${POSTGRES_PORT:-25432}"
REDIS_PORT="${REDIS_PORT:-26379}"
ENGINE_PORT="${ENGINE_PORT:-4200}"

BACKEND_BIN="$RUN_DIR/backend"
BACKEND_LOG="$RUN_DIR/backend.log"
FRONTEND_LOG="$RUN_DIR/frontend.log"
ELECTRON_LOG="$RUN_DIR/electron.log"
CURL="${CURL:-$(command -v curl || echo /usr/bin/curl)}"
LSOF="${LSOF:-$(command -v lsof || echo /usr/sbin/lsof)}"
PYTHON="${PYTHON:-$(command -v python3 || true)}"
PSQL="${PSQL:-$(command -v psql || true)}"
REDIS_CLI="${REDIS_CLI:-$(command -v redis-cli || true)}"
BACKEND_REBUILT=0
DESKTOP_REBUILT=0

color() { printf '\033[%sm%s\033[0m' "$1" "$2"; }
info()  { echo "$(color '36' '==>') $*"; }
warn()  { echo "$(color '33' '!!') $*"; }
ok()    { echo "$(color '32' '✔') $*"; }
err()   { echo "$(color '31' '✗') $*" >&2; }

pid_alive() { [ -f "$1" ] && kill -0 "$(cat "$1")" 2>/dev/null; }

generate_secret() {
    local bytes="${1:-32}"
    if command -v openssl >/dev/null 2>&1; then
        openssl rand -hex "$bytes"
    else
        od -An -N "$bytes" -tx1 /dev/urandom | tr -d ' \n'
    fi
}

generate_token_encryption_key() {
    openssl rand -base64 32 | tr -d '\n'
}

set_env_value() {
    local file="$1" key="$2" value="$3" tmp
    tmp=$(mktemp)
    awk -v key="$key" -v value="$value" '
        BEGIN { found = 0 }
        $0 ~ "^" key "=" {
            if (!found) print key "=" value
            found = 1
            next
        }
        { print }
        END {
            if (!found) print key "=" value
        }
    ' "$file" > "$tmp"
    mv "$tmp" "$file"
}

ensure_backend_env() {
    local be_env="$ROOT/desktop/backend-go/.env"
    if [ -f "$be_env" ]; then
        return 0
    fi

    info "Creating isolated local backend configuration"
    cp "$ROOT/desktop/backend-go/.env.example" "$be_env"
    set_env_value "$be_env" DATABASE_URL \
        "postgres://postgres@127.0.0.1:$POSTGRES_PORT/businessos_dev?sslmode=disable"
    set_env_value "$be_env" REDIS_URL "redis://127.0.0.1:$REDIS_PORT/0"
    set_env_value "$be_env" REDIS_PASSWORD ""
    set_env_value "$be_env" SECRET_KEY "$(generate_secret 64)"
    # The backend accepts a base64-encoded 32-byte AES-256 key.
    set_env_value "$be_env" TOKEN_ENCRYPTION_KEY "$(generate_token_encryption_key)"
    set_env_value "$be_env" REDIS_KEY_HMAC_SECRET "$(generate_secret 32)"
    set_env_value "$be_env" ENVIRONMENT development
    set_env_value "$be_env" OPTIMAL_ENGINE_URL "http://127.0.0.1:$ENGINE_PORT"
    chmod 600 "$be_env"
    ok "Created $be_env with local-only credentials"
}

pid_for() {
    local pid_file="$RUN_DIR/$1.pid"
    if pid_alive "$pid_file"; then
        cat "$pid_file"
    else
        printf -- "-"
    fi
}

# Sync ports from $ENV_FILE into frontend and backend environment files.
sync_env_files() {
    info "Syncing ports from .env.dev (BACKEND=$BACKEND_PORT, FRONTEND=$FRONTEND_PORT)"
    cat > "$ROOT/frontend/.env.development.local" <<EOF
# Auto-generated by scripts/dev-local.sh from .env.dev. Edit .env.dev instead.
BACKEND_PORT=$BACKEND_PORT
FRONTEND_PORT=$FRONTEND_PORT
VITE_LOCAL_BACKEND_URL=${VITE_LOCAL_BACKEND_URL:-http://localhost:$BACKEND_PORT}
VITE_BACKEND_URL=${VITE_LOCAL_BACKEND_URL:-http://localhost:$BACKEND_PORT}
BACKEND_TARGET=${BACKEND_TARGET:-http://localhost:$BACKEND_PORT}
EOF
    local be_env="$ROOT/desktop/backend-go/.env"
    if [ -f "$be_env" ]; then
        # SERVER_PORT
        if grep -q "^SERVER_PORT=" "$be_env"; then
            sed -i.bak "s|^SERVER_PORT=.*|SERVER_PORT=$BACKEND_PORT|" "$be_env"
        else
            printf "\nSERVER_PORT=%s\n" "$BACKEND_PORT" >> "$be_env"
        fi
        # Frontend URL used by OAuth integration callbacks (Google Calendar, etc.).
        if grep -q "^FRONTEND_PORT=" "$be_env"; then
            sed -i.bak "s|^FRONTEND_PORT=.*|FRONTEND_PORT=$FRONTEND_PORT|" "$be_env"
        else
            printf "\nFRONTEND_PORT=%s\n" "$FRONTEND_PORT" >> "$be_env"
        fi
        if grep -q "^FRONTEND_URL=" "$be_env"; then
            sed -i.bak "s|^FRONTEND_URL=.*|FRONTEND_URL=http://localhost:$FRONTEND_PORT|" "$be_env"
        else
            printf "\nFRONTEND_URL=http://localhost:%s\n" "$FRONTEND_PORT" >> "$be_env"
        fi
        # ALLOWED_ORIGINS — ensure http://localhost:$FRONTEND_PORT is in the list
        if grep -q "^ALLOWED_ORIGINS=" "$be_env"; then
            local cur
            cur=$(grep "^ALLOWED_ORIGINS=" "$be_env" | head -1 | cut -d= -f2-)
            if ! echo "$cur" | grep -q "localhost:$FRONTEND_PORT"; then
                sed -i.bak "s|^ALLOWED_ORIGINS=.*|ALLOWED_ORIGINS=$cur,http://localhost:$FRONTEND_PORT|" "$be_env"
            fi
        fi
        # GOOGLE_REDIRECT_URI port
        if grep -q "^GOOGLE_REDIRECT_URI=http://localhost:" "$be_env"; then
            sed -i.bak "s|^GOOGLE_REDIRECT_URI=http://localhost:[0-9]*|GOOGLE_REDIRECT_URI=http://localhost:$BACKEND_PORT|" "$be_env"
        fi
        # Keep the shared integration callback for legacy Google flows.
        if grep -q "^GOOGLE_INTEGRATION_REDIRECT_URI=http://localhost:" "$be_env"; then
            sed -i.bak "s|^GOOGLE_INTEGRATION_REDIRECT_URI=http://localhost:[0-9]*/api/integrations/.*|GOOGLE_INTEGRATION_REDIRECT_URI=http://localhost:$BACKEND_PORT/api/integrations/google/callback|" "$be_env"
        else
            printf "\nGOOGLE_INTEGRATION_REDIRECT_URI=http://localhost:%s/api/integrations/google/callback\n" "$BACKEND_PORT" >> "$be_env"
        fi
        # Tool OAuth callbacks are separate. Do not collapse them into the
        # legacy shared callback because Google validates the exact URI.
        if grep -q "^GOOGLE_CALENDAR_REDIRECT_URI=http://localhost:" "$be_env"; then
            sed -i.bak "s|^GOOGLE_CALENDAR_REDIRECT_URI=http://localhost:[0-9]*/api/integrations/.*|GOOGLE_CALENDAR_REDIRECT_URI=http://localhost:$BACKEND_PORT/api/integrations/google_calendar/callback|" "$be_env"
        else
            printf "\nGOOGLE_CALENDAR_REDIRECT_URI=http://localhost:%s/api/integrations/google_calendar/callback\n" "$BACKEND_PORT" >> "$be_env"
        fi
        rm -f "$be_env.bak"
    fi
}

resolve_postgres_bin() {
    local version="${1:-}" candidate
    if [ -n "${BUSINESSOS_PG_BIN:-}" ] && [ -x "$BUSINESSOS_PG_BIN/pg_ctl" ]; then
        printf '%s' "$BUSINESSOS_PG_BIN"
        return 0
    fi
    if command -v pg_config >/dev/null 2>&1; then
        candidate=$(pg_config --bindir 2>/dev/null || true)
        if [ -x "$candidate/pg_ctl" ] && [ -x "$candidate/initdb" ] && {
            [ -z "$version" ] || "$candidate/pg_ctl" --version | grep -q " $version\\.";
        }; then
            printf '%s' "$candidate"
            return 0
        fi
    fi
    if [ -n "$version" ] && command -v brew >/dev/null 2>&1; then
        candidate="$(brew --prefix "postgresql@$version" 2>/dev/null || true)/bin"
        if [ -x "$candidate/pg_ctl" ]; then
            printf '%s' "$candidate"
            return 0
        fi
    fi
    for candidate in \
        /opt/homebrew/opt/postgresql@*/bin \
        /usr/local/opt/postgresql@*/bin \
        /opt/homebrew/opt/postgresql/bin \
        /usr/local/opt/postgresql/bin \
        /usr/lib/postgresql/*/bin; do
        if [ -x "$candidate/pg_ctl" ] && [ -x "$candidate/initdb" ] && {
            [ -z "$version" ] || "$candidate/pg_ctl" --version | grep -q " $version\\.";
        }; then
            printf '%s' "$candidate"
            return 0
        fi
    done
    return 1
}

# Ensure desktop deps + Electron binary are present (handles fresh checkouts).
ensure_desktop_deps() {
    if [ ! -d "$ROOT/desktop/node_modules" ]; then
        info "desktop/node_modules missing — installing (skipping native scripts)"
        ( cd "$ROOT/desktop" && npm install --ignore-scripts --no-audit --no-fund )
        info "Rebuilding native modules for Electron's ABI"
        ( cd "$ROOT/desktop" && npx --no-install @electron/rebuild -f -w better-sqlite3 ) || \
            warn "Native rebuild failed — better-sqlite3 may not work at runtime"
    fi
    if [ ! -d "$ROOT/desktop/node_modules/electron/dist/Electron.app" ]; then
        info "Electron binary missing — running install.js (downloads ~150MB)"
        ( cd "$ROOT/desktop" && node node_modules/electron/install.js )
        ok "Electron binary installed"
    fi
}

ensure_frontend_deps() {
    if [ ! -d "$ROOT/frontend/node_modules" ]; then
        info "frontend/node_modules missing — running pnpm install"
        ( cd "$ROOT/frontend" && pnpm install )
    fi

    # The frontend links both bundled Optimal Engine SDKs from this checkout.
    # A clean clone has their sources, but not their generated dist packages.
    # Build them before Vite starts so first-run dependency scanning succeeds.
    if [ ! -f "$ROOT/optimal-engine/sdks/typescript/dist/index.js" ] || \
       [ ! -f "$ROOT/optimal-engine/sdks/miosa/dist/index.js" ]; then
        info "Optimal Engine SDK builds missing - building local packages"
        ( cd "$ROOT/frontend" && pnpm run build:optimal-sdks )
        ok "Optimal Engine SDKs built"
    fi
}

build_backend_if_stale() {
    local src="$ROOT/desktop/backend-go"
    # The server embeds SQL migrations with go:embed. Rebuild when either Go
    # source, dependency metadata, or a migration changes. Otherwise a restart
    # can execute stale code or SQL.
    if [ ! -x "$BACKEND_BIN" ] || [ -n "$(find "$src" -type f \( -name '*.go' -o -name '*.sql' -o -name 'go.mod' -o -name 'go.sum' \) -newer "$BACKEND_BIN" -print -quit 2>/dev/null)" ]; then
        info "Building backend (Go) → $BACKEND_BIN"
        ( cd "$src" && go build -o "$BACKEND_BIN" ./cmd/server )
        BACKEND_REBUILT=1
        ok "Backend built"
    else
        info "Backend binary up-to-date"
    fi
}

build_desktop_if_stale() {
    local src="$ROOT/desktop/src"
    local main_bundle="$ROOT/desktop/.vite/build/index.js"
    local preload_bundle="$ROOT/desktop/.vite/preload/index.js"
    if [ ! -f "$main_bundle" ] || [ ! -f "$preload_bundle" ] || [ "$ROOT/desktop/vite.main.config.ts" -nt "$main_bundle" ] || [ "$ROOT/desktop/vite.preload.config.ts" -nt "$preload_bundle" ] || [ -n "$(find "$src" -type f \( -name '*.ts' -o -name '*.js' \) -newer "$main_bundle" -print -quit 2>/dev/null)" ]; then
        info "Building Electron main/preload bundles"
        ( cd "$ROOT/desktop" && npx vite build --config vite.main.config.ts --ssr src/main/index.ts )
        ( cd "$ROOT/desktop" && npx vite build --config vite.preload.config.ts --ssr src/preload/index.ts --outDir .vite/preload )
        DESKTOP_REBUILT=1
        ok "Electron bundles built"
    else
        info "Electron bundles up-to-date"
    fi
}

read_env_value() {
    local key="$1" file="$2" value
    value=$(grep "^${key}=" "$file" 2>/dev/null | tail -1 | cut -d= -f2- | tr -d '\r')
    case "$value" in
        \"*\") value=${value#\"}; value=${value%\"} ;;
        \'*\') value=${value#\'}; value=${value%\'} ;;
    esac
    printf '%s' "$value"
}

url_port() {
    local url="$1" default_port="$2" hostport port
    hostport="${url#*://}"
    hostport="${hostport#*@}"
    hostport="${hostport%%/*}"
    if [[ "$hostport" == \[* ]]; then
        port="${hostport##*]:}"
    else
        port="${hostport##*:}"
    fi
    if [ "$port" = "$hostport" ] || [ -z "$port" ]; then
        port="$default_port"
    fi
    printf '%s' "$port"
}

ensure_local_postgres() {
    local be_env="$ROOT/desktop/backend-go/.env"
    local database_url hostport host port database_name data_dir version pg_bin pg_ctl pg_isready psql initdb createdb

    database_url="${DATABASE_URL:-}"
    if [ -z "$database_url" ] && [ -f "$be_env" ]; then
        database_url=$(read_env_value DATABASE_URL "$be_env")
    fi
    if [ -z "$database_url" ]; then
        err "DATABASE_URL is missing from $be_env"
        return 1
    fi

    # This launcher only manages explicit local PostgreSQL URLs.
    local connection_url
    connection_url="${database_url#*://}"
    hostport="${connection_url#*@}"
    database_name="${hostport#*/}"
    hostport="${hostport%%/*}"
    database_name="${database_name%%\?*}"
    if [[ "$hostport" == \[* ]]; then
        host="${hostport#\[}"
        host="${host%%\]*}"
        port="${hostport##*]:}"
    else
        host="${hostport%%:*}"
        port="${hostport##*:}"
    fi
    if [ "$port" = "$hostport" ] || [ -z "$port" ]; then
        port=5432
    fi
    case "$host" in
        localhost|127.0.0.1|::1) ;;
        *) return 0 ;;
    esac

    data_dir="${BUSINESSOS_PGDATA:-$RUN_DIR/pgdata}"
    version=""
    if [ -f "$data_dir/PG_VERSION" ]; then
        version=$(tr -d '[:space:]' < "$data_dir/PG_VERSION")
    fi
    if ! pg_bin=$(resolve_postgres_bin "$version"); then
        err "PostgreSQL tools were not found. Install PostgreSQL 14+ and retry."
        err "macOS: brew install postgresql@16"
        return 1
    fi
    pg_ctl="$pg_bin/pg_ctl"
    pg_isready="$pg_bin/pg_isready"
    psql="$pg_bin/psql"
    initdb="$pg_bin/initdb"
    createdb="$pg_bin/createdb"

    if [ ! -f "$data_dir/PG_VERSION" ]; then
        info "Initializing isolated PostgreSQL data in $data_dir"
        mkdir -p "$data_dir"
        "$initdb" -D "$data_dir" -U postgres -A trust --encoding=UTF8 --no-locale \
            >"$RUN_DIR/initdb.log" 2>&1
        ok "PostgreSQL data directory initialized"
    fi
    version=$(tr -d '[:space:]' < "$data_dir/PG_VERSION")
    if ! "$pg_ctl" --version | grep -q " $version\\."; then
        err "PostgreSQL data is version $version but tools are $("$pg_ctl" --version)."
        err "Set BUSINESSOS_PG_BIN to the matching PostgreSQL bin directory."
        return 1
    fi

    if ! "$pg_isready" -h "$host" -p "$port" -d postgres >/dev/null 2>&1; then
        info "Starting local PostgreSQL $version on :$port"
        "$pg_ctl" -D "$data_dir" -l "$RUN_DIR/pgdev.log" -o "-p $port -k /tmp" start >/dev/null
        for _ in $(seq 1 30); do
            if "$pg_isready" -h "$host" -p "$port" -d postgres >/dev/null 2>&1; then
                break
            fi
            sleep 0.5
        done
    fi
    if ! "$pg_isready" -h "$host" -p "$port" -d postgres >/dev/null 2>&1; then
        err "PostgreSQL is not accepting connections on $host:$port. See $RUN_DIR/pgdev.log"
        return 1
    fi
    case "$database_name" in
        *[!A-Za-z0-9_]*|'')
            err "Configured database name contains unsupported characters: $database_name"
            return 1
            ;;
    esac
    local maintenance_url database_query
    maintenance_url="${database_url%%\?*}"
    maintenance_url="${maintenance_url%/*}/postgres"
    if [[ "$database_url" == *\?* ]]; then
        database_query="${database_url#*\?}"
        maintenance_url="${maintenance_url}?${database_query}"
    fi
    if ! "$psql" "$maintenance_url" -Atq \
        -c "SELECT 1 FROM pg_database WHERE datname = '$database_name'" | grep -qx '1'; then
        info "Creating local database $database_name"
        "$createdb" --maintenance-db="$maintenance_url" "$database_name"
    fi
    ok "PostgreSQL $version ready on :$port ($database_name)"
}

ensure_local_redis() {
    local be_env="$ROOT/desktop/backend-go/.env"
    local redis_url hostport host port redis_dir
    redis_url="${REDIS_URL:-$(read_env_value REDIS_URL "$be_env")}"
    if [ -z "$redis_url" ]; then
        err "REDIS_URL is missing from $be_env"
        return 1
    fi
    hostport="${redis_url#*://}"
    hostport="${hostport#*@}"
    hostport="${hostport%%/*}"
    host="${hostport%%:*}"
    port="${hostport##*:}"
    [ "$port" != "$hostport" ] || port=6379
    case "$host" in
        localhost|127.0.0.1|::1) ;;
        *) return 0 ;;
    esac

    if [ -n "$REDIS_CLI" ] && "$REDIS_CLI" -h "$host" -p "$port" ping 2>/dev/null | grep -q PONG; then
        ok "Redis ready on :$port"
        return 0
    fi
    if ! command -v redis-server >/dev/null 2>&1; then
        err "Redis was not found. Install Redis and retry."
        err "macOS: brew install redis"
        return 1
    fi
    if [ -z "$REDIS_CLI" ] || [ ! -x "$REDIS_CLI" ]; then
        err "redis-cli was not found. Install the complete Redis package and retry."
        return 1
    fi
    redis_dir="$RUN_DIR/redis"
    mkdir -p "$redis_dir"
    info "Starting isolated Redis on :$port"
    redis-server \
        --bind 127.0.0.1 \
        --port "$port" \
        --daemonize yes \
        --pidfile "$RUN_DIR/redis.pid" \
        --logfile "$RUN_DIR/redis.log" \
        --dir "$redis_dir" \
        --dbfilename dump.rdb
    REDIS_CLI="${REDIS_CLI:-$(command -v redis-cli || true)}"
    for _ in $(seq 1 30); do
        if "$REDIS_CLI" -h "$host" -p "$port" ping 2>/dev/null | grep -q PONG; then
            ok "Redis ready on :$port"
            return 0
        fi
        sleep 0.25
    done
    err "Redis did not become ready. See $RUN_DIR/redis.log"
    return 1
}

# Spawn a command fully detached from this script's job control.
# Args: <pidfile> <logfile> <workdir> <env vars (KEY=val space-separated)> -- <cmd> <args...>
spawn_detached() {
    local pidfile="$1" logfile="$2" workdir="$3"; shift 3
    # Bash 3.2 (the macOS system Bash) treats an expanded empty array as an
    # unbound variable under `set -u`. Keep one harmless default so backend and
    # frontend launches work even when callers provide no explicit env pairs.
    local envs=("PYTHONUNBUFFERED=1")
    while [ "${1:-}" != "--" ] && [ "$#" -gt 0 ]; do envs+=("$1"); shift; done
    [ "${1:-}" = "--" ] && shift

    if [ ! -x "$PYTHON" ]; then
        err "Python not found at $PYTHON; cannot detach dev process"
        return 1
    fi

    "$PYTHON" - "$pidfile" "$logfile" "$workdir" "${#envs[@]}" "${envs[@]}" -- "$@" <<'PY'
import os
import subprocess
import sys

pidfile, logfile, workdir, env_count_raw, *rest = sys.argv[1:]
env_count = int(env_count_raw)
env_pairs = rest[:env_count]
separator = rest[env_count]
command = rest[env_count + 1:]
if separator != "--" or not command:
    raise SystemExit("invalid spawn_detached arguments")

env = os.environ.copy()
for pair in env_pairs:
    key, _, value = pair.partition("=")
    if key:
        env[key] = value

os.makedirs(os.path.dirname(logfile), exist_ok=True)
with open(logfile, "ab", buffering=0) as log:
    process = subprocess.Popen(
        command,
        cwd=workdir,
        env=env,
        stdin=subprocess.DEVNULL,
        stdout=log,
        stderr=subprocess.STDOUT,
        start_new_session=True,
        close_fds=True,
    )

with open(pidfile, "w", encoding="utf-8") as f:
    f.write(str(process.pid))
PY
}

start_backend() {
    if pid_alive "$RUN_DIR/backend.pid"; then
        warn "Backend already running (pid $(cat "$RUN_DIR/backend.pid"))"
        return
    fi
    info "Starting backend on :$BACKEND_PORT"
    # Must run from desktop/backend-go so godotenv finds .env
    spawn_detached "$RUN_DIR/backend.pid" "$BACKEND_LOG" "$ROOT/desktop/backend-go" -- "$BACKEND_BIN"
    for _ in $(seq 1 60); do
        if "$CURL" -sf -m 1 "http://localhost:$BACKEND_PORT/healthz" >/dev/null 2>&1; then
            ok "Backend healthy on :$BACKEND_PORT"
            return
        fi
        sleep 0.5
    done
    err "Backend did not become healthy in 30s — see $BACKEND_LOG"
    return 1
}

verify_schema_contract() {
    info "Verifying database schema contract"
    (
        cd "$ROOT/desktop/backend-go"
        go run ./scripts/db/verify_schema_contract.go
    )
    ok "Database schema contract passed"
}

# OptimalEngine (Elixir) — starts the live engine the BO server proxies to.
# Skipped silently when:
#   - mix isn't on PATH (no Elixir installed; engine-backed routes return 503)
#   - OPTIMAL_ENGINE_URL isn't set in backend .env (operator opted out)
# When started, the engine listens on :4200 (or whatever port is in the
# OPTIMAL_ENGINE_URL); BO server picks it up automatically because its
# proxy reads OPTIMAL_ENGINE_URL on each request.
ENGINE_LOG="$RUN_DIR/optimal-engine.log"
ENGINE_PID="$RUN_DIR/optimal-engine.pid"
start_engine() {
    if "$CURL" -sf -m 1 "http://127.0.0.1:${ENGINE_PORT:-4200}/api/health" >/dev/null 2>&1; then
        ok "OptimalEngine already running on :${ENGINE_PORT:-4200} - using it"
        return 0
    fi

    local be_env="$ROOT/desktop/backend-go/.env"
    if ! grep -q "^OPTIMAL_ENGINE_URL=" "$be_env" 2>/dev/null; then
        warn "OptimalEngine: OPTIMAL_ENGINE_URL not set in $be_env - skipping"
        return 0
    fi
    if ! command -v mix >/dev/null 2>&1; then
        warn "OptimalEngine: mix not on PATH - install Elixir for engine-backed modules"
        return 0
    fi
    if pid_alive "$ENGINE_PID"; then
        warn "OptimalEngine already running (pid $(cat "$ENGINE_PID"))"
        return 0
    fi
    if "$LSOF" -ti tcp:"$ENGINE_PORT" >/dev/null 2>&1; then
        warn "OptimalEngine: :$ENGINE_PORT already taken (pre-existing process); skipping"
        return 0
    fi
    info "Starting bundled OptimalEngine on :$ENGINE_PORT"
    local engine_dir="$ROOT/optimal-engine"
    if [ ! -d "$engine_dir/deps" ]; then
        info "Fetching OptimalEngine dependencies"
        (cd "$engine_dir" && mix deps.get >>"$ENGINE_LOG" 2>&1)
    fi
    # Defaults to a scratch dir, but honors OPTIMAL_ENGINE_ROOT / OPTIMAL_ENGINE_DB
    # so you can point BusinessOS at real data (e.g. your OptimalOS workspaces).
    local sw="${OPTIMAL_ENGINE_ROOT:-$ROOT/.run/optimal-engine-data}"
    local sdb="${OPTIMAL_ENGINE_DB:-$sw/.optimal/index.db}"
    local scache="${OPTIMAL_ENGINE_CACHE:-$ROOT/.run/optimal-engine-cache}"
    mkdir -p "$(dirname "$sdb")" "$scache"
    spawn_detached \
        "$ENGINE_PID" \
        "$ENGINE_LOG" \
        "$engine_dir" \
        "OPTIMAL_ENGINE_ROOT=$sw" \
        "OPTIMAL_ENGINE_DB=$sdb" \
        "OPTIMAL_ENGINE_CACHE=$scache" \
        "OPTIMAL_API_ENABLED=true" \
        "OPTIMAL_API_PORT=$ENGINE_PORT" \
        -- mix run --no-halt
    for _ in $(seq 1 60); do
        if "$CURL" -sf -m 1 "http://127.0.0.1:$ENGINE_PORT/api/health" >/dev/null 2>&1; then
            ok "OptimalEngine ready on :$ENGINE_PORT"
            return 0
        fi
        sleep 1
    done
    err "OptimalEngine did not become ready in 60s. See $ENGINE_LOG"
    return 1
}

start_frontend() {
    if pid_alive "$RUN_DIR/frontend.pid"; then
        warn "Frontend already running (pid $(cat "$RUN_DIR/frontend.pid"))"
        return
    fi
    info "Starting frontend on :$FRONTEND_PORT"
    spawn_detached "$RUN_DIR/frontend.pid" "$FRONTEND_LOG" "$ROOT/frontend" -- pnpm dev
    for _ in $(seq 1 60); do
        if "$CURL" -sf -m 1 -o /dev/null "http://localhost:$FRONTEND_PORT/"; then
            ok "Frontend serving on :$FRONTEND_PORT"
            return
        fi
        sleep 0.5
    done
    err "Frontend did not respond in 30s — see $FRONTEND_LOG"
    return 1
}

start_electron() {
    if pid_alive "$RUN_DIR/electron.pid"; then
        warn "Electron already running (pid $(cat "$RUN_DIR/electron.pid"))"
        return
    fi
    info "Starting Electron (BUSINESSOS_DEV_URL=http://localhost:$FRONTEND_PORT)"
    # Linux dev: the npm-installed Electron's chrome-sandbox isn't setuid root
    # (only packaged installs get that), so the SUID sandbox aborts at startup.
    # Disable it for the dev instance only — the renderer loads first-party code.
    local sandbox_env=""
    if [ "$(uname -s)" = "Linux" ] && [ ! -u "$ROOT/desktop/node_modules/electron/dist/chrome-sandbox" ]; then
        sandbox_env="ELECTRON_DISABLE_SANDBOX=1"
    fi
    spawn_detached \
        "$RUN_DIR/electron.pid" \
        "$ELECTRON_LOG" \
        "$ROOT/desktop" \
        "BUSINESSOS_DEV_URL=http://localhost:$FRONTEND_PORT" \
        "BUSINESSOS_DEV_PORT=$FRONTEND_PORT" \
        "BUSINESSOS_BACKEND_PORT=$BACKEND_PORT" \
        "OPTIMAL_ENGINE_URL=${OPTIMAL_ENGINE_URL:-http://127.0.0.1:$ENGINE_PORT}" \
        ${sandbox_env:+"$sandbox_env"} \
        -- ./node_modules/.bin/electron .
    for _ in $(seq 1 40); do
        if grep -q "Loading from http://localhost:$FRONTEND_PORT" "$ELECTRON_LOG" 2>/dev/null; then
            ok "Electron launched"
            return
        fi
        if ! pid_alive "$RUN_DIR/electron.pid"; then
            err "Electron exited prematurely — see $ELECTRON_LOG"
            return 1
        fi
        sleep 0.5
    done
    warn "Electron didn't report ready in 20s; still running, check $ELECTRON_LOG"
}

cmd_start() {
    ensure_backend_env
    sync_env_files
    ensure_local_postgres
    ensure_local_redis
    ensure_frontend_deps
    ensure_desktop_deps
    build_backend_if_stale
    build_desktop_if_stale
    if [ "$BACKEND_REBUILT" = "1" ] && pid_alive "$RUN_DIR/backend.pid"; then
        info "Restarting managed backend to activate the new binary"
        stop_one backend
    fi
    if [ "$DESKTOP_REBUILT" = "1" ] && pid_alive "$RUN_DIR/electron.pid"; then
        info "Restarting Electron to activate the new bundles"
        stop_one electron
    fi
    # The backend owns the migration ledger. Running an individual migration
    # here records a partial ledger and prevents the backend from safely
    # baselining an existing local database on first startup.
    start_engine
    start_backend
    verify_schema_contract
    start_frontend
    if [ "${BUSINESSOS_HEADLESS:-0}" = "1" ]; then
        info "Headless mode enabled - skipping Electron launch"
    else
        start_electron
    fi
    echo
    cmd_status
    echo
    echo "Logs:    make dev-local-logs    (or: tail -f $RUN_DIR/*.log)"
    echo "Stop:    make dev-local-stop"
}

stop_one() {
    local name="$1" pid_file="$RUN_DIR/$1.pid"
    if [ -f "$pid_file" ]; then
        local pid; pid=$(cat "$pid_file")
        if kill -0 "$pid" 2>/dev/null; then
            pkill -P "$pid" 2>/dev/null || true
            kill "$pid" 2>/dev/null || true
            for _ in $(seq 1 20); do
                kill -0 "$pid" 2>/dev/null || break
                sleep 0.1
            done
            if kill -0 "$pid" 2>/dev/null; then
                kill -KILL "$pid" 2>/dev/null || true
            fi
            ok "stopped $name (pid $pid)"
        fi
        rm -f "$pid_file"
    fi
}

cmd_stop() {
    info "Stopping local dev stack"
    stop_one electron
    stop_one frontend
    stop_one backend
    stop_one optimal-engine
    if pid_alive "$RUN_DIR/redis.pid"; then
        stop_one redis
    fi
    local data_dir="${BUSINESSOS_PGDATA:-$RUN_DIR/pgdata}" pg_bin
    if [ -f "$data_dir/PG_VERSION" ] && pg_bin=$(resolve_postgres_bin "$(cat "$data_dir/PG_VERSION")"); then
        "$pg_bin/pg_ctl" -D "$data_dir" status >/dev/null 2>&1 && \
            "$pg_bin/pg_ctl" -D "$data_dir" stop -m fast >/dev/null
    fi
    pkill -f "$ROOT/desktop/node_modules/electron/dist/Electron.app/Contents/MacOS/Electron" 2>/dev/null || true
    pkill -f "electron-forge" 2>/dev/null || true
    pkill -f "BusinessOS.app" 2>/dev/null || true
    ok "Stack stopped"
}

cmd_status() {
    local be_env="$ROOT/desktop/backend-go/.env"
    local status_postgres_port="$POSTGRES_PORT"
    local status_redis_port="$REDIS_PORT"
    local configured_url
    configured_url=$(read_env_value DATABASE_URL "$be_env")
    [ -z "$configured_url" ] || status_postgres_port=$(url_port "$configured_url" 5432)
    configured_url=$(read_env_value REDIS_URL "$be_env")
    [ -z "$configured_url" ] || status_redis_port=$(url_port "$configured_url" 6379)

    printf '%-10s %-7s %-12s %s\n' "Service" "Port" "Status" "PID"
    printf '%-10s %-7s %-12s %s\n' "-------" "----" "------" "---"
    for row in "postgres:$status_postgres_port" "redis:$status_redis_port" "optimal-engine:$ENGINE_PORT" "backend:$BACKEND_PORT" "frontend:$FRONTEND_PORT" "electron:-"; do
        name="${row%%:*}"
        port="${row##*:}"
        if [ "$name" = "postgres" ] && { pg_bin=$(resolve_postgres_bin "$(cat "$RUN_DIR/pgdata/PG_VERSION" 2>/dev/null)" 2>/dev/null); } && "$pg_bin/pg_isready" -h 127.0.0.1 -p "$status_postgres_port" >/dev/null 2>&1; then
            status="$(color '32' 'running')"
            pid="managed"
        elif [ "$name" = "redis" ] && [ -n "$REDIS_CLI" ] && "$REDIS_CLI" -h 127.0.0.1 -p "$status_redis_port" ping >/dev/null 2>&1; then
            status="$(color '32' 'running')"
            pid="$(pid_for redis)"
            [ "$pid" != "-" ] || pid="external"
        elif [ "$name" = "optimal-engine" ] && "$CURL" -sf -m 1 "http://127.0.0.1:$ENGINE_PORT/api/health" >/dev/null 2>&1; then
            status="$(color '32' 'running')"
            pid="$(pid_for optimal-engine)"
            [ "$pid" != "-" ] || pid="external"
        elif pid_alive "$RUN_DIR/$name.pid"; then
            status="$(color '32' 'running')"
            pid=$(cat "$RUN_DIR/$name.pid")
        else
            status="$(color '31' 'down')"
            pid="-"
        fi
        printf '%-10s %-7s %-22s %s\n' "$name" "$port" "$status" "$pid"
    done
}

cmd_verify() {
    ensure_backend_env
    ensure_local_postgres
    ensure_local_redis

    info "Checking backend readiness"
    "$CURL" -fsS -m 5 "http://localhost:$BACKEND_PORT/readyz" >/dev/null
    ok "Backend is ready with database and Redis"

    verify_schema_contract

    info "Checking frontend"
    "$CURL" -fsS -m 5 "http://localhost:$FRONTEND_PORT/" >/dev/null
    ok "Frontend is reachable"

    if [ "${BUSINESSOS_HEADLESS:-0}" != "1" ] && ! pid_alive "$RUN_DIR/electron.pid"; then
        err "Electron is not running. Run: make dev-local-restart"
        return 1
    fi
    if [ "${BUSINESSOS_HEADLESS:-0}" != "1" ]; then
        ok "Electron process is running"
    fi

    if ! "$CURL" -fsS -m 5 "http://127.0.0.1:$ENGINE_PORT/api/health" >/dev/null; then
        err "Optimal Engine is unavailable on :$ENGINE_PORT"
        return 1
    fi
    ok "Optimal Engine is reachable"
}

cmd_logs() {
    exec tail -F "$BACKEND_LOG" "$FRONTEND_LOG" "$ELECTRON_LOG" 2>/dev/null
}

main() {
    case "${1:-start}" in
        start)          cmd_start ;;
        stop)           cmd_stop ;;
        restart)        cmd_stop; sleep 1; cmd_start ;;
        status)         cmd_status ;;
        logs)           cmd_logs ;;
        verify)         cmd_verify ;;
        *) echo "Usage: $0 {start|stop|restart|status|verify|logs}"; exit 1 ;;
    esac
}

if [ "${BASH_SOURCE[0]}" = "$0" ]; then
    main "$@"
fi
